// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/system/config.proto

package system

import (
	common "appforge/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KType         int32                  `protobuf:"varint,2,opt,name=k_type,json=kType,proto3" json:"k_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_proto_system_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{0}
}

func (x *Interval) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interval) GetKType() int32 {
	if x != nil {
		return x.KType
	}
	return 0
}

// 系统配置
type SystemCore struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SiteName           string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`                                                       // 网站名称
	SiteLogo           string                 `protobuf:"bytes,2,opt,name=site_logo,json=siteLogo,proto3" json:"site_logo,omitempty"`                                                       // 网站LOGO
	IsCaptchaEnabled   common.Enable          `protobuf:"varint,3,opt,name=is_captcha_enabled,json=isCaptchaEnabled,proto3,enum=common.Enable" json:"is_captcha_enabled,omitempty"`         // 是否开启验证码,0表示全部，1表示启用，2表示禁用
	IsRegisterEnabled  common.Enable          `protobuf:"varint,4,opt,name=is_register_enabled,json=isRegisterEnabled,proto3,enum=common.Enable" json:"is_register_enabled,omitempty"`      // 是否开启注册,0表示全部，1表示启用，2表示禁用
	IsGuestEnabled     common.Enable          `protobuf:"varint,5,opt,name=is_guest_enabled,json=isGuestEnabled,proto3,enum=common.Enable" json:"is_guest_enabled,omitempty"`               // 是否允许游客登录,0表示全部，1表示启用，2表示禁用
	IsCryptoEnabled    common.Enable          `protobuf:"varint,6,opt,name=is_crypto_enabled,json=isCryptoEnabled,proto3,enum=common.Enable" json:"is_crypto_enabled,omitempty"`            // 是否加密接口提交数据,0表示全部，1表示启用，2表示禁用
	AdminMustGoogleF2A common.Enable          `protobuf:"varint,7,opt,name=admin_must_google_f2a,json=adminMustGoogleF2a,proto3,enum=common.Enable" json:"admin_must_google_f2a,omitempty"` // 管理后台必须开启google验证码
	AppMustGoogleF2A   common.Enable          `protobuf:"varint,8,opt,name=app_must_google_f2a,json=appMustGoogleF2a,proto3,enum=common.Enable" json:"app_must_google_f2a,omitempty"`       // 客户端必须开启google验证码
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SystemCore) Reset() {
	*x = SystemCore{}
	mi := &file_proto_system_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemCore) ProtoMessage() {}

func (x *SystemCore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemCore.ProtoReflect.Descriptor instead.
func (*SystemCore) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{1}
}

func (x *SystemCore) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *SystemCore) GetSiteLogo() string {
	if x != nil {
		return x.SiteLogo
	}
	return ""
}

func (x *SystemCore) GetIsCaptchaEnabled() common.Enable {
	if x != nil {
		return x.IsCaptchaEnabled
	}
	return common.Enable(0)
}

func (x *SystemCore) GetIsRegisterEnabled() common.Enable {
	if x != nil {
		return x.IsRegisterEnabled
	}
	return common.Enable(0)
}

func (x *SystemCore) GetIsGuestEnabled() common.Enable {
	if x != nil {
		return x.IsGuestEnabled
	}
	return common.Enable(0)
}

func (x *SystemCore) GetIsCryptoEnabled() common.Enable {
	if x != nil {
		return x.IsCryptoEnabled
	}
	return common.Enable(0)
}

func (x *SystemCore) GetAdminMustGoogleF2A() common.Enable {
	if x != nil {
		return x.AdminMustGoogleF2A
	}
	return common.Enable(0)
}

func (x *SystemCore) GetAppMustGoogleF2A() common.Enable {
	if x != nil {
		return x.AppMustGoogleF2A
	}
	return common.Enable(0)
}

// 阿里云 OSS配置
type AliyunOssConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,2,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	AccessKeySecret string                 `protobuf:"bytes,3,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	BucketName      string                 `protobuf:"bytes,4,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	BucketUrl       string                 `protobuf:"bytes,5,opt,name=bucket_url,json=bucketUrl,proto3" json:"bucket_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AliyunOssConfig) Reset() {
	*x = AliyunOssConfig{}
	mi := &file_proto_system_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliyunOssConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliyunOssConfig) ProtoMessage() {}

func (x *AliyunOssConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliyunOssConfig.ProtoReflect.Descriptor instead.
func (*AliyunOssConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{2}
}

func (x *AliyunOssConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AliyunOssConfig) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AliyunOssConfig) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

func (x *AliyunOssConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *AliyunOssConfig) GetBucketUrl() string {
	if x != nil {
		return x.BucketUrl
	}
	return ""
}

// 腾讯云 COS配置
type TencentCosConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	SecretKey     string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	BucketName    string                 `protobuf:"bytes,4,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	BucketUrl     string                 `protobuf:"bytes,5,opt,name=bucket_url,json=bucketUrl,proto3" json:"bucket_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TencentCosConfig) Reset() {
	*x = TencentCosConfig{}
	mi := &file_proto_system_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TencentCosConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TencentCosConfig) ProtoMessage() {}

func (x *TencentCosConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TencentCosConfig.ProtoReflect.Descriptor instead.
func (*TencentCosConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{3}
}

func (x *TencentCosConfig) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *TencentCosConfig) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *TencentCosConfig) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *TencentCosConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TencentCosConfig) GetBucketUrl() string {
	if x != nil {
		return x.BucketUrl
	}
	return ""
}

// MINIO配置
type MinioConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,2,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	AccessKeySecret string                 `protobuf:"bytes,3,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	BucketName      string                 `protobuf:"bytes,4,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	BucketUrl       string                 `protobuf:"bytes,5,opt,name=bucket_url,json=bucketUrl,proto3" json:"bucket_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MinioConfig) Reset() {
	*x = MinioConfig{}
	mi := &file_proto_system_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinioConfig) ProtoMessage() {}

func (x *MinioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinioConfig.ProtoReflect.Descriptor instead.
func (*MinioConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{4}
}

func (x *MinioConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MinioConfig) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *MinioConfig) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

func (x *MinioConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *MinioConfig) GetBucketUrl() string {
	if x != nil {
		return x.BucketUrl
	}
	return ""
}

// 对象存储配置
type ObjectStorageConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AliyunOss     *AliyunOssConfig       `protobuf:"bytes,1,opt,name=aliyun_oss,json=aliyunOss,proto3" json:"aliyun_oss,omitempty"`
	TencentCos    *TencentCosConfig      `protobuf:"bytes,2,opt,name=tencent_cos,json=tencentCos,proto3" json:"tencent_cos,omitempty"`
	Minio         *MinioConfig           `protobuf:"bytes,3,opt,name=minio,proto3" json:"minio,omitempty"`
	OssType       int64                  `protobuf:"varint,4,opt,name=oss_type,json=ossType,proto3" json:"oss_type,omitempty"`      // 1阿里云OSS 2腾讯云COS 3MINIO
	OssDomain     string                 `protobuf:"bytes,5,opt,name=oss_domain,json=ossDomain,proto3" json:"oss_domain,omitempty"` // 对象存储访问域名（可选，优先使用bucket_url）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectStorageConfig) Reset() {
	*x = ObjectStorageConfig{}
	mi := &file_proto_system_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectStorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageConfig) ProtoMessage() {}

func (x *ObjectStorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageConfig.ProtoReflect.Descriptor instead.
func (*ObjectStorageConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectStorageConfig) GetAliyunOss() *AliyunOssConfig {
	if x != nil {
		return x.AliyunOss
	}
	return nil
}

func (x *ObjectStorageConfig) GetTencentCos() *TencentCosConfig {
	if x != nil {
		return x.TencentCos
	}
	return nil
}

func (x *ObjectStorageConfig) GetMinio() *MinioConfig {
	if x != nil {
		return x.Minio
	}
	return nil
}

func (x *ObjectStorageConfig) GetOssType() int64 {
	if x != nil {
		return x.OssType
	}
	return 0
}

func (x *ObjectStorageConfig) GetOssDomain() string {
	if x != nil {
		return x.OssDomain
	}
	return ""
}

type ITickConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ApiUrl                   string                 `protobuf:"bytes,1,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`                                                            // ITICK API地址
	ApiToken                 string                 `protobuf:"bytes,2,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`                                                      // ITICK API密钥
	WsUrl                    string                 `protobuf:"bytes,3,opt,name=ws_url,json=wsUrl,proto3" json:"ws_url,omitempty"`                                                               // ITICK WebSocket地址
	ReconcileIntervalMinutes int32                  `protobuf:"varint,4,opt,name=reconcile_interval_minutes,json=reconcileIntervalMinutes,proto3" json:"reconcile_interval_minutes,omitempty"`   // K线校正间隔，默认5分钟
	ReconcileWindowBars      int32                  `protobuf:"varint,5,opt,name=reconcile_window_bars,json=reconcileWindowBars,proto3" json:"reconcile_window_bars,omitempty"`                  // 每次校正最近K线数量，默认30
	GapScanIntervalMinutes   int32                  `protobuf:"varint,6,opt,name=gap_scan_interval_minutes,json=gapScanIntervalMinutes,proto3" json:"gap_scan_interval_minutes,omitempty"`       // 缺口扫描间隔，默认60分钟
	RepairBatchSize          int32                  `protobuf:"varint,7,opt,name=repair_batch_size,json=repairBatchSize,proto3" json:"repair_batch_size,omitempty"`                              // 缺口修复批量大小，默认10
	BuildingBucketTtlMinutes int32                  `protobuf:"varint,8,opt,name=building_bucket_ttl_minutes,json=buildingBucketTtlMinutes,proto3" json:"building_bucket_ttl_minutes,omitempty"` // 当前K线桶Redis TTL，默认120分钟
	WsKlineStaleSeconds      int32                  `protobuf:"varint,9,opt,name=ws_kline_stale_seconds,json=wsKlineStaleSeconds,proto3" json:"ws_kline_stale_seconds,omitempty"`                // WS K线失效时间，默认30秒
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ITickConfig) Reset() {
	*x = ITickConfig{}
	mi := &file_proto_system_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ITickConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ITickConfig) ProtoMessage() {}

func (x *ITickConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ITickConfig.ProtoReflect.Descriptor instead.
func (*ITickConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{6}
}

func (x *ITickConfig) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *ITickConfig) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *ITickConfig) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

func (x *ITickConfig) GetReconcileIntervalMinutes() int32 {
	if x != nil {
		return x.ReconcileIntervalMinutes
	}
	return 0
}

func (x *ITickConfig) GetReconcileWindowBars() int32 {
	if x != nil {
		return x.ReconcileWindowBars
	}
	return 0
}

func (x *ITickConfig) GetGapScanIntervalMinutes() int32 {
	if x != nil {
		return x.GapScanIntervalMinutes
	}
	return 0
}

func (x *ITickConfig) GetRepairBatchSize() int32 {
	if x != nil {
		return x.RepairBatchSize
	}
	return 0
}

func (x *ITickConfig) GetBuildingBucketTtlMinutes() int32 {
	if x != nil {
		return x.BuildingBucketTtlMinutes
	}
	return 0
}

func (x *ITickConfig) GetWsKlineStaleSeconds() int32 {
	if x != nil {
		return x.WsKlineStaleSeconds
	}
	return 0
}

type RechargeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinAmount     string                 `protobuf:"bytes,1,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"` // 最小充值金额，自然货币单位
	MaxAmount     string                 `protobuf:"bytes,2,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"` // 最大充值金额，自然货币单位
	FeeRate       int64                  `protobuf:"varint,3,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`      // 手续费配置，单位：万分之几，例如：100表示1%
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeConfig) Reset() {
	*x = RechargeConfig{}
	mi := &file_proto_system_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeConfig) ProtoMessage() {}

func (x *RechargeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeConfig.ProtoReflect.Descriptor instead.
func (*RechargeConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{7}
}

func (x *RechargeConfig) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *RechargeConfig) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *RechargeConfig) GetFeeRate() int64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

type WithdrawConfig struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	MinAmount                     string                 `protobuf:"bytes,1,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`                                                                    // 最小提现金额，自然货币单位
	MaxAmount                     string                 `protobuf:"bytes,2,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`                                                                    // 最大提现金额，自然货币单位
	FeeRate                       int64                  `protobuf:"varint,3,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`                                                                         // 手续费配置，单位：万分之几，例如：100表示1%
	DailyLimitPerUser             int32                  `protobuf:"varint,4,opt,name=daily_limit_per_user,json=dailyLimitPerUser,proto3" json:"daily_limit_per_user,omitempty"`                                       // 每人每天提现次数限制
	DailyAmountLimitPerUser       string                 `protobuf:"bytes,5,opt,name=daily_amount_limit_per_user,json=dailyAmountLimitPerUser,proto3" json:"daily_amount_limit_per_user,omitempty"`                    // 每人每天提现金额限制，自然货币单位
	AllowedTimeRange              string                 `protobuf:"bytes,6,opt,name=allowed_time_range,json=allowedTimeRange,proto3" json:"allowed_time_range,omitempty"`                                             // 允许提现的时间段，例如：每天9:00-18:00，格式为"09:00-18:00"
	PendingWithdrawalLimitPerUser int32                  `protobuf:"varint,7,opt,name=pending_withdrawal_limit_per_user,json=pendingWithdrawalLimitPerUser,proto3" json:"pending_withdrawal_limit_per_user,omitempty"` // 允许未审核在提现数量限制，单位：笔
	FreeWithdrawTimesPerDay       int32                  `protobuf:"varint,8,opt,name=free_withdraw_times_per_day,json=freeWithdrawTimesPerDay,proto3" json:"free_withdraw_times_per_day,omitempty"`                   // 每日免费提现次数，0=没有免费提现
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *WithdrawConfig) Reset() {
	*x = WithdrawConfig{}
	mi := &file_proto_system_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawConfig) ProtoMessage() {}

func (x *WithdrawConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawConfig.ProtoReflect.Descriptor instead.
func (*WithdrawConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawConfig) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *WithdrawConfig) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *WithdrawConfig) GetFeeRate() int64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

func (x *WithdrawConfig) GetDailyLimitPerUser() int32 {
	if x != nil {
		return x.DailyLimitPerUser
	}
	return 0
}

func (x *WithdrawConfig) GetDailyAmountLimitPerUser() string {
	if x != nil {
		return x.DailyAmountLimitPerUser
	}
	return ""
}

func (x *WithdrawConfig) GetAllowedTimeRange() string {
	if x != nil {
		return x.AllowedTimeRange
	}
	return ""
}

func (x *WithdrawConfig) GetPendingWithdrawalLimitPerUser() int32 {
	if x != nil {
		return x.PendingWithdrawalLimitPerUser
	}
	return 0
}

func (x *WithdrawConfig) GetFreeWithdrawTimesPerDay() int32 {
	if x != nil {
		return x.FreeWithdrawTimesPerDay
	}
	return 0
}

type EmailConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         common.Enable          `protobuf:"varint,1,opt,name=enabled,proto3,enum=common.Enable" json:"enabled,omitempty"`                    // 状态,0表示全部，1表示启用，2表示禁用
	SmtpHost        string                 `protobuf:"bytes,2,opt,name=smtp_host,json=smtpHost,proto3" json:"smtp_host,omitempty"`                      // SMTP 主机
	SmtpPort        int32                  `protobuf:"varint,3,opt,name=smtp_port,json=smtpPort,proto3" json:"smtp_port,omitempty"`                     // SMTP 端口
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`                                      // SMTP 用户名
	Password        string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`                                      // SMTP 密码
	FromEmail       string                 `protobuf:"bytes,6,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`                   // 发件邮箱
	FromName        string                 `protobuf:"bytes,7,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`                      // 发件名称
	SubjectTemplate string                 `protobuf:"bytes,8,opt,name=subject_template,json=subjectTemplate,proto3" json:"subject_template,omitempty"` // 标题模板，支持 {{code}} {{scene}}
	BodyTemplate    string                 `protobuf:"bytes,9,opt,name=body_template,json=bodyTemplate,proto3" json:"body_template,omitempty"`          // 内容模板，支持 {{code}} {{scene}}
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmailConfig) Reset() {
	*x = EmailConfig{}
	mi := &file_proto_system_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailConfig) ProtoMessage() {}

func (x *EmailConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailConfig.ProtoReflect.Descriptor instead.
func (*EmailConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{9}
}

func (x *EmailConfig) GetEnabled() common.Enable {
	if x != nil {
		return x.Enabled
	}
	return common.Enable(0)
}

func (x *EmailConfig) GetSmtpHost() string {
	if x != nil {
		return x.SmtpHost
	}
	return ""
}

func (x *EmailConfig) GetSmtpPort() int32 {
	if x != nil {
		return x.SmtpPort
	}
	return 0
}

func (x *EmailConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EmailConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EmailConfig) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *EmailConfig) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *EmailConfig) GetSubjectTemplate() string {
	if x != nil {
		return x.SubjectTemplate
	}
	return ""
}

func (x *EmailConfig) GetBodyTemplate() string {
	if x != nil {
		return x.BodyTemplate
	}
	return ""
}

type PhoneConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       common.Enable          `protobuf:"varint,1,opt,name=enabled,proto3,enum=common.Enable" json:"enabled,omitempty"`           // 状态,0表示全部，1表示启用，2表示禁用
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`                             // 短信服务商标识
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                             // HTTP 网关地址
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                                 // HTTP 方法，默认 POST
	HeadersJson   string                 `protobuf:"bytes,5,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`    // HTTP headers JSON，例如 {"Authorization":"Bearer xxx"}
	BodyTemplate  string                 `protobuf:"bytes,6,opt,name=body_template,json=bodyTemplate,proto3" json:"body_template,omitempty"` // 请求体模板，支持 {{phone}} {{code}} {{scene}}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneConfig) Reset() {
	*x = PhoneConfig{}
	mi := &file_proto_system_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneConfig) ProtoMessage() {}

func (x *PhoneConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneConfig.ProtoReflect.Descriptor instead.
func (*PhoneConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{10}
}

func (x *PhoneConfig) GetEnabled() common.Enable {
	if x != nil {
		return x.Enabled
	}
	return common.Enable(0)
}

func (x *PhoneConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PhoneConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PhoneConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PhoneConfig) GetHeadersJson() string {
	if x != nil {
		return x.HeadersJson
	}
	return ""
}

func (x *PhoneConfig) GetBodyTemplate() string {
	if x != nil {
		return x.BodyTemplate
	}
	return ""
}

type ChatConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       common.Enable          `protobuf:"varint,1,opt,name=enabled,proto3,enum=common.Enable" json:"enabled,omitempty"`    // 状态:1表示启用，2表示禁用
	Api           string                 `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`                                // 客服API地址
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`            // 客服API Key
	ApiSecret     string                 `protobuf:"bytes,4,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`   // 客服API Secret
	ChatUiUrl     string                 `protobuf:"bytes,5,opt,name=chat_ui_url,json=chatUiUrl,proto3" json:"chat_ui_url,omitempty"` // 客服前端地址
	ChatWsUrl     string                 `protobuf:"bytes,6,opt,name=chat_ws_url,json=chatWsUrl,proto3" json:"chat_ws_url,omitempty"` // 客服WebSocket地址，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatConfig) Reset() {
	*x = ChatConfig{}
	mi := &file_proto_system_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatConfig) ProtoMessage() {}

func (x *ChatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatConfig.ProtoReflect.Descriptor instead.
func (*ChatConfig) Descriptor() ([]byte, []int) {
	return file_proto_system_config_proto_rawDescGZIP(), []int{11}
}

func (x *ChatConfig) GetEnabled() common.Enable {
	if x != nil {
		return x.Enabled
	}
	return common.Enable(0)
}

func (x *ChatConfig) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *ChatConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ChatConfig) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *ChatConfig) GetChatUiUrl() string {
	if x != nil {
		return x.ChatUiUrl
	}
	return ""
}

func (x *ChatConfig) GetChatWsUrl() string {
	if x != nil {
		return x.ChatWsUrl
	}
	return ""
}

var File_proto_system_config_proto protoreflect.FileDescriptor

const file_proto_system_config_proto_rawDesc = "" +
	"\n" +
	"\x19proto/system/config.proto\x12\x06system\x1a\x19proto/common/common.proto\"5\n" +
	"\bInterval\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06k_type\x18\x02 \x01(\x05R\x05kType\"\xbc\x03\n" +
	"\n" +
	"SystemCore\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\x12\x1b\n" +
	"\tsite_logo\x18\x02 \x01(\tR\bsiteLogo\x12<\n" +
	"\x12is_captcha_enabled\x18\x03 \x01(\x0e2\x0e.common.EnableR\x10isCaptchaEnabled\x12>\n" +
	"\x13is_register_enabled\x18\x04 \x01(\x0e2\x0e.common.EnableR\x11isRegisterEnabled\x128\n" +
	"\x10is_guest_enabled\x18\x05 \x01(\x0e2\x0e.common.EnableR\x0eisGuestEnabled\x12:\n" +
	"\x11is_crypto_enabled\x18\x06 \x01(\x0e2\x0e.common.EnableR\x0fisCryptoEnabled\x12A\n" +
	"\x15admin_must_google_f2a\x18\a \x01(\x0e2\x0e.common.EnableR\x12adminMustGoogleF2a\x12=\n" +
	"\x13app_must_google_f2a\x18\b \x01(\x0e2\x0e.common.EnableR\x10appMustGoogleF2a\"\xbd\x01\n" +
	"\x0fAliyunOssConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\"\n" +
	"\raccess_key_id\x18\x02 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11access_key_secret\x18\x03 \x01(\tR\x0faccessKeySecret\x12\x1f\n" +
	"\vbucket_name\x18\x04 \x01(\tR\n" +
	"bucketName\x12\x1d\n" +
	"\n" +
	"bucket_url\x18\x05 \x01(\tR\tbucketUrl\"\xa6\x01\n" +
	"\x10TencentCosConfig\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12\x1f\n" +
	"\vbucket_name\x18\x04 \x01(\tR\n" +
	"bucketName\x12\x1d\n" +
	"\n" +
	"bucket_url\x18\x05 \x01(\tR\tbucketUrl\"\xb9\x01\n" +
	"\vMinioConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\"\n" +
	"\raccess_key_id\x18\x02 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11access_key_secret\x18\x03 \x01(\tR\x0faccessKeySecret\x12\x1f\n" +
	"\vbucket_name\x18\x04 \x01(\tR\n" +
	"bucketName\x12\x1d\n" +
	"\n" +
	"bucket_url\x18\x05 \x01(\tR\tbucketUrl\"\xed\x01\n" +
	"\x13ObjectStorageConfig\x126\n" +
	"\n" +
	"aliyun_oss\x18\x01 \x01(\v2\x17.system.AliyunOssConfigR\taliyunOss\x129\n" +
	"\vtencent_cos\x18\x02 \x01(\v2\x18.system.TencentCosConfigR\n" +
	"tencentCos\x12)\n" +
	"\x05minio\x18\x03 \x01(\v2\x13.system.MinioConfigR\x05minio\x12\x19\n" +
	"\boss_type\x18\x04 \x01(\x03R\aossType\x12\x1d\n" +
	"\n" +
	"oss_domain\x18\x05 \x01(\tR\tossDomain\"\xa7\x03\n" +
	"\vITickConfig\x12\x17\n" +
	"\aapi_url\x18\x01 \x01(\tR\x06apiUrl\x12\x1b\n" +
	"\tapi_token\x18\x02 \x01(\tR\bapiToken\x12\x15\n" +
	"\x06ws_url\x18\x03 \x01(\tR\x05wsUrl\x12<\n" +
	"\x1areconcile_interval_minutes\x18\x04 \x01(\x05R\x18reconcileIntervalMinutes\x122\n" +
	"\x15reconcile_window_bars\x18\x05 \x01(\x05R\x13reconcileWindowBars\x129\n" +
	"\x19gap_scan_interval_minutes\x18\x06 \x01(\x05R\x16gapScanIntervalMinutes\x12*\n" +
	"\x11repair_batch_size\x18\a \x01(\x05R\x0frepairBatchSize\x12=\n" +
	"\x1bbuilding_bucket_ttl_minutes\x18\b \x01(\x05R\x18buildingBucketTtlMinutes\x123\n" +
	"\x16ws_kline_stale_seconds\x18\t \x01(\x05R\x13wsKlineStaleSeconds\"i\n" +
	"\x0eRechargeConfig\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x01 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x02 \x01(\tR\tmaxAmount\x12\x19\n" +
	"\bfee_rate\x18\x03 \x01(\x03R\afeeRate\"\x8e\x03\n" +
	"\x0eWithdrawConfig\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x01 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x02 \x01(\tR\tmaxAmount\x12\x19\n" +
	"\bfee_rate\x18\x03 \x01(\x03R\afeeRate\x12/\n" +
	"\x14daily_limit_per_user\x18\x04 \x01(\x05R\x11dailyLimitPerUser\x12<\n" +
	"\x1bdaily_amount_limit_per_user\x18\x05 \x01(\tR\x17dailyAmountLimitPerUser\x12,\n" +
	"\x12allowed_time_range\x18\x06 \x01(\tR\x10allowedTimeRange\x12H\n" +
	"!pending_withdrawal_limit_per_user\x18\a \x01(\x05R\x1dpendingWithdrawalLimitPerUser\x12<\n" +
	"\x1bfree_withdraw_times_per_day\x18\b \x01(\x05R\x17freeWithdrawTimesPerDay\"\xb5\x02\n" +
	"\vEmailConfig\x12(\n" +
	"\aenabled\x18\x01 \x01(\x0e2\x0e.common.EnableR\aenabled\x12\x1b\n" +
	"\tsmtp_host\x18\x02 \x01(\tR\bsmtpHost\x12\x1b\n" +
	"\tsmtp_port\x18\x03 \x01(\x05R\bsmtpPort\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"from_email\x18\x06 \x01(\tR\tfromEmail\x12\x1b\n" +
	"\tfrom_name\x18\a \x01(\tR\bfromName\x12)\n" +
	"\x10subject_template\x18\b \x01(\tR\x0fsubjectTemplate\x12#\n" +
	"\rbody_template\x18\t \x01(\tR\fbodyTemplate\"\xcf\x01\n" +
	"\vPhoneConfig\x12(\n" +
	"\aenabled\x18\x01 \x01(\x0e2\x0e.common.EnableR\aenabled\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12!\n" +
	"\fheaders_json\x18\x05 \x01(\tR\vheadersJson\x12#\n" +
	"\rbody_template\x18\x06 \x01(\tR\fbodyTemplate\"\xc0\x01\n" +
	"\n" +
	"ChatConfig\x12(\n" +
	"\aenabled\x18\x01 \x01(\x0e2\x0e.common.EnableR\aenabled\x12\x10\n" +
	"\x03api\x18\x02 \x01(\tR\x03api\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x04 \x01(\tR\tapiSecret\x12\x1e\n" +
	"\vchat_ui_url\x18\x05 \x01(\tR\tchatUiUrl\x12\x1e\n" +
	"\vchat_ws_url\x18\x06 \x01(\tR\tchatWsUrlB\x1eZ\x1cappforge/proto/system;systemb\x06proto3"

var (
	file_proto_system_config_proto_rawDescOnce sync.Once
	file_proto_system_config_proto_rawDescData []byte
)

func file_proto_system_config_proto_rawDescGZIP() []byte {
	file_proto_system_config_proto_rawDescOnce.Do(func() {
		file_proto_system_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_config_proto_rawDesc), len(file_proto_system_config_proto_rawDesc)))
	})
	return file_proto_system_config_proto_rawDescData
}

var file_proto_system_config_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_system_config_proto_goTypes = []any{
	(*Interval)(nil),            // 0: system.Interval
	(*SystemCore)(nil),          // 1: system.SystemCore
	(*AliyunOssConfig)(nil),     // 2: system.AliyunOssConfig
	(*TencentCosConfig)(nil),    // 3: system.TencentCosConfig
	(*MinioConfig)(nil),         // 4: system.MinioConfig
	(*ObjectStorageConfig)(nil), // 5: system.ObjectStorageConfig
	(*ITickConfig)(nil),         // 6: system.ITickConfig
	(*RechargeConfig)(nil),      // 7: system.RechargeConfig
	(*WithdrawConfig)(nil),      // 8: system.WithdrawConfig
	(*EmailConfig)(nil),         // 9: system.EmailConfig
	(*PhoneConfig)(nil),         // 10: system.PhoneConfig
	(*ChatConfig)(nil),          // 11: system.ChatConfig
	(common.Enable)(0),          // 12: common.Enable
}
var file_proto_system_config_proto_depIdxs = []int32{
	12, // 0: system.SystemCore.is_captcha_enabled:type_name -> common.Enable
	12, // 1: system.SystemCore.is_register_enabled:type_name -> common.Enable
	12, // 2: system.SystemCore.is_guest_enabled:type_name -> common.Enable
	12, // 3: system.SystemCore.is_crypto_enabled:type_name -> common.Enable
	12, // 4: system.SystemCore.admin_must_google_f2a:type_name -> common.Enable
	12, // 5: system.SystemCore.app_must_google_f2a:type_name -> common.Enable
	2,  // 6: system.ObjectStorageConfig.aliyun_oss:type_name -> system.AliyunOssConfig
	3,  // 7: system.ObjectStorageConfig.tencent_cos:type_name -> system.TencentCosConfig
	4,  // 8: system.ObjectStorageConfig.minio:type_name -> system.MinioConfig
	12, // 9: system.EmailConfig.enabled:type_name -> common.Enable
	12, // 10: system.PhoneConfig.enabled:type_name -> common.Enable
	12, // 11: system.ChatConfig.enabled:type_name -> common.Enable
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_system_config_proto_init() }
func file_proto_system_config_proto_init() {
	if File_proto_system_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_config_proto_rawDesc), len(file_proto_system_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_system_config_proto_goTypes,
		DependencyIndexes: file_proto_system_config_proto_depIdxs,
		MessageInfos:      file_proto_system_config_proto_msgTypes,
	}.Build()
	File_proto_system_config_proto = out.File
	file_proto_system_config_proto_goTypes = nil
	file_proto_system_config_proto_depIdxs = nil
}
