// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tAppSigningConfigFieldNames          = builder.RawFieldNames(&TAppSigningConfig{})
	tAppSigningConfigRows                = strings.Join(tAppSigningConfigFieldNames, ",")
	tAppSigningConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(tAppSigningConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tAppSigningConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(tAppSigningConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTAppSigningConfigIdPrefix                = "cache:tAppSigningConfig:id:"
	cacheTAppSigningConfigTenantIdAppIdNamePrefix = "cache:tAppSigningConfig:tenantId:appId:name:"
)

type (
	tAppSigningConfigModel interface {
		Insert(ctx context.Context, data *TAppSigningConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TAppSigningConfig, error)
		FindOneByTenantIdAppIdName(ctx context.Context, tenantId int64, appId int64, name string) (*TAppSigningConfig, error)
		Update(ctx context.Context, data *TAppSigningConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTAppSigningConfigModel struct {
		sqlc.CachedConn
		table string
	}

	TAppSigningConfig struct {
		Id                         int64          `db:"id"`                           // 签名配置ID
		TenantId                   int64          `db:"tenant_id"`                    // 所属租户ID
		AppId                      int64          `db:"app_id"`                       // 应用ID
		Name                       string         `db:"name"`                         // 签名配置名称
		KeystoreObjectId           int64          `db:"keystore_object_id"`           // 签名文件存储对象ID
		KeystoreObjectKey          string         `db:"keystore_object_key"`          // 私有对象存储中的keystore对象Key
		KeyAlias                   string         `db:"key_alias"`                    // 签名别名
		CertificateSha256          sql.NullString `db:"certificate_sha256"`           // 签名证书SHA-256指纹，小写十六进制
		KeystorePasswordCiphertext sql.NullString `db:"keystore_password_ciphertext"` // keystore密码密文
		KeyPasswordCiphertext      sql.NullString `db:"key_password_ciphertext"`      // key密码密文
		SecretRef                  sql.NullString `db:"secret_ref"`                   // KMS/Secrets Manager/Vault引用
		Status                     int64          `db:"status"`                       // 状态：1启用 2停用
		LastVerifiedAt             sql.NullTime   `db:"last_verified_at"`             // 最近验证时间
		CreateBy                   int64          `db:"create_by"`                    // 创建人ID
		CreateTime                 time.Time      `db:"create_time"`                  // 创建时间
		UpdateTime                 time.Time      `db:"update_time"`                  // 更新时间
	}
)

func newTAppSigningConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTAppSigningConfigModel {
	return &defaultTAppSigningConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_app_signing_config`",
	}
}

func (m *defaultTAppSigningConfigModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tAppSigningConfigIdKey := fmt.Sprintf("%s%v", cacheTAppSigningConfigIdPrefix, id)
	tAppSigningConfigTenantIdAppIdNameKey := fmt.Sprintf("%s%v:%v:%v", cacheTAppSigningConfigTenantIdAppIdNamePrefix, data.TenantId, data.AppId, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tAppSigningConfigIdKey, tAppSigningConfigTenantIdAppIdNameKey)
	return err
}

func (m *defaultTAppSigningConfigModel) FindOne(ctx context.Context, id int64) (*TAppSigningConfig, error) {
	tAppSigningConfigIdKey := fmt.Sprintf("%s%v", cacheTAppSigningConfigIdPrefix, id)
	var resp TAppSigningConfig
	err := m.QueryRowCtx(ctx, &resp, tAppSigningConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tAppSigningConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTAppSigningConfigModel) FindOneByTenantIdAppIdName(ctx context.Context, tenantId int64, appId int64, name string) (*TAppSigningConfig, error) {
	tAppSigningConfigTenantIdAppIdNameKey := fmt.Sprintf("%s%v:%v:%v", cacheTAppSigningConfigTenantIdAppIdNamePrefix, tenantId, appId, name)
	var resp TAppSigningConfig
	err := m.QueryRowIndexCtx(ctx, &resp, tAppSigningConfigTenantIdAppIdNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `app_id` = ? and `name` = ? limit 1", tAppSigningConfigRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, appId, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTAppSigningConfigModel) Insert(ctx context.Context, data *TAppSigningConfig) (sql.Result, error) {
	tAppSigningConfigIdKey := fmt.Sprintf("%s%v", cacheTAppSigningConfigIdPrefix, data.Id)
	tAppSigningConfigTenantIdAppIdNameKey := fmt.Sprintf("%s%v:%v:%v", cacheTAppSigningConfigTenantIdAppIdNamePrefix, data.TenantId, data.AppId, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tAppSigningConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.AppId, data.Name, data.KeystoreObjectId, data.KeystoreObjectKey, data.KeyAlias, data.CertificateSha256, data.KeystorePasswordCiphertext, data.KeyPasswordCiphertext, data.SecretRef, data.Status, data.LastVerifiedAt, data.CreateBy)
	}, tAppSigningConfigIdKey, tAppSigningConfigTenantIdAppIdNameKey)
	return ret, err
}

func (m *defaultTAppSigningConfigModel) Update(ctx context.Context, newData *TAppSigningConfig) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tAppSigningConfigIdKey := fmt.Sprintf("%s%v", cacheTAppSigningConfigIdPrefix, data.Id)
	tAppSigningConfigTenantIdAppIdNameKey := fmt.Sprintf("%s%v:%v:%v", cacheTAppSigningConfigTenantIdAppIdNamePrefix, data.TenantId, data.AppId, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tAppSigningConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.AppId, newData.Name, newData.KeystoreObjectId, newData.KeystoreObjectKey, newData.KeyAlias, newData.CertificateSha256, newData.KeystorePasswordCiphertext, newData.KeyPasswordCiphertext, newData.SecretRef, newData.Status, newData.LastVerifiedAt, newData.CreateBy, newData.Id)
	}, tAppSigningConfigIdKey, tAppSigningConfigTenantIdAppIdNameKey)
	return err
}

func (m *defaultTAppSigningConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTAppSigningConfigIdPrefix, primary)
}

func (m *defaultTAppSigningConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tAppSigningConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTAppSigningConfigModel) tableName() string {
	return m.table
}
