// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tBuildTaskFieldNames          = builder.RawFieldNames(&TBuildTask{})
	tBuildTaskRows                = strings.Join(tBuildTaskFieldNames, ",")
	tBuildTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(tBuildTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tBuildTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(tBuildTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTBuildTaskIdPrefix = "cache:tBuildTask:id:"
)

type (
	tBuildTaskModel interface {
		Insert(ctx context.Context, data *TBuildTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TBuildTask, error)
		Update(ctx context.Context, data *TBuildTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTBuildTaskModel struct {
		sqlc.CachedConn
		table string
	}

	TBuildTask struct {
		Id              int64          `db:"id"`                // 构建任务ID
		TenantId        int64          `db:"tenant_id"`         // 所属租户ID
		AppId           int64          `db:"app_id"`            // 应用ID
		VersionId       int64          `db:"version_id"`        // 应用版本ID
		ChannelId       int64          `db:"channel_id"`        // 渠道ID
		SigningConfigId int64          `db:"signing_config_id"` // 签名配置ID
		ChannelCode     string         `db:"channel_code"`      // 构建时使用的渠道编码快照
		VersionCode     int64          `db:"version_code"`      // 构建时使用的versionCode快照
		VersionName     string         `db:"version_name"`      // 构建时使用的versionName快照
		SourceApkUrl    sql.NullString `db:"source_apk_url"`    // 构建时使用的原始APK地址快照
		BuildConfig     sql.NullString `db:"build_config"`      // 构建时使用的构建配置快照
		Status          string         `db:"status"`            // 构建状态
		BuilderId       sql.NullString `db:"builder_id"`        // Builder工作节点ID
		BuilderAttempt  int64          `db:"builder_attempt"`   // Builder尝试次数
		Priority        int64          `db:"priority"`          // 任务优先级，值越大越优先
		ApkUrl          sql.NullString `db:"apk_url"`           // 构建产物下载地址
		ApkSha256       sql.NullString `db:"apk_sha256"`        // 构建产物SHA-256
		ApkSize         int64          `db:"apk_size"`          // 构建产物大小（字节）
		LogUrl          sql.NullString `db:"log_url"`           // 构建日志地址
		ErrorMessage    sql.NullString `db:"error_message"`     // 失败原因
		QueuedAt        time.Time      `db:"queued_at"`         // 进入队列时间
		StartTime       sql.NullTime   `db:"start_time"`        // 开始构建时间
		FinishTime      sql.NullTime   `db:"finish_time"`       // 完成时间
		LeaseUntil      sql.NullTime   `db:"lease_until"`       // Builder租约到期时间
		CreateBy        int64          `db:"create_by"`         // 创建人ID
		CreateTime      time.Time      `db:"create_time"`       // 创建时间
		UpdateTime      time.Time      `db:"update_time"`       // 更新时间
	}
)

func newTBuildTaskModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTBuildTaskModel {
	return &defaultTBuildTaskModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_build_task`",
	}
}

func (m *defaultTBuildTaskModel) Delete(ctx context.Context, id int64) error {
	tBuildTaskIdKey := fmt.Sprintf("%s%v", cacheTBuildTaskIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tBuildTaskIdKey)
	return err
}

func (m *defaultTBuildTaskModel) FindOne(ctx context.Context, id int64) (*TBuildTask, error) {
	tBuildTaskIdKey := fmt.Sprintf("%s%v", cacheTBuildTaskIdPrefix, id)
	var resp TBuildTask
	err := m.QueryRowCtx(ctx, &resp, tBuildTaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tBuildTaskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTBuildTaskModel) Insert(ctx context.Context, data *TBuildTask) (sql.Result, error) {
	tBuildTaskIdKey := fmt.Sprintf("%s%v", cacheTBuildTaskIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tBuildTaskRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.AppId, data.VersionId, data.ChannelId, data.SigningConfigId, data.ChannelCode, data.VersionCode, data.VersionName, data.SourceApkUrl, data.BuildConfig, data.Status, data.BuilderId, data.BuilderAttempt, data.Priority, data.ApkUrl, data.ApkSha256, data.ApkSize, data.LogUrl, data.ErrorMessage, data.QueuedAt, data.StartTime, data.FinishTime, data.LeaseUntil, data.CreateBy)
	}, tBuildTaskIdKey)
	return ret, err
}

func (m *defaultTBuildTaskModel) Update(ctx context.Context, data *TBuildTask) error {
	tBuildTaskIdKey := fmt.Sprintf("%s%v", cacheTBuildTaskIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tBuildTaskRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TenantId, data.AppId, data.VersionId, data.ChannelId, data.SigningConfigId, data.ChannelCode, data.VersionCode, data.VersionName, data.SourceApkUrl, data.BuildConfig, data.Status, data.BuilderId, data.BuilderAttempt, data.Priority, data.ApkUrl, data.ApkSha256, data.ApkSize, data.LogUrl, data.ErrorMessage, data.QueuedAt, data.StartTime, data.FinishTime, data.LeaseUntil, data.CreateBy, data.Id)
	}, tBuildTaskIdKey)
	return err
}

func (m *defaultTBuildTaskModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTBuildTaskIdPrefix, primary)
}

func (m *defaultTBuildTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tBuildTaskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTBuildTaskModel) tableName() string {
	return m.table
}
