// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tBuildFairQueueFieldNames          = builder.RawFieldNames(&TBuildFairQueue{})
	tBuildFairQueueRows                = strings.Join(tBuildFairQueueFieldNames, ",")
	tBuildFairQueueRowsExpectAutoSet   = strings.Join(stringx.Remove(tBuildFairQueueFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tBuildFairQueueRowsWithPlaceHolder = strings.Join(stringx.Remove(tBuildFairQueueFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTBuildFairQueueIdPrefix               = "cache:tBuildFairQueue:id:"
	cacheTBuildFairQueueTenantIdPoolCodePrefix = "cache:tBuildFairQueue:tenantId:poolCode:"
)

type (
	tBuildFairQueueModel interface {
		Insert(ctx context.Context, data *TBuildFairQueue) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TBuildFairQueue, error)
		FindOneByTenantIdPoolCode(ctx context.Context, tenantId int64, poolCode string) (*TBuildFairQueue, error)
		Update(ctx context.Context, data *TBuildFairQueue) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTBuildFairQueueModel struct {
		sqlc.CachedConn
		table string
	}

	TBuildFairQueue struct {
		Id               int64        `db:"id"`                 // 公平队列状态ID
		TenantId         int64        `db:"tenant_id"`          // 租户ID
		PoolCode         string       `db:"pool_code"`          // 构建池编码
		VirtualFinish    int64        `db:"virtual_finish"`     // 加权公平队列虚拟完成时间
		DispatchCount    int64        `db:"dispatch_count"`     // 累计调度任务数
		LastDispatchedAt sql.NullTime `db:"last_dispatched_at"` // 最近调度时间
		CreateTime       time.Time    `db:"create_time"`        // 创建时间
		UpdateTime       time.Time    `db:"update_time"`        // 更新时间
	}
)

func newTBuildFairQueueModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTBuildFairQueueModel {
	return &defaultTBuildFairQueueModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_build_fair_queue`",
	}
}

func (m *defaultTBuildFairQueueModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tBuildFairQueueIdKey := fmt.Sprintf("%s%v", cacheTBuildFairQueueIdPrefix, id)
	tBuildFairQueueTenantIdPoolCodeKey := fmt.Sprintf("%s%v:%v", cacheTBuildFairQueueTenantIdPoolCodePrefix, data.TenantId, data.PoolCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tBuildFairQueueIdKey, tBuildFairQueueTenantIdPoolCodeKey)
	return err
}

func (m *defaultTBuildFairQueueModel) FindOne(ctx context.Context, id int64) (*TBuildFairQueue, error) {
	tBuildFairQueueIdKey := fmt.Sprintf("%s%v", cacheTBuildFairQueueIdPrefix, id)
	var resp TBuildFairQueue
	err := m.QueryRowCtx(ctx, &resp, tBuildFairQueueIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tBuildFairQueueRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTBuildFairQueueModel) FindOneByTenantIdPoolCode(ctx context.Context, tenantId int64, poolCode string) (*TBuildFairQueue, error) {
	tBuildFairQueueTenantIdPoolCodeKey := fmt.Sprintf("%s%v:%v", cacheTBuildFairQueueTenantIdPoolCodePrefix, tenantId, poolCode)
	var resp TBuildFairQueue
	err := m.QueryRowIndexCtx(ctx, &resp, tBuildFairQueueTenantIdPoolCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `pool_code` = ? limit 1", tBuildFairQueueRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, poolCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTBuildFairQueueModel) Insert(ctx context.Context, data *TBuildFairQueue) (sql.Result, error) {
	tBuildFairQueueIdKey := fmt.Sprintf("%s%v", cacheTBuildFairQueueIdPrefix, data.Id)
	tBuildFairQueueTenantIdPoolCodeKey := fmt.Sprintf("%s%v:%v", cacheTBuildFairQueueTenantIdPoolCodePrefix, data.TenantId, data.PoolCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, tBuildFairQueueRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.PoolCode, data.VirtualFinish, data.DispatchCount, data.LastDispatchedAt)
	}, tBuildFairQueueIdKey, tBuildFairQueueTenantIdPoolCodeKey)
	return ret, err
}

func (m *defaultTBuildFairQueueModel) Update(ctx context.Context, newData *TBuildFairQueue) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tBuildFairQueueIdKey := fmt.Sprintf("%s%v", cacheTBuildFairQueueIdPrefix, data.Id)
	tBuildFairQueueTenantIdPoolCodeKey := fmt.Sprintf("%s%v:%v", cacheTBuildFairQueueTenantIdPoolCodePrefix, data.TenantId, data.PoolCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tBuildFairQueueRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.PoolCode, newData.VirtualFinish, newData.DispatchCount, newData.LastDispatchedAt, newData.Id)
	}, tBuildFairQueueIdKey, tBuildFairQueueTenantIdPoolCodeKey)
	return err
}

func (m *defaultTBuildFairQueueModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTBuildFairQueueIdPrefix, primary)
}

func (m *defaultTBuildFairQueueModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tBuildFairQueueRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTBuildFairQueueModel) tableName() string {
	return m.table
}
