// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tChannelEventFieldNames          = builder.RawFieldNames(&TChannelEvent{})
	tChannelEventRows                = strings.Join(tChannelEventFieldNames, ",")
	tChannelEventRowsExpectAutoSet   = strings.Join(stringx.Remove(tChannelEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tChannelEventRowsWithPlaceHolder = strings.Join(stringx.Remove(tChannelEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTChannelEventIdPrefix                        = "cache:tChannelEvent:id:"
	cacheTChannelEventTenantIdEventTypeEventKeyPrefix = "cache:tChannelEvent:tenantId:eventType:eventKey:"
)

type (
	tChannelEventModel interface {
		Insert(ctx context.Context, data *TChannelEvent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TChannelEvent, error)
		FindOneByTenantIdEventTypeEventKey(ctx context.Context, tenantId int64, eventType int64, eventKey string) (*TChannelEvent, error)
		Update(ctx context.Context, data *TChannelEvent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTChannelEventModel struct {
		sqlc.CachedConn
		table string
	}

	TChannelEvent struct {
		Id          int64          `db:"id"`           // 事件ID
		TenantId    int64          `db:"tenant_id"`    // 所属租户ID
		AppId       int64          `db:"app_id"`       // 应用ID
		ChannelId   int64          `db:"channel_id"`   // 渠道ID
		ChannelCode string         `db:"channel_code"` // 渠道编码
		EventType   int64          `db:"event_type"`   // 事件类型：1点击 2下载 3首次启动 4注册 5首充 6付费
		EventKey    string         `db:"event_key"`    // 事件幂等键
		InstallId   sql.NullString `db:"install_id"`   // 安装ID
		UserId      sql.NullInt64  `db:"user_id"`      // 关联用户ID
		AppVersion  sql.NullString `db:"app_version"`  // 客户端版本
		Ip          sql.NullString `db:"ip"`           // 事件IP
		DeviceModel sql.NullString `db:"device_model"` // 设备型号
		EventTime   time.Time      `db:"event_time"`   // 事件发生时间
		Metadata    sql.NullString `db:"metadata"`     // 事件扩展信息
		CreateTime  time.Time      `db:"create_time"`  // 入库时间
	}
)

func newTChannelEventModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTChannelEventModel {
	return &defaultTChannelEventModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_channel_event`",
	}
}

func (m *defaultTChannelEventModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tChannelEventIdKey := fmt.Sprintf("%s%v", cacheTChannelEventIdPrefix, id)
	tChannelEventTenantIdEventTypeEventKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheTChannelEventTenantIdEventTypeEventKeyPrefix, data.TenantId, data.EventType, data.EventKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tChannelEventIdKey, tChannelEventTenantIdEventTypeEventKeyKey)
	return err
}

func (m *defaultTChannelEventModel) FindOne(ctx context.Context, id int64) (*TChannelEvent, error) {
	tChannelEventIdKey := fmt.Sprintf("%s%v", cacheTChannelEventIdPrefix, id)
	var resp TChannelEvent
	err := m.QueryRowCtx(ctx, &resp, tChannelEventIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tChannelEventRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTChannelEventModel) FindOneByTenantIdEventTypeEventKey(ctx context.Context, tenantId int64, eventType int64, eventKey string) (*TChannelEvent, error) {
	tChannelEventTenantIdEventTypeEventKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheTChannelEventTenantIdEventTypeEventKeyPrefix, tenantId, eventType, eventKey)
	var resp TChannelEvent
	err := m.QueryRowIndexCtx(ctx, &resp, tChannelEventTenantIdEventTypeEventKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `event_type` = ? and `event_key` = ? limit 1", tChannelEventRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, eventType, eventKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTChannelEventModel) Insert(ctx context.Context, data *TChannelEvent) (sql.Result, error) {
	tChannelEventIdKey := fmt.Sprintf("%s%v", cacheTChannelEventIdPrefix, data.Id)
	tChannelEventTenantIdEventTypeEventKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheTChannelEventTenantIdEventTypeEventKeyPrefix, data.TenantId, data.EventType, data.EventKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tChannelEventRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.AppId, data.ChannelId, data.ChannelCode, data.EventType, data.EventKey, data.InstallId, data.UserId, data.AppVersion, data.Ip, data.DeviceModel, data.EventTime, data.Metadata)
	}, tChannelEventIdKey, tChannelEventTenantIdEventTypeEventKeyKey)
	return ret, err
}

func (m *defaultTChannelEventModel) Update(ctx context.Context, newData *TChannelEvent) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tChannelEventIdKey := fmt.Sprintf("%s%v", cacheTChannelEventIdPrefix, data.Id)
	tChannelEventTenantIdEventTypeEventKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheTChannelEventTenantIdEventTypeEventKeyPrefix, data.TenantId, data.EventType, data.EventKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tChannelEventRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.AppId, newData.ChannelId, newData.ChannelCode, newData.EventType, newData.EventKey, newData.InstallId, newData.UserId, newData.AppVersion, newData.Ip, newData.DeviceModel, newData.EventTime, newData.Metadata, newData.Id)
	}, tChannelEventIdKey, tChannelEventTenantIdEventTypeEventKeyKey)
	return err
}

func (m *defaultTChannelEventModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTChannelEventIdPrefix, primary)
}

func (m *defaultTChannelEventModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tChannelEventRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTChannelEventModel) tableName() string {
	return m.table
}
