// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tHybridArtifactReferenceFieldNames          = builder.RawFieldNames(&THybridArtifactReference{})
	tHybridArtifactReferenceRows                = strings.Join(tHybridArtifactReferenceFieldNames, ",")
	tHybridArtifactReferenceRowsExpectAutoSet   = strings.Join(stringx.Remove(tHybridArtifactReferenceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tHybridArtifactReferenceRowsWithPlaceHolder = strings.Join(stringx.Remove(tHybridArtifactReferenceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTHybridArtifactReferenceIdPrefix                                       = "cache:tHybridArtifactReference:id:"
	cacheTHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypePrefix = "cache:tHybridArtifactReference:tenantId:taskId:builderAttempt:artifactType:"
)

type (
	tHybridArtifactReferenceModel interface {
		Insert(ctx context.Context, data *THybridArtifactReference) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*THybridArtifactReference, error)
		FindOneByTenantIdTaskIdBuilderAttemptArtifactType(ctx context.Context, tenantId int64, taskId int64, builderAttempt int64, artifactType int64) (*THybridArtifactReference, error)
		Update(ctx context.Context, data *THybridArtifactReference) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTHybridArtifactReferenceModel struct {
		sqlc.CachedConn
		table string
	}

	THybridArtifactReference struct {
		Id              int64        `db:"id"`               // 混合部署Artifact引用ID
		TenantId        int64        `db:"tenant_id"`        // 所属租户ID
		AgentId         int64        `db:"agent_id"`         // 关联Local Agent ID
		TaskId          int64        `db:"task_id"`          // 关联构建任务ID
		BuilderAttempt  int64        `db:"builder_attempt"`  // 构建任务fencing尝试次数
		ArtifactType    int64        `db:"artifact_type"`    // Artifact类型：1源APK 2构建APK 3构建日志 4离线任务包
		StorageMode     int64        `db:"storage_mode"`     // 存储模式：1控制面存储 2客户存储 3离线包
		ObjectReference string       `db:"object_reference"` // 对象引用或离线包ID，不包含访问凭证
		Sha256          string       `db:"sha256"`           // Artifact内容SHA-256
		SizeBytes       int64        `db:"size_bytes"`       // Artifact大小字节数
		Status          int64        `db:"status"`           // 引用状态：1待校验 2已验证 3已失效
		VerifiedAt      sql.NullTime `db:"verified_at"`      // 大小、SHA、租户和attempt验证时间
		CreateTime      time.Time    `db:"create_time"`      // 创建时间
		UpdateTime      time.Time    `db:"update_time"`      // 更新时间
	}
)

func newTHybridArtifactReferenceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTHybridArtifactReferenceModel {
	return &defaultTHybridArtifactReferenceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_hybrid_artifact_reference`",
	}
}

func (m *defaultTHybridArtifactReferenceModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tHybridArtifactReferenceIdKey := fmt.Sprintf("%s%v", cacheTHybridArtifactReferenceIdPrefix, id)
	tHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypePrefix, data.TenantId, data.TaskId, data.BuilderAttempt, data.ArtifactType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tHybridArtifactReferenceIdKey, tHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypeKey)
	return err
}

func (m *defaultTHybridArtifactReferenceModel) FindOne(ctx context.Context, id int64) (*THybridArtifactReference, error) {
	tHybridArtifactReferenceIdKey := fmt.Sprintf("%s%v", cacheTHybridArtifactReferenceIdPrefix, id)
	var resp THybridArtifactReference
	err := m.QueryRowCtx(ctx, &resp, tHybridArtifactReferenceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tHybridArtifactReferenceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTHybridArtifactReferenceModel) FindOneByTenantIdTaskIdBuilderAttemptArtifactType(ctx context.Context, tenantId int64, taskId int64, builderAttempt int64, artifactType int64) (*THybridArtifactReference, error) {
	tHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypePrefix, tenantId, taskId, builderAttempt, artifactType)
	var resp THybridArtifactReference
	err := m.QueryRowIndexCtx(ctx, &resp, tHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `task_id` = ? and `builder_attempt` = ? and `artifact_type` = ? limit 1", tHybridArtifactReferenceRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, taskId, builderAttempt, artifactType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTHybridArtifactReferenceModel) Insert(ctx context.Context, data *THybridArtifactReference) (sql.Result, error) {
	tHybridArtifactReferenceIdKey := fmt.Sprintf("%s%v", cacheTHybridArtifactReferenceIdPrefix, data.Id)
	tHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypePrefix, data.TenantId, data.TaskId, data.BuilderAttempt, data.ArtifactType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tHybridArtifactReferenceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.AgentId, data.TaskId, data.BuilderAttempt, data.ArtifactType, data.StorageMode, data.ObjectReference, data.Sha256, data.SizeBytes, data.Status, data.VerifiedAt)
	}, tHybridArtifactReferenceIdKey, tHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypeKey)
	return ret, err
}

func (m *defaultTHybridArtifactReferenceModel) Update(ctx context.Context, newData *THybridArtifactReference) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tHybridArtifactReferenceIdKey := fmt.Sprintf("%s%v", cacheTHybridArtifactReferenceIdPrefix, data.Id)
	tHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypePrefix, data.TenantId, data.TaskId, data.BuilderAttempt, data.ArtifactType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tHybridArtifactReferenceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.AgentId, newData.TaskId, newData.BuilderAttempt, newData.ArtifactType, newData.StorageMode, newData.ObjectReference, newData.Sha256, newData.SizeBytes, newData.Status, newData.VerifiedAt, newData.Id)
	}, tHybridArtifactReferenceIdKey, tHybridArtifactReferenceTenantIdTaskIdBuilderAttemptArtifactTypeKey)
	return err
}

func (m *defaultTHybridArtifactReferenceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTHybridArtifactReferenceIdPrefix, primary)
}

func (m *defaultTHybridArtifactReferenceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tHybridArtifactReferenceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTHybridArtifactReferenceModel) tableName() string {
	return m.table
}
