// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tInvoiceItemFieldNames          = builder.RawFieldNames(&TInvoiceItem{})
	tInvoiceItemRows                = strings.Join(tInvoiceItemFieldNames, ",")
	tInvoiceItemRowsExpectAutoSet   = strings.Join(stringx.Remove(tInvoiceItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tInvoiceItemRowsWithPlaceHolder = strings.Join(stringx.Remove(tInvoiceItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTInvoiceItemIdPrefix               = "cache:tInvoiceItem:id:"
	cacheTInvoiceItemInvoiceIdLineKeyPrefix = "cache:tInvoiceItem:invoiceId:lineKey:"
)

type (
	tInvoiceItemModel interface {
		Insert(ctx context.Context, data *TInvoiceItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TInvoiceItem, error)
		FindOneByInvoiceIdLineKey(ctx context.Context, invoiceId int64, lineKey string) (*TInvoiceItem, error)
		Update(ctx context.Context, data *TInvoiceItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTInvoiceItemModel struct {
		sqlc.CachedConn
		table string
	}

	TInvoiceItem struct {
		Id          int64          `db:"id"`          // 账单项ID
		TenantId    int64          `db:"tenant_id"`   // 所属租户ID
		InvoiceId   int64          `db:"invoice_id"`  // 所属账单ID
		LineKey     string         `db:"line_key"`    // 账单内不可变行幂等键
		ItemType    int64          `db:"item_type"`   // 账单项类型：1套餐 2用量 3折扣 4税费 5调整 6退款
		Description string         `db:"description"` // 账单项说明
		Metric      sql.NullString `db:"metric"`      // 用量指标，非用量项为空
		Quantity    int64          `db:"quantity"`    // 计费数量整数
		UnitAmount  int64          `db:"unit_amount"` // 单价，最小货币单位整数
		Amount      int64          `db:"amount"`      // 行金额，最小货币单位整数
		Metadata    sql.NullString `db:"metadata"`    // 套餐版本或用量账本范围JSON
		CreateTime  time.Time      `db:"create_time"` // 创建时间
	}
)

func newTInvoiceItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTInvoiceItemModel {
	return &defaultTInvoiceItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_invoice_item`",
	}
}

func (m *defaultTInvoiceItemModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tInvoiceItemIdKey := fmt.Sprintf("%s%v", cacheTInvoiceItemIdPrefix, id)
	tInvoiceItemInvoiceIdLineKeyKey := fmt.Sprintf("%s%v:%v", cacheTInvoiceItemInvoiceIdLineKeyPrefix, data.InvoiceId, data.LineKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tInvoiceItemIdKey, tInvoiceItemInvoiceIdLineKeyKey)
	return err
}

func (m *defaultTInvoiceItemModel) FindOne(ctx context.Context, id int64) (*TInvoiceItem, error) {
	tInvoiceItemIdKey := fmt.Sprintf("%s%v", cacheTInvoiceItemIdPrefix, id)
	var resp TInvoiceItem
	err := m.QueryRowCtx(ctx, &resp, tInvoiceItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tInvoiceItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTInvoiceItemModel) FindOneByInvoiceIdLineKey(ctx context.Context, invoiceId int64, lineKey string) (*TInvoiceItem, error) {
	tInvoiceItemInvoiceIdLineKeyKey := fmt.Sprintf("%s%v:%v", cacheTInvoiceItemInvoiceIdLineKeyPrefix, invoiceId, lineKey)
	var resp TInvoiceItem
	err := m.QueryRowIndexCtx(ctx, &resp, tInvoiceItemInvoiceIdLineKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `invoice_id` = ? and `line_key` = ? limit 1", tInvoiceItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, invoiceId, lineKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTInvoiceItemModel) Insert(ctx context.Context, data *TInvoiceItem) (sql.Result, error) {
	tInvoiceItemIdKey := fmt.Sprintf("%s%v", cacheTInvoiceItemIdPrefix, data.Id)
	tInvoiceItemInvoiceIdLineKeyKey := fmt.Sprintf("%s%v:%v", cacheTInvoiceItemInvoiceIdLineKeyPrefix, data.InvoiceId, data.LineKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tInvoiceItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.InvoiceId, data.LineKey, data.ItemType, data.Description, data.Metric, data.Quantity, data.UnitAmount, data.Amount, data.Metadata)
	}, tInvoiceItemIdKey, tInvoiceItemInvoiceIdLineKeyKey)
	return ret, err
}

func (m *defaultTInvoiceItemModel) Update(ctx context.Context, newData *TInvoiceItem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tInvoiceItemIdKey := fmt.Sprintf("%s%v", cacheTInvoiceItemIdPrefix, data.Id)
	tInvoiceItemInvoiceIdLineKeyKey := fmt.Sprintf("%s%v:%v", cacheTInvoiceItemInvoiceIdLineKeyPrefix, data.InvoiceId, data.LineKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tInvoiceItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.InvoiceId, newData.LineKey, newData.ItemType, newData.Description, newData.Metric, newData.Quantity, newData.UnitAmount, newData.Amount, newData.Metadata, newData.Id)
	}, tInvoiceItemIdKey, tInvoiceItemInvoiceIdLineKeyKey)
	return err
}

func (m *defaultTInvoiceItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTInvoiceItemIdPrefix, primary)
}

func (m *defaultTInvoiceItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tInvoiceItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTInvoiceItemModel) tableName() string {
	return m.table
}
