// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tQuotaReservationFieldNames          = builder.RawFieldNames(&TQuotaReservation{})
	tQuotaReservationRows                = strings.Join(tQuotaReservationFieldNames, ",")
	tQuotaReservationRowsExpectAutoSet   = strings.Join(stringx.Remove(tQuotaReservationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tQuotaReservationRowsWithPlaceHolder = strings.Join(stringx.Remove(tQuotaReservationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTQuotaReservationIdPrefix                           = "cache:tQuotaReservation:id:"
	cacheTQuotaReservationTenantIdMetricIdempotencyKeyPrefix = "cache:tQuotaReservation:tenantId:metric:idempotencyKey:"
)

type (
	tQuotaReservationModel interface {
		Insert(ctx context.Context, data *TQuotaReservation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TQuotaReservation, error)
		FindOneByTenantIdMetricIdempotencyKey(ctx context.Context, tenantId int64, metric string, idempotencyKey string) (*TQuotaReservation, error)
		Update(ctx context.Context, data *TQuotaReservation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTQuotaReservationModel struct {
		sqlc.CachedConn
		table string
	}

	TQuotaReservation struct {
		Id             int64        `db:"id"`              // 额度预占ID
		TenantId       int64        `db:"tenant_id"`       // 所属租户ID
		Metric         string       `db:"metric"`          // 预占额度指标枚举字符串
		Quantity       int64        `db:"quantity"`        // 预占数量，必须大于0
		ResourceType   string       `db:"resource_type"`   // 预占资源类型
		ResourceId     int64        `db:"resource_id"`     // 预占资源ID，创建前可为0
		IdempotencyKey string       `db:"idempotency_key"` // 预占幂等键
		PeriodKey      string       `db:"period_key"`      // 归属周期键YYYY-MM
		Status         int64        `db:"status"`          // 预占状态：1预占 2确认 3释放 4过期
		ExpiresAt      time.Time    `db:"expires_at"`      // 未确认预占过期时间
		ConfirmedAt    sql.NullTime `db:"confirmed_at"`    // 确认时间
		ReleasedAt     sql.NullTime `db:"released_at"`     // 释放或过期时间
		CreateTime     time.Time    `db:"create_time"`     // 创建时间
		UpdateTime     time.Time    `db:"update_time"`     // 更新时间
	}
)

func newTQuotaReservationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTQuotaReservationModel {
	return &defaultTQuotaReservationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_quota_reservation`",
	}
}

func (m *defaultTQuotaReservationModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tQuotaReservationIdKey := fmt.Sprintf("%s%v", cacheTQuotaReservationIdPrefix, id)
	tQuotaReservationTenantIdMetricIdempotencyKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheTQuotaReservationTenantIdMetricIdempotencyKeyPrefix, data.TenantId, data.Metric, data.IdempotencyKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tQuotaReservationIdKey, tQuotaReservationTenantIdMetricIdempotencyKeyKey)
	return err
}

func (m *defaultTQuotaReservationModel) FindOne(ctx context.Context, id int64) (*TQuotaReservation, error) {
	tQuotaReservationIdKey := fmt.Sprintf("%s%v", cacheTQuotaReservationIdPrefix, id)
	var resp TQuotaReservation
	err := m.QueryRowCtx(ctx, &resp, tQuotaReservationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tQuotaReservationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTQuotaReservationModel) FindOneByTenantIdMetricIdempotencyKey(ctx context.Context, tenantId int64, metric string, idempotencyKey string) (*TQuotaReservation, error) {
	tQuotaReservationTenantIdMetricIdempotencyKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheTQuotaReservationTenantIdMetricIdempotencyKeyPrefix, tenantId, metric, idempotencyKey)
	var resp TQuotaReservation
	err := m.QueryRowIndexCtx(ctx, &resp, tQuotaReservationTenantIdMetricIdempotencyKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `metric` = ? and `idempotency_key` = ? limit 1", tQuotaReservationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, metric, idempotencyKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTQuotaReservationModel) Insert(ctx context.Context, data *TQuotaReservation) (sql.Result, error) {
	tQuotaReservationIdKey := fmt.Sprintf("%s%v", cacheTQuotaReservationIdPrefix, data.Id)
	tQuotaReservationTenantIdMetricIdempotencyKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheTQuotaReservationTenantIdMetricIdempotencyKeyPrefix, data.TenantId, data.Metric, data.IdempotencyKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tQuotaReservationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.Metric, data.Quantity, data.ResourceType, data.ResourceId, data.IdempotencyKey, data.PeriodKey, data.Status, data.ExpiresAt, data.ConfirmedAt, data.ReleasedAt)
	}, tQuotaReservationIdKey, tQuotaReservationTenantIdMetricIdempotencyKeyKey)
	return ret, err
}

func (m *defaultTQuotaReservationModel) Update(ctx context.Context, newData *TQuotaReservation) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tQuotaReservationIdKey := fmt.Sprintf("%s%v", cacheTQuotaReservationIdPrefix, data.Id)
	tQuotaReservationTenantIdMetricIdempotencyKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheTQuotaReservationTenantIdMetricIdempotencyKeyPrefix, data.TenantId, data.Metric, data.IdempotencyKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tQuotaReservationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.Metric, newData.Quantity, newData.ResourceType, newData.ResourceId, newData.IdempotencyKey, newData.PeriodKey, newData.Status, newData.ExpiresAt, newData.ConfirmedAt, newData.ReleasedAt, newData.Id)
	}, tQuotaReservationIdKey, tQuotaReservationTenantIdMetricIdempotencyKeyKey)
	return err
}

func (m *defaultTQuotaReservationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTQuotaReservationIdPrefix, primary)
}

func (m *defaultTQuotaReservationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tQuotaReservationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTQuotaReservationModel) tableName() string {
	return m.table
}
