// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tStorageObjectFieldNames          = builder.RawFieldNames(&TStorageObject{})
	tStorageObjectRows                = strings.Join(tStorageObjectFieldNames, ",")
	tStorageObjectRowsExpectAutoSet   = strings.Join(stringx.Remove(tStorageObjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tStorageObjectRowsWithPlaceHolder = strings.Join(stringx.Remove(tStorageObjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTStorageObjectIdPrefix        = "cache:tStorageObject:id:"
	cacheTStorageObjectObjectKeyPrefix = "cache:tStorageObject:objectKey:"
)

type (
	tStorageObjectModel interface {
		Insert(ctx context.Context, data *TStorageObject) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TStorageObject, error)
		FindOneByObjectKey(ctx context.Context, objectKey string) (*TStorageObject, error)
		Update(ctx context.Context, data *TStorageObject) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTStorageObjectModel struct {
		sqlc.CachedConn
		table string
	}

	TStorageObject struct {
		Id           int64          `db:"id"`            // 存储对象ID
		TenantId     int64          `db:"tenant_id"`     // 所属租户ID
		AppId        int64          `db:"app_id"`        // 关联应用ID，上传时允许为0
		ObjectType   int64          `db:"object_type"`   // 对象类型：1原始APK 2签名文件 3构建APK 4构建日志 5品牌Logo 6品牌启动图
		ObjectKey    string         `db:"object_key"`    // 私有对象存储Key
		OriginalName string         `db:"original_name"` // 用户上传时的原始文件名
		ContentType  string         `db:"content_type"`  // 对象内容类型
		SizeBytes    int64          `db:"size_bytes"`    // 对象大小，单位字节
		Sha256       sql.NullString `db:"sha256"`        // 对象SHA-256，小写十六进制
		Status       int64          `db:"status"`        // 状态：1上传中 2已就绪 3已绑定 4已删除 5失败
		CreateBy     int64          `db:"create_by"`     // 创建人ID
		CreateTime   time.Time      `db:"create_time"`   // 创建时间
		UpdateTime   time.Time      `db:"update_time"`   // 更新时间
	}
)

func newTStorageObjectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTStorageObjectModel {
	return &defaultTStorageObjectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_storage_object`",
	}
}

func (m *defaultTStorageObjectModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tStorageObjectIdKey := fmt.Sprintf("%s%v", cacheTStorageObjectIdPrefix, id)
	tStorageObjectObjectKeyKey := fmt.Sprintf("%s%v", cacheTStorageObjectObjectKeyPrefix, data.ObjectKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tStorageObjectIdKey, tStorageObjectObjectKeyKey)
	return err
}

func (m *defaultTStorageObjectModel) FindOne(ctx context.Context, id int64) (*TStorageObject, error) {
	tStorageObjectIdKey := fmt.Sprintf("%s%v", cacheTStorageObjectIdPrefix, id)
	var resp TStorageObject
	err := m.QueryRowCtx(ctx, &resp, tStorageObjectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tStorageObjectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTStorageObjectModel) FindOneByObjectKey(ctx context.Context, objectKey string) (*TStorageObject, error) {
	tStorageObjectObjectKeyKey := fmt.Sprintf("%s%v", cacheTStorageObjectObjectKeyPrefix, objectKey)
	var resp TStorageObject
	err := m.QueryRowIndexCtx(ctx, &resp, tStorageObjectObjectKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `object_key` = ? limit 1", tStorageObjectRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, objectKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTStorageObjectModel) Insert(ctx context.Context, data *TStorageObject) (sql.Result, error) {
	tStorageObjectIdKey := fmt.Sprintf("%s%v", cacheTStorageObjectIdPrefix, data.Id)
	tStorageObjectObjectKeyKey := fmt.Sprintf("%s%v", cacheTStorageObjectObjectKeyPrefix, data.ObjectKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tStorageObjectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.AppId, data.ObjectType, data.ObjectKey, data.OriginalName, data.ContentType, data.SizeBytes, data.Sha256, data.Status, data.CreateBy)
	}, tStorageObjectIdKey, tStorageObjectObjectKeyKey)
	return ret, err
}

func (m *defaultTStorageObjectModel) Update(ctx context.Context, newData *TStorageObject) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tStorageObjectIdKey := fmt.Sprintf("%s%v", cacheTStorageObjectIdPrefix, data.Id)
	tStorageObjectObjectKeyKey := fmt.Sprintf("%s%v", cacheTStorageObjectObjectKeyPrefix, data.ObjectKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tStorageObjectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.AppId, newData.ObjectType, newData.ObjectKey, newData.OriginalName, newData.ContentType, newData.SizeBytes, newData.Sha256, newData.Status, newData.CreateBy, newData.Id)
	}, tStorageObjectIdKey, tStorageObjectObjectKeyKey)
	return err
}

func (m *defaultTStorageObjectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTStorageObjectIdPrefix, primary)
}

func (m *defaultTStorageObjectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tStorageObjectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTStorageObjectModel) tableName() string {
	return m.table
}
