// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTenantSubscriptionFieldNames          = builder.RawFieldNames(&TTenantSubscription{})
	tTenantSubscriptionRows                = strings.Join(tTenantSubscriptionFieldNames, ",")
	tTenantSubscriptionRowsExpectAutoSet   = strings.Join(stringx.Remove(tTenantSubscriptionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTenantSubscriptionRowsWithPlaceHolder = strings.Join(stringx.Remove(tTenantSubscriptionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTTenantSubscriptionIdPrefix                           = "cache:tTenantSubscription:id:"
	cacheTTenantSubscriptionSourceExternalSubscriptionIdPrefix = "cache:tTenantSubscription:source:externalSubscriptionId:"
	cacheTTenantSubscriptionTenantIdPrefix                     = "cache:tTenantSubscription:tenantId:"
)

type (
	tTenantSubscriptionModel interface {
		Insert(ctx context.Context, data *TTenantSubscription) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTenantSubscription, error)
		FindOneBySourceExternalSubscriptionId(ctx context.Context, source int64, externalSubscriptionId sql.NullString) (*TTenantSubscription, error)
		FindOneByTenantId(ctx context.Context, tenantId int64) (*TTenantSubscription, error)
		Update(ctx context.Context, data *TTenantSubscription) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTenantSubscriptionModel struct {
		sqlc.CachedConn
		table string
	}

	TTenantSubscription struct {
		Id                     int64          `db:"id"`                       // 租户订阅ID
		TenantId               int64          `db:"tenant_id"`                // 所属租户ID
		PlanId                 int64          `db:"plan_id"`                  // 当前套餐版本ID
		PlanVersion            int64          `db:"plan_version"`             // 订阅时固化的套餐版本号
		Status                 int64          `db:"status"`                   // 订阅状态：1生效 2逾期 3宽限 4暂停 5已取消 6待支付
		Source                 int64          `db:"source"`                   // 订阅来源：1Stripe 2人工合同 3平台赠送
		ExternalCustomerId     sql.NullString `db:"external_customer_id"`     // 支付提供商客户ID，人工订阅为空
		ExternalSubscriptionId sql.NullString `db:"external_subscription_id"` // 支付提供商订阅ID，人工订阅为空
		CurrentPeriodStart     time.Time      `db:"current_period_start"`     // 当前计费周期开始时间
		CurrentPeriodEnd       time.Time      `db:"current_period_end"`       // 当前计费周期结束时间
		CancelAtPeriodEnd      int64          `db:"cancel_at_period_end"`     // 周期末取消：0否 1是
		GraceUntil             sql.NullTime   `db:"grace_until"`              // 宽限期截止时间
		PendingPlanId          int64          `db:"pending_plan_id"`          // 周期末待切换套餐版本ID，0表示无
		PendingPlanVersion     int64          `db:"pending_plan_version"`     // 周期末待切换套餐版本号，0表示无
		LastProviderEventAt    sql.NullTime   `db:"last_provider_event_at"`   // 最近已应用支付事件的供应商创建时间
		CreateTime             time.Time      `db:"create_time"`              // 创建时间
		UpdateTime             time.Time      `db:"update_time"`              // 更新时间
	}
)

func newTTenantSubscriptionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTTenantSubscriptionModel {
	return &defaultTTenantSubscriptionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_tenant_subscription`",
	}
}

func (m *defaultTTenantSubscriptionModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tTenantSubscriptionIdKey := fmt.Sprintf("%s%v", cacheTTenantSubscriptionIdPrefix, id)
	tTenantSubscriptionSourceExternalSubscriptionIdKey := fmt.Sprintf("%s%v:%v", cacheTTenantSubscriptionSourceExternalSubscriptionIdPrefix, data.Source, data.ExternalSubscriptionId)
	tTenantSubscriptionTenantIdKey := fmt.Sprintf("%s%v", cacheTTenantSubscriptionTenantIdPrefix, data.TenantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tTenantSubscriptionIdKey, tTenantSubscriptionSourceExternalSubscriptionIdKey, tTenantSubscriptionTenantIdKey)
	return err
}

func (m *defaultTTenantSubscriptionModel) FindOne(ctx context.Context, id int64) (*TTenantSubscription, error) {
	tTenantSubscriptionIdKey := fmt.Sprintf("%s%v", cacheTTenantSubscriptionIdPrefix, id)
	var resp TTenantSubscription
	err := m.QueryRowCtx(ctx, &resp, tTenantSubscriptionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTenantSubscriptionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTenantSubscriptionModel) FindOneBySourceExternalSubscriptionId(ctx context.Context, source int64, externalSubscriptionId sql.NullString) (*TTenantSubscription, error) {
	tTenantSubscriptionSourceExternalSubscriptionIdKey := fmt.Sprintf("%s%v:%v", cacheTTenantSubscriptionSourceExternalSubscriptionIdPrefix, source, externalSubscriptionId)
	var resp TTenantSubscription
	err := m.QueryRowIndexCtx(ctx, &resp, tTenantSubscriptionSourceExternalSubscriptionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `source` = ? and `external_subscription_id` = ? limit 1", tTenantSubscriptionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, source, externalSubscriptionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTenantSubscriptionModel) FindOneByTenantId(ctx context.Context, tenantId int64) (*TTenantSubscription, error) {
	tTenantSubscriptionTenantIdKey := fmt.Sprintf("%s%v", cacheTTenantSubscriptionTenantIdPrefix, tenantId)
	var resp TTenantSubscription
	err := m.QueryRowIndexCtx(ctx, &resp, tTenantSubscriptionTenantIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? limit 1", tTenantSubscriptionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTenantSubscriptionModel) Insert(ctx context.Context, data *TTenantSubscription) (sql.Result, error) {
	tTenantSubscriptionIdKey := fmt.Sprintf("%s%v", cacheTTenantSubscriptionIdPrefix, data.Id)
	tTenantSubscriptionSourceExternalSubscriptionIdKey := fmt.Sprintf("%s%v:%v", cacheTTenantSubscriptionSourceExternalSubscriptionIdPrefix, data.Source, data.ExternalSubscriptionId)
	tTenantSubscriptionTenantIdKey := fmt.Sprintf("%s%v", cacheTTenantSubscriptionTenantIdPrefix, data.TenantId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tTenantSubscriptionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.PlanId, data.PlanVersion, data.Status, data.Source, data.ExternalCustomerId, data.ExternalSubscriptionId, data.CurrentPeriodStart, data.CurrentPeriodEnd, data.CancelAtPeriodEnd, data.GraceUntil, data.PendingPlanId, data.PendingPlanVersion, data.LastProviderEventAt)
	}, tTenantSubscriptionIdKey, tTenantSubscriptionSourceExternalSubscriptionIdKey, tTenantSubscriptionTenantIdKey)
	return ret, err
}

func (m *defaultTTenantSubscriptionModel) Update(ctx context.Context, newData *TTenantSubscription) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tTenantSubscriptionIdKey := fmt.Sprintf("%s%v", cacheTTenantSubscriptionIdPrefix, data.Id)
	tTenantSubscriptionSourceExternalSubscriptionIdKey := fmt.Sprintf("%s%v:%v", cacheTTenantSubscriptionSourceExternalSubscriptionIdPrefix, data.Source, data.ExternalSubscriptionId)
	tTenantSubscriptionTenantIdKey := fmt.Sprintf("%s%v", cacheTTenantSubscriptionTenantIdPrefix, data.TenantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTenantSubscriptionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.PlanId, newData.PlanVersion, newData.Status, newData.Source, newData.ExternalCustomerId, newData.ExternalSubscriptionId, newData.CurrentPeriodStart, newData.CurrentPeriodEnd, newData.CancelAtPeriodEnd, newData.GraceUntil, newData.PendingPlanId, newData.PendingPlanVersion, newData.LastProviderEventAt, newData.Id)
	}, tTenantSubscriptionIdKey, tTenantSubscriptionSourceExternalSubscriptionIdKey, tTenantSubscriptionTenantIdKey)
	return err
}

func (m *defaultTTenantSubscriptionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTTenantSubscriptionIdPrefix, primary)
}

func (m *defaultTTenantSubscriptionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTenantSubscriptionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTTenantSubscriptionModel) tableName() string {
	return m.table
}
