// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTenantEntitlementFieldNames          = builder.RawFieldNames(&TTenantEntitlement{})
	tTenantEntitlementRows                = strings.Join(tTenantEntitlementFieldNames, ",")
	tTenantEntitlementRowsExpectAutoSet   = strings.Join(stringx.Remove(tTenantEntitlementFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTenantEntitlementRowsWithPlaceHolder = strings.Join(stringx.Remove(tTenantEntitlementFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTTenantEntitlementIdPrefix       = "cache:tTenantEntitlement:id:"
	cacheTTenantEntitlementTenantIdPrefix = "cache:tTenantEntitlement:tenantId:"
)

type (
	tTenantEntitlementModel interface {
		Insert(ctx context.Context, data *TTenantEntitlement) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTenantEntitlement, error)
		FindOneByTenantId(ctx context.Context, tenantId int64) (*TTenantEntitlement, error)
		Update(ctx context.Context, data *TTenantEntitlement) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTenantEntitlementModel struct {
		sqlc.CachedConn
		table string
	}

	TTenantEntitlement struct {
		Id                  int64          `db:"id"`                    // 租户权益快照ID
		TenantId            int64          `db:"tenant_id"`             // 所属租户ID
		SourceType          int64          `db:"source_type"`           // 权益来源：1套餐 2人工合同 3平台赠送
		SourceId            int64          `db:"source_id"`             // 来源订阅或人工授权ID
		PlanId              int64          `db:"plan_id"`               // 权益基础套餐版本ID
		PlanVersion         int64          `db:"plan_version"`          // 权益基础套餐版本号
		BuildsPerCycle      int64          `db:"builds_per_cycle"`      // 每周期可计费构建次数，-1不限量
		MaxBuildConcurrency int64          `db:"max_build_concurrency"` // 租户最大构建并发，-1不限量
		StorageBytes        int64          `db:"storage_bytes"`         // 存储额度字节数，-1不限量
		MaxUploadBytes      int64          `db:"max_upload_bytes"`      // 单文件上传上限字节数，-1不限量
		TeamSeats           int64          `db:"team_seats"`            // 团队活跃席位数，-1不限量
		ApiRateLimit        int64          `db:"api_rate_limit"`        // Open API每分钟请求上限，-1不限量
		ChargeFailedBuild   int64          `db:"charge_failed_build"`   // 失败构建计量规则：0不计费 1计费
		ChargeCacheHit      int64          `db:"charge_cache_hit"`      // 缓存命中构建计量规则：0不计费 1计费
		ChargeRetryBuild    int64          `db:"charge_retry_build"`    // 重试构建计量规则：0不计费 1计费
		OverrideJson        sql.NullString `db:"override_json"`         // 人工临时额度和功能覆盖JSON
		ValidFrom           time.Time      `db:"valid_from"`            // 权益生效时间
		ValidUntil          time.Time      `db:"valid_until"`           // 权益失效时间
		Status              int64          `db:"status"`                // 权益状态：1生效 2暂停
		Revision            int64          `db:"revision"`              // 权益快照修订号，每次变更递增
		CreateTime          time.Time      `db:"create_time"`           // 创建时间
		UpdateTime          time.Time      `db:"update_time"`           // 更新时间
	}
)

func newTTenantEntitlementModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTTenantEntitlementModel {
	return &defaultTTenantEntitlementModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_tenant_entitlement`",
	}
}

func (m *defaultTTenantEntitlementModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tTenantEntitlementIdKey := fmt.Sprintf("%s%v", cacheTTenantEntitlementIdPrefix, id)
	tTenantEntitlementTenantIdKey := fmt.Sprintf("%s%v", cacheTTenantEntitlementTenantIdPrefix, data.TenantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tTenantEntitlementIdKey, tTenantEntitlementTenantIdKey)
	return err
}

func (m *defaultTTenantEntitlementModel) FindOne(ctx context.Context, id int64) (*TTenantEntitlement, error) {
	tTenantEntitlementIdKey := fmt.Sprintf("%s%v", cacheTTenantEntitlementIdPrefix, id)
	var resp TTenantEntitlement
	err := m.QueryRowCtx(ctx, &resp, tTenantEntitlementIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTenantEntitlementRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTenantEntitlementModel) FindOneByTenantId(ctx context.Context, tenantId int64) (*TTenantEntitlement, error) {
	tTenantEntitlementTenantIdKey := fmt.Sprintf("%s%v", cacheTTenantEntitlementTenantIdPrefix, tenantId)
	var resp TTenantEntitlement
	err := m.QueryRowIndexCtx(ctx, &resp, tTenantEntitlementTenantIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? limit 1", tTenantEntitlementRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTenantEntitlementModel) Insert(ctx context.Context, data *TTenantEntitlement) (sql.Result, error) {
	tTenantEntitlementIdKey := fmt.Sprintf("%s%v", cacheTTenantEntitlementIdPrefix, data.Id)
	tTenantEntitlementTenantIdKey := fmt.Sprintf("%s%v", cacheTTenantEntitlementTenantIdPrefix, data.TenantId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tTenantEntitlementRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.SourceType, data.SourceId, data.PlanId, data.PlanVersion, data.BuildsPerCycle, data.MaxBuildConcurrency, data.StorageBytes, data.MaxUploadBytes, data.TeamSeats, data.ApiRateLimit, data.ChargeFailedBuild, data.ChargeCacheHit, data.ChargeRetryBuild, data.OverrideJson, data.ValidFrom, data.ValidUntil, data.Status, data.Revision)
	}, tTenantEntitlementIdKey, tTenantEntitlementTenantIdKey)
	return ret, err
}

func (m *defaultTTenantEntitlementModel) Update(ctx context.Context, newData *TTenantEntitlement) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tTenantEntitlementIdKey := fmt.Sprintf("%s%v", cacheTTenantEntitlementIdPrefix, data.Id)
	tTenantEntitlementTenantIdKey := fmt.Sprintf("%s%v", cacheTTenantEntitlementTenantIdPrefix, data.TenantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTenantEntitlementRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.SourceType, newData.SourceId, newData.PlanId, newData.PlanVersion, newData.BuildsPerCycle, newData.MaxBuildConcurrency, newData.StorageBytes, newData.MaxUploadBytes, newData.TeamSeats, newData.ApiRateLimit, newData.ChargeFailedBuild, newData.ChargeCacheHit, newData.ChargeRetryBuild, newData.OverrideJson, newData.ValidFrom, newData.ValidUntil, newData.Status, newData.Revision, newData.Id)
	}, tTenantEntitlementIdKey, tTenantEntitlementTenantIdKey)
	return err
}

func (m *defaultTTenantEntitlementModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTTenantEntitlementIdPrefix, primary)
}

func (m *defaultTTenantEntitlementModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTenantEntitlementRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTTenantEntitlementModel) tableName() string {
	return m.table
}
