// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUsageThresholdNotificationFieldNames          = builder.RawFieldNames(&TUsageThresholdNotification{})
	tUsageThresholdNotificationRows                = strings.Join(tUsageThresholdNotificationFieldNames, ",")
	tUsageThresholdNotificationRowsExpectAutoSet   = strings.Join(stringx.Remove(tUsageThresholdNotificationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tUsageThresholdNotificationRowsWithPlaceHolder = strings.Join(stringx.Remove(tUsageThresholdNotificationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTUsageThresholdNotificationIdPrefix                                      = "cache:tUsageThresholdNotification:id:"
	cacheTUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentPrefix = "cache:tUsageThresholdNotification:tenantId:metric:periodKey:thresholdPercent:"
)

type (
	tUsageThresholdNotificationModel interface {
		Insert(ctx context.Context, data *TUsageThresholdNotification) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TUsageThresholdNotification, error)
		FindOneByTenantIdMetricPeriodKeyThresholdPercent(ctx context.Context, tenantId int64, metric string, periodKey string, thresholdPercent int64) (*TUsageThresholdNotification, error)
		Update(ctx context.Context, data *TUsageThresholdNotification) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTUsageThresholdNotificationModel struct {
		sqlc.CachedConn
		table string
	}

	TUsageThresholdNotification struct {
		Id               int64     `db:"id"`                // 阈值通知ID
		TenantId         int64     `db:"tenant_id"`         // 所属租户ID
		Metric           string    `db:"metric"`            // 用量指标枚举字符串
		PeriodKey        string    `db:"period_key"`        // 归属周期键YYYY-MM
		ThresholdPercent int64     `db:"threshold_percent"` // 触发阈值百分比：70、90或100
		UsageQuantity    int64     `db:"usage_quantity"`    // 触发时当前用量
		LimitQuantity    int64     `db:"limit_quantity"`    // 触发时权益限额
		Status           int64     `db:"status"`            // 通知状态：1待发送 2已发送 3发送失败
		OutboxEventId    int64     `db:"outbox_event_id"`   // 关联quota Webhook Outbox事件ID
		CreateTime       time.Time `db:"create_time"`       // 创建时间
		UpdateTime       time.Time `db:"update_time"`       // 更新时间
	}
)

func newTUsageThresholdNotificationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTUsageThresholdNotificationModel {
	return &defaultTUsageThresholdNotificationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_usage_threshold_notification`",
	}
}

func (m *defaultTUsageThresholdNotificationModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tUsageThresholdNotificationIdKey := fmt.Sprintf("%s%v", cacheTUsageThresholdNotificationIdPrefix, id)
	tUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentPrefix, data.TenantId, data.Metric, data.PeriodKey, data.ThresholdPercent)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tUsageThresholdNotificationIdKey, tUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentKey)
	return err
}

func (m *defaultTUsageThresholdNotificationModel) FindOne(ctx context.Context, id int64) (*TUsageThresholdNotification, error) {
	tUsageThresholdNotificationIdKey := fmt.Sprintf("%s%v", cacheTUsageThresholdNotificationIdPrefix, id)
	var resp TUsageThresholdNotification
	err := m.QueryRowCtx(ctx, &resp, tUsageThresholdNotificationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUsageThresholdNotificationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUsageThresholdNotificationModel) FindOneByTenantIdMetricPeriodKeyThresholdPercent(ctx context.Context, tenantId int64, metric string, periodKey string, thresholdPercent int64) (*TUsageThresholdNotification, error) {
	tUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentPrefix, tenantId, metric, periodKey, thresholdPercent)
	var resp TUsageThresholdNotification
	err := m.QueryRowIndexCtx(ctx, &resp, tUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `metric` = ? and `period_key` = ? and `threshold_percent` = ? limit 1", tUsageThresholdNotificationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, metric, periodKey, thresholdPercent); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUsageThresholdNotificationModel) Insert(ctx context.Context, data *TUsageThresholdNotification) (sql.Result, error) {
	tUsageThresholdNotificationIdKey := fmt.Sprintf("%s%v", cacheTUsageThresholdNotificationIdPrefix, data.Id)
	tUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentPrefix, data.TenantId, data.Metric, data.PeriodKey, data.ThresholdPercent)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tUsageThresholdNotificationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.Metric, data.PeriodKey, data.ThresholdPercent, data.UsageQuantity, data.LimitQuantity, data.Status, data.OutboxEventId)
	}, tUsageThresholdNotificationIdKey, tUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentKey)
	return ret, err
}

func (m *defaultTUsageThresholdNotificationModel) Update(ctx context.Context, newData *TUsageThresholdNotification) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tUsageThresholdNotificationIdKey := fmt.Sprintf("%s%v", cacheTUsageThresholdNotificationIdPrefix, data.Id)
	tUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentPrefix, data.TenantId, data.Metric, data.PeriodKey, data.ThresholdPercent)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tUsageThresholdNotificationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.Metric, newData.PeriodKey, newData.ThresholdPercent, newData.UsageQuantity, newData.LimitQuantity, newData.Status, newData.OutboxEventId, newData.Id)
	}, tUsageThresholdNotificationIdKey, tUsageThresholdNotificationTenantIdMetricPeriodKeyThresholdPercentKey)
	return err
}

func (m *defaultTUsageThresholdNotificationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTUsageThresholdNotificationIdPrefix, primary)
}

func (m *defaultTUsageThresholdNotificationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUsageThresholdNotificationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTUsageThresholdNotificationModel) tableName() string {
	return m.table
}
