// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tWebhookDeliveryFieldNames          = builder.RawFieldNames(&TWebhookDelivery{})
	tWebhookDeliveryRows                = strings.Join(tWebhookDeliveryFieldNames, ",")
	tWebhookDeliveryRowsExpectAutoSet   = strings.Join(stringx.Remove(tWebhookDeliveryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tWebhookDeliveryRowsWithPlaceHolder = strings.Join(stringx.Remove(tWebhookDeliveryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTWebhookDeliveryIdPrefix                      = "cache:tWebhookDelivery:id:"
	cacheTWebhookDeliveryOutboxEventIdEndpointIdPrefix = "cache:tWebhookDelivery:outboxEventId:endpointId:"
)

type (
	tWebhookDeliveryModel interface {
		Insert(ctx context.Context, data *TWebhookDelivery) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TWebhookDelivery, error)
		FindOneByOutboxEventIdEndpointId(ctx context.Context, outboxEventId int64, endpointId int64) (*TWebhookDelivery, error)
		Update(ctx context.Context, data *TWebhookDelivery) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTWebhookDeliveryModel struct {
		sqlc.CachedConn
		table string
	}

	TWebhookDelivery struct {
		Id                  int64          `db:"id"`                    // Webhook投递ID
		TenantId            int64          `db:"tenant_id"`             // 所属租户ID
		EndpointId          int64          `db:"endpoint_id"`           // Webhook端点ID
		OutboxEventId       int64          `db:"outbox_event_id"`       // Outbox事件ID
		EventId             string         `db:"event_id"`              // 对外事件UUID快照
		Attempt             int64          `db:"attempt"`               // 已执行尝试次数
		Status              int64          `db:"status"`                // 状态：1待投递 2投递中 3成功 4待重试 5死信
		ResponseStatus      int64          `db:"response_status"`       // 最近HTTP响应状态码
		ResponseBodyExcerpt sql.NullString `db:"response_body_excerpt"` // 最近响应体摘要
		ErrorMessage        sql.NullString `db:"error_message"`         // 最近错误摘要
		NextRetryAt         time.Time      `db:"next_retry_at"`         // 下次允许投递时间
		LeaseUntil          sql.NullTime   `db:"lease_until"`           // 投递Worker租约到期时间
		DeliveredAt         sql.NullTime   `db:"delivered_at"`          // 投递成功时间
		CreateTime          time.Time      `db:"create_time"`           // 创建时间
		UpdateTime          time.Time      `db:"update_time"`           // 更新时间
	}
)

func newTWebhookDeliveryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTWebhookDeliveryModel {
	return &defaultTWebhookDeliveryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_webhook_delivery`",
	}
}

func (m *defaultTWebhookDeliveryModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tWebhookDeliveryIdKey := fmt.Sprintf("%s%v", cacheTWebhookDeliveryIdPrefix, id)
	tWebhookDeliveryOutboxEventIdEndpointIdKey := fmt.Sprintf("%s%v:%v", cacheTWebhookDeliveryOutboxEventIdEndpointIdPrefix, data.OutboxEventId, data.EndpointId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tWebhookDeliveryIdKey, tWebhookDeliveryOutboxEventIdEndpointIdKey)
	return err
}

func (m *defaultTWebhookDeliveryModel) FindOne(ctx context.Context, id int64) (*TWebhookDelivery, error) {
	tWebhookDeliveryIdKey := fmt.Sprintf("%s%v", cacheTWebhookDeliveryIdPrefix, id)
	var resp TWebhookDelivery
	err := m.QueryRowCtx(ctx, &resp, tWebhookDeliveryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tWebhookDeliveryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTWebhookDeliveryModel) FindOneByOutboxEventIdEndpointId(ctx context.Context, outboxEventId int64, endpointId int64) (*TWebhookDelivery, error) {
	tWebhookDeliveryOutboxEventIdEndpointIdKey := fmt.Sprintf("%s%v:%v", cacheTWebhookDeliveryOutboxEventIdEndpointIdPrefix, outboxEventId, endpointId)
	var resp TWebhookDelivery
	err := m.QueryRowIndexCtx(ctx, &resp, tWebhookDeliveryOutboxEventIdEndpointIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `outbox_event_id` = ? and `endpoint_id` = ? limit 1", tWebhookDeliveryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, outboxEventId, endpointId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTWebhookDeliveryModel) Insert(ctx context.Context, data *TWebhookDelivery) (sql.Result, error) {
	tWebhookDeliveryIdKey := fmt.Sprintf("%s%v", cacheTWebhookDeliveryIdPrefix, data.Id)
	tWebhookDeliveryOutboxEventIdEndpointIdKey := fmt.Sprintf("%s%v:%v", cacheTWebhookDeliveryOutboxEventIdEndpointIdPrefix, data.OutboxEventId, data.EndpointId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tWebhookDeliveryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.EndpointId, data.OutboxEventId, data.EventId, data.Attempt, data.Status, data.ResponseStatus, data.ResponseBodyExcerpt, data.ErrorMessage, data.NextRetryAt, data.LeaseUntil, data.DeliveredAt)
	}, tWebhookDeliveryIdKey, tWebhookDeliveryOutboxEventIdEndpointIdKey)
	return ret, err
}

func (m *defaultTWebhookDeliveryModel) Update(ctx context.Context, newData *TWebhookDelivery) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tWebhookDeliveryIdKey := fmt.Sprintf("%s%v", cacheTWebhookDeliveryIdPrefix, data.Id)
	tWebhookDeliveryOutboxEventIdEndpointIdKey := fmt.Sprintf("%s%v:%v", cacheTWebhookDeliveryOutboxEventIdEndpointIdPrefix, data.OutboxEventId, data.EndpointId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tWebhookDeliveryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.EndpointId, newData.OutboxEventId, newData.EventId, newData.Attempt, newData.Status, newData.ResponseStatus, newData.ResponseBodyExcerpt, newData.ErrorMessage, newData.NextRetryAt, newData.LeaseUntil, newData.DeliveredAt, newData.Id)
	}, tWebhookDeliveryIdKey, tWebhookDeliveryOutboxEventIdEndpointIdKey)
	return err
}

func (m *defaultTWebhookDeliveryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTWebhookDeliveryIdPrefix, primary)
}

func (m *defaultTWebhookDeliveryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tWebhookDeliveryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTWebhookDeliveryModel) tableName() string {
	return m.table
}
