// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tWhiteLabelTemplateRevisionFieldNames          = builder.RawFieldNames(&TWhiteLabelTemplateRevision{})
	tWhiteLabelTemplateRevisionRows                = strings.Join(tWhiteLabelTemplateRevisionFieldNames, ",")
	tWhiteLabelTemplateRevisionRowsExpectAutoSet   = strings.Join(stringx.Remove(tWhiteLabelTemplateRevisionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tWhiteLabelTemplateRevisionRowsWithPlaceHolder = strings.Join(stringx.Remove(tWhiteLabelTemplateRevisionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTWhiteLabelTemplateRevisionIdPrefix                 = "cache:tWhiteLabelTemplateRevision:id:"
	cacheTWhiteLabelTemplateRevisionTemplateIdChecksumPrefix = "cache:tWhiteLabelTemplateRevision:templateId:checksum:"
	cacheTWhiteLabelTemplateRevisionTemplateIdRevisionPrefix = "cache:tWhiteLabelTemplateRevision:templateId:revision:"
)

type (
	tWhiteLabelTemplateRevisionModel interface {
		Insert(ctx context.Context, data *TWhiteLabelTemplateRevision) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TWhiteLabelTemplateRevision, error)
		FindOneByTemplateIdChecksum(ctx context.Context, templateId int64, checksum string) (*TWhiteLabelTemplateRevision, error)
		FindOneByTemplateIdRevision(ctx context.Context, templateId int64, revision int64) (*TWhiteLabelTemplateRevision, error)
		Update(ctx context.Context, data *TWhiteLabelTemplateRevision) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTWhiteLabelTemplateRevisionModel struct {
		sqlc.CachedConn
		table string
	}

	TWhiteLabelTemplateRevision struct {
		Id                int64          `db:"id"`                 // 白标模板修订ID
		TenantId          int64          `db:"tenant_id"`          // 所属租户ID
		TemplateId        int64          `db:"template_id"`        // 白标模板ID
		Revision          int64          `db:"revision"`           // 模板修订号
		PackageNameRule   string         `db:"package_name_rule"`  // 动态包名规则JSON
		ManifestPatch     sql.NullString `db:"manifest_patch"`     // Manifest声明式补丁JSON
		ResourcePatch     sql.NullString `db:"resource_patch"`     // 资源声明式补丁JSON
		ExtensionFiles    sql.NullString `db:"extension_files"`    // 受控扩展文件声明JSON
		ExpectedArtifacts sql.NullString `db:"expected_artifacts"` // 产物验收规则JSON
		Checksum          string         `db:"checksum"`           // 规范化修订内容SHA-256
		Status            int64          `db:"status"`             // 状态：1草稿 2已发布 3已取代
		CreateBy          int64          `db:"create_by"`          // 创建人ID
		CreateTime        time.Time      `db:"create_time"`        // 创建时间
	}
)

func newTWhiteLabelTemplateRevisionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTWhiteLabelTemplateRevisionModel {
	return &defaultTWhiteLabelTemplateRevisionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_white_label_template_revision`",
	}
}

func (m *defaultTWhiteLabelTemplateRevisionModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tWhiteLabelTemplateRevisionIdKey := fmt.Sprintf("%s%v", cacheTWhiteLabelTemplateRevisionIdPrefix, id)
	tWhiteLabelTemplateRevisionTemplateIdChecksumKey := fmt.Sprintf("%s%v:%v", cacheTWhiteLabelTemplateRevisionTemplateIdChecksumPrefix, data.TemplateId, data.Checksum)
	tWhiteLabelTemplateRevisionTemplateIdRevisionKey := fmt.Sprintf("%s%v:%v", cacheTWhiteLabelTemplateRevisionTemplateIdRevisionPrefix, data.TemplateId, data.Revision)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tWhiteLabelTemplateRevisionIdKey, tWhiteLabelTemplateRevisionTemplateIdChecksumKey, tWhiteLabelTemplateRevisionTemplateIdRevisionKey)
	return err
}

func (m *defaultTWhiteLabelTemplateRevisionModel) FindOne(ctx context.Context, id int64) (*TWhiteLabelTemplateRevision, error) {
	tWhiteLabelTemplateRevisionIdKey := fmt.Sprintf("%s%v", cacheTWhiteLabelTemplateRevisionIdPrefix, id)
	var resp TWhiteLabelTemplateRevision
	err := m.QueryRowCtx(ctx, &resp, tWhiteLabelTemplateRevisionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tWhiteLabelTemplateRevisionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTWhiteLabelTemplateRevisionModel) FindOneByTemplateIdChecksum(ctx context.Context, templateId int64, checksum string) (*TWhiteLabelTemplateRevision, error) {
	tWhiteLabelTemplateRevisionTemplateIdChecksumKey := fmt.Sprintf("%s%v:%v", cacheTWhiteLabelTemplateRevisionTemplateIdChecksumPrefix, templateId, checksum)
	var resp TWhiteLabelTemplateRevision
	err := m.QueryRowIndexCtx(ctx, &resp, tWhiteLabelTemplateRevisionTemplateIdChecksumKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `template_id` = ? and `checksum` = ? limit 1", tWhiteLabelTemplateRevisionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, templateId, checksum); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTWhiteLabelTemplateRevisionModel) FindOneByTemplateIdRevision(ctx context.Context, templateId int64, revision int64) (*TWhiteLabelTemplateRevision, error) {
	tWhiteLabelTemplateRevisionTemplateIdRevisionKey := fmt.Sprintf("%s%v:%v", cacheTWhiteLabelTemplateRevisionTemplateIdRevisionPrefix, templateId, revision)
	var resp TWhiteLabelTemplateRevision
	err := m.QueryRowIndexCtx(ctx, &resp, tWhiteLabelTemplateRevisionTemplateIdRevisionKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `template_id` = ? and `revision` = ? limit 1", tWhiteLabelTemplateRevisionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, templateId, revision); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTWhiteLabelTemplateRevisionModel) Insert(ctx context.Context, data *TWhiteLabelTemplateRevision) (sql.Result, error) {
	tWhiteLabelTemplateRevisionIdKey := fmt.Sprintf("%s%v", cacheTWhiteLabelTemplateRevisionIdPrefix, data.Id)
	tWhiteLabelTemplateRevisionTemplateIdChecksumKey := fmt.Sprintf("%s%v:%v", cacheTWhiteLabelTemplateRevisionTemplateIdChecksumPrefix, data.TemplateId, data.Checksum)
	tWhiteLabelTemplateRevisionTemplateIdRevisionKey := fmt.Sprintf("%s%v:%v", cacheTWhiteLabelTemplateRevisionTemplateIdRevisionPrefix, data.TemplateId, data.Revision)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tWhiteLabelTemplateRevisionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.TemplateId, data.Revision, data.PackageNameRule, data.ManifestPatch, data.ResourcePatch, data.ExtensionFiles, data.ExpectedArtifacts, data.Checksum, data.Status, data.CreateBy)
	}, tWhiteLabelTemplateRevisionIdKey, tWhiteLabelTemplateRevisionTemplateIdChecksumKey, tWhiteLabelTemplateRevisionTemplateIdRevisionKey)
	return ret, err
}

func (m *defaultTWhiteLabelTemplateRevisionModel) Update(ctx context.Context, newData *TWhiteLabelTemplateRevision) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tWhiteLabelTemplateRevisionIdKey := fmt.Sprintf("%s%v", cacheTWhiteLabelTemplateRevisionIdPrefix, data.Id)
	tWhiteLabelTemplateRevisionTemplateIdChecksumKey := fmt.Sprintf("%s%v:%v", cacheTWhiteLabelTemplateRevisionTemplateIdChecksumPrefix, data.TemplateId, data.Checksum)
	tWhiteLabelTemplateRevisionTemplateIdRevisionKey := fmt.Sprintf("%s%v:%v", cacheTWhiteLabelTemplateRevisionTemplateIdRevisionPrefix, data.TemplateId, data.Revision)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tWhiteLabelTemplateRevisionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.TemplateId, newData.Revision, newData.PackageNameRule, newData.ManifestPatch, newData.ResourcePatch, newData.ExtensionFiles, newData.ExpectedArtifacts, newData.Checksum, newData.Status, newData.CreateBy, newData.Id)
	}, tWhiteLabelTemplateRevisionIdKey, tWhiteLabelTemplateRevisionTemplateIdChecksumKey, tWhiteLabelTemplateRevisionTemplateIdRevisionKey)
	return err
}

func (m *defaultTWhiteLabelTemplateRevisionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTWhiteLabelTemplateRevisionIdPrefix, primary)
}

func (m *defaultTWhiteLabelTemplateRevisionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tWhiteLabelTemplateRevisionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTWhiteLabelTemplateRevisionModel) tableName() string {
	return m.table
}
