// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: core.proto

package server

import (
	"context"

	"appforge/proto/core"
	"appforge/services/core/internal/logic"
	"appforge/services/core/internal/svc"
)

type CoreServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedCoreServer
}

func NewCoreServer(svcCtx *svc.ServiceContext) *CoreServer {
	return &CoreServer{
		svcCtx: svcCtx,
	}
}

func (s *CoreServer) CreateApplication(ctx context.Context, in *core.CreateApplicationReq) (*core.ApplicationResp, error) {
	l := logic.NewCreateApplicationLogic(ctx, s.svcCtx)
	return l.CreateApplication(in)
}

func (s *CoreServer) GetApplication(ctx context.Context, in *core.ApplicationIdReq) (*core.ApplicationResp, error) {
	l := logic.NewGetApplicationLogic(ctx, s.svcCtx)
	return l.GetApplication(in)
}

func (s *CoreServer) ListApplications(ctx context.Context, in *core.ApplicationListReq) (*core.ApplicationListResp, error) {
	l := logic.NewListApplicationsLogic(ctx, s.svcCtx)
	return l.ListApplications(in)
}

func (s *CoreServer) CreateVersion(ctx context.Context, in *core.CreateVersionReq) (*core.VersionResp, error) {
	l := logic.NewCreateVersionLogic(ctx, s.svcCtx)
	return l.CreateVersion(in)
}

func (s *CoreServer) GetVersion(ctx context.Context, in *core.VersionIdReq) (*core.VersionResp, error) {
	l := logic.NewGetVersionLogic(ctx, s.svcCtx)
	return l.GetVersion(in)
}

func (s *CoreServer) ListVersions(ctx context.Context, in *core.VersionListReq) (*core.VersionListResp, error) {
	l := logic.NewListVersionsLogic(ctx, s.svcCtx)
	return l.ListVersions(in)
}

func (s *CoreServer) CreateChannel(ctx context.Context, in *core.CreateChannelReq) (*core.ChannelResp, error) {
	l := logic.NewCreateChannelLogic(ctx, s.svcCtx)
	return l.CreateChannel(in)
}

func (s *CoreServer) GetChannel(ctx context.Context, in *core.ChannelIdReq) (*core.ChannelResp, error) {
	l := logic.NewGetChannelLogic(ctx, s.svcCtx)
	return l.GetChannel(in)
}

func (s *CoreServer) ListChannels(ctx context.Context, in *core.ChannelListReq) (*core.ChannelListResp, error) {
	l := logic.NewListChannelsLogic(ctx, s.svcCtx)
	return l.ListChannels(in)
}

func (s *CoreServer) CreateSigningConfig(ctx context.Context, in *core.CreateSigningConfigReq) (*core.SigningConfigResp, error) {
	l := logic.NewCreateSigningConfigLogic(ctx, s.svcCtx)
	return l.CreateSigningConfig(in)
}

func (s *CoreServer) GetSigningConfig(ctx context.Context, in *core.SigningConfigIdReq) (*core.SigningConfigResp, error) {
	l := logic.NewGetSigningConfigLogic(ctx, s.svcCtx)
	return l.GetSigningConfig(in)
}

func (s *CoreServer) ListSigningConfigs(ctx context.Context, in *core.SigningConfigListReq) (*core.SigningConfigListResp, error) {
	l := logic.NewListSigningConfigsLogic(ctx, s.svcCtx)
	return l.ListSigningConfigs(in)
}

func (s *CoreServer) CreateBuildTask(ctx context.Context, in *core.CreateBuildTaskReq) (*core.BuildTaskResp, error) {
	l := logic.NewCreateBuildTaskLogic(ctx, s.svcCtx)
	return l.CreateBuildTask(in)
}

func (s *CoreServer) GetBuildTask(ctx context.Context, in *core.BuildTaskIdReq) (*core.BuildTaskResp, error) {
	l := logic.NewGetBuildTaskLogic(ctx, s.svcCtx)
	return l.GetBuildTask(in)
}

func (s *CoreServer) ListBuildTasks(ctx context.Context, in *core.BuildTaskListReq) (*core.BuildTaskListResp, error) {
	l := logic.NewListBuildTasksLogic(ctx, s.svcCtx)
	return l.ListBuildTasks(in)
}

func (s *CoreServer) ReportInstall(ctx context.Context, in *core.InstallReportReq) (*core.RespBase, error) {
	l := logic.NewReportInstallLogic(ctx, s.svcCtx)
	return l.ReportInstall(in)
}

func (s *CoreServer) ReportChannelEvent(ctx context.Context, in *core.ReportChannelEventReq) (*core.RespBase, error) {
	l := logic.NewReportChannelEventLogic(ctx, s.svcCtx)
	return l.ReportChannelEvent(in)
}

func (s *CoreServer) GetChannelStats(ctx context.Context, in *core.ChannelStatsReq) (*core.ChannelStatsResp, error) {
	l := logic.NewGetChannelStatsLogic(ctx, s.svcCtx)
	return l.GetChannelStats(in)
}

func (s *CoreServer) ClaimBuildTask(ctx context.Context, in *core.ClaimBuildTaskReq) (*core.BuildTaskResp, error) {
	l := logic.NewClaimBuildTaskLogic(ctx, s.svcCtx)
	return l.ClaimBuildTask(in)
}

func (s *CoreServer) HeartbeatBuildTask(ctx context.Context, in *core.HeartbeatBuildTaskReq) (*core.RespBase, error) {
	l := logic.NewHeartbeatBuildTaskLogic(ctx, s.svcCtx)
	return l.HeartbeatBuildTask(in)
}

func (s *CoreServer) ReportBuildProgress(ctx context.Context, in *core.ReportBuildProgressReq) (*core.RespBase, error) {
	l := logic.NewReportBuildProgressLogic(ctx, s.svcCtx)
	return l.ReportBuildProgress(in)
}

func (s *CoreServer) CompleteBuildTask(ctx context.Context, in *core.CompleteBuildTaskReq) (*core.RespBase, error) {
	l := logic.NewCompleteBuildTaskLogic(ctx, s.svcCtx)
	return l.CompleteBuildTask(in)
}

func (s *CoreServer) FailBuildTask(ctx context.Context, in *core.FailBuildTaskReq) (*core.RespBase, error) {
	l := logic.NewFailBuildTaskLogic(ctx, s.svcCtx)
	return l.FailBuildTask(in)
}
