// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: core.proto

package server

import (
	"context"

	"appforge/proto/core"
	"appforge/services/core/internal/logic"
	"appforge/services/core/internal/svc"
)

type CoreServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedCoreServer
}

func NewCoreServer(svcCtx *svc.ServiceContext) *CoreServer {
	return &CoreServer{
		svcCtx: svcCtx,
	}
}

func (s *CoreServer) CreateApplication(ctx context.Context, in *core.CreateApplicationReq) (*core.ApplicationResp, error) {
	l := logic.NewCreateApplicationLogic(ctx, s.svcCtx)
	return l.CreateApplication(in)
}

func (s *CoreServer) GetApplication(ctx context.Context, in *core.ApplicationIdReq) (*core.ApplicationResp, error) {
	l := logic.NewGetApplicationLogic(ctx, s.svcCtx)
	return l.GetApplication(in)
}

func (s *CoreServer) ListApplications(ctx context.Context, in *core.ApplicationListReq) (*core.ApplicationListResp, error) {
	l := logic.NewListApplicationsLogic(ctx, s.svcCtx)
	return l.ListApplications(in)
}

// 创建待上传的私有存储对象元数据。
func (s *CoreServer) CreateStorageObject(ctx context.Context, in *core.CreateStorageObjectReq) (*core.StorageObjectResp, error) {
	l := logic.NewCreateStorageObjectLogic(ctx, s.svcCtx)
	return l.CreateStorageObject(in)
}

// 查询当前租户的私有存储对象。
func (s *CoreServer) GetStorageObject(ctx context.Context, in *core.StorageObjectIdReq) (*core.StorageObjectResp, error) {
	l := logic.NewGetStorageObjectLogic(ctx, s.svcCtx)
	return l.GetStorageObject(in)
}

// 完成上传校验并把对象置为可用。
func (s *CoreServer) CompleteStorageObject(ctx context.Context, in *core.CompleteStorageObjectReq) (*core.StorageObjectResp, error) {
	l := logic.NewCompleteStorageObjectLogic(ctx, s.svcCtx)
	return l.CompleteStorageObject(in)
}

// 标记上传或校验失败。
func (s *CoreServer) FailStorageObject(ctx context.Context, in *core.FailStorageObjectReq) (*core.RespBase, error) {
	l := logic.NewFailStorageObjectLogic(ctx, s.svcCtx)
	return l.FailStorageObject(in)
}

// 领取超时未完成或失败的上传对象，供后台清理物理文件。
func (s *CoreServer) ClaimExpiredStorageObjects(ctx context.Context, in *core.ClaimExpiredStorageObjectsReq) (*core.ClaimExpiredStorageObjectsResp, error) {
	l := logic.NewClaimExpiredStorageObjectsLogic(ctx, s.svcCtx)
	return l.ClaimExpiredStorageObjects(in)
}

// 确认物理对象已删除并把元数据置为已删除。
func (s *CoreServer) MarkStorageObjectDeleted(ctx context.Context, in *core.MarkStorageObjectDeletedReq) (*core.RespBase, error) {
	l := logic.NewMarkStorageObjectDeletedLogic(ctx, s.svcCtx)
	return l.MarkStorageObjectDeleted(in)
}

func (s *CoreServer) CreateVersion(ctx context.Context, in *core.CreateVersionReq) (*core.VersionResp, error) {
	l := logic.NewCreateVersionLogic(ctx, s.svcCtx)
	return l.CreateVersion(in)
}

func (s *CoreServer) GetVersion(ctx context.Context, in *core.VersionIdReq) (*core.VersionResp, error) {
	l := logic.NewGetVersionLogic(ctx, s.svcCtx)
	return l.GetVersion(in)
}

func (s *CoreServer) ListVersions(ctx context.Context, in *core.VersionListReq) (*core.VersionListResp, error) {
	l := logic.NewListVersionsLogic(ctx, s.svcCtx)
	return l.ListVersions(in)
}

func (s *CoreServer) CreateChannel(ctx context.Context, in *core.CreateChannelReq) (*core.ChannelResp, error) {
	l := logic.NewCreateChannelLogic(ctx, s.svcCtx)
	return l.CreateChannel(in)
}

func (s *CoreServer) GetChannel(ctx context.Context, in *core.ChannelIdReq) (*core.ChannelResp, error) {
	l := logic.NewGetChannelLogic(ctx, s.svcCtx)
	return l.GetChannel(in)
}

func (s *CoreServer) ListChannels(ctx context.Context, in *core.ChannelListReq) (*core.ChannelListResp, error) {
	l := logic.NewListChannelsLogic(ctx, s.svcCtx)
	return l.ListChannels(in)
}

func (s *CoreServer) CreateSigningConfig(ctx context.Context, in *core.CreateSigningConfigReq) (*core.SigningConfigResp, error) {
	l := logic.NewCreateSigningConfigLogic(ctx, s.svcCtx)
	return l.CreateSigningConfig(in)
}

func (s *CoreServer) GetSigningConfig(ctx context.Context, in *core.SigningConfigIdReq) (*core.SigningConfigResp, error) {
	l := logic.NewGetSigningConfigLogic(ctx, s.svcCtx)
	return l.GetSigningConfig(in)
}

func (s *CoreServer) ListSigningConfigs(ctx context.Context, in *core.SigningConfigListReq) (*core.SigningConfigListResp, error) {
	l := logic.NewListSigningConfigsLogic(ctx, s.svcCtx)
	return l.ListSigningConfigs(in)
}

// 创建应用品牌配置。
func (s *CoreServer) CreateBrandingProfile(ctx context.Context, in *core.CreateBrandingProfileReq) (*core.BrandingProfileResp, error) {
	l := logic.NewCreateBrandingProfileLogic(ctx, s.svcCtx)
	return l.CreateBrandingProfile(in)
}

// 更新应用品牌配置并递增修订号。
func (s *CoreServer) UpdateBrandingProfile(ctx context.Context, in *core.UpdateBrandingProfileReq) (*core.BrandingProfileResp, error) {
	l := logic.NewUpdateBrandingProfileLogic(ctx, s.svcCtx)
	return l.UpdateBrandingProfile(in)
}

// 查询当前租户的品牌配置。
func (s *CoreServer) GetBrandingProfile(ctx context.Context, in *core.BrandingProfileIdReq) (*core.BrandingProfileResp, error) {
	l := logic.NewGetBrandingProfileLogic(ctx, s.svcCtx)
	return l.GetBrandingProfile(in)
}

// 分页查询当前租户的品牌配置。
func (s *CoreServer) ListBrandingProfiles(ctx context.Context, in *core.BrandingProfileListReq) (*core.BrandingProfileListResp, error) {
	l := logic.NewListBrandingProfilesLogic(ctx, s.svcCtx)
	return l.ListBrandingProfiles(in)
}

// 修改品牌配置状态。
func (s *CoreServer) ChangeBrandingProfileStatus(ctx context.Context, in *core.ChangeBrandingProfileStatusReq) (*core.BrandingProfileResp, error) {
	l := logic.NewChangeBrandingProfileStatusLogic(ctx, s.svcCtx)
	return l.ChangeBrandingProfileStatus(in)
}

// 创建或重置品牌兼容性预检记录。
func (s *CoreServer) CreateBrandingPreflight(ctx context.Context, in *core.CreateBrandingPreflightReq) (*core.BrandingPreflightResp, error) {
	l := logic.NewCreateBrandingPreflightLogic(ctx, s.svcCtx)
	return l.CreateBrandingPreflight(in)
}

// 查询品牌兼容性预检记录。
func (s *CoreServer) GetBrandingPreflight(ctx context.Context, in *core.BrandingPreflightIdReq) (*core.BrandingPreflightResp, error) {
	l := logic.NewGetBrandingPreflightLogic(ctx, s.svcCtx)
	return l.GetBrandingPreflight(in)
}

// 分页查询品牌兼容性预检记录。
func (s *CoreServer) ListBrandingPreflights(ctx context.Context, in *core.BrandingPreflightListReq) (*core.BrandingPreflightListResp, error) {
	l := logic.NewListBrandingPreflightsLogic(ctx, s.svcCtx)
	return l.ListBrandingPreflights(in)
}

// 原子领取一个待处理或租约过期的品牌兼容性预检。
func (s *CoreServer) ClaimBrandingPreflight(ctx context.Context, in *core.ClaimBrandingPreflightReq) (*core.BrandingPreflightExecutionContextResp, error) {
	l := logic.NewClaimBrandingPreflightLogic(ctx, s.svcCtx)
	return l.ClaimBrandingPreflight(in)
}

// 完成品牌兼容性预检。
func (s *CoreServer) CompleteBrandingPreflight(ctx context.Context, in *core.CompleteBrandingPreflightReq) (*core.BrandingPreflightResp, error) {
	l := logic.NewCompleteBrandingPreflightLogic(ctx, s.svcCtx)
	return l.CompleteBrandingPreflight(in)
}

// 创建V3白标模板。
func (s *CoreServer) CreateWhiteLabelTemplate(ctx context.Context, in *core.CreateWhiteLabelTemplateReq) (*core.WhiteLabelTemplateResp, error) {
	l := logic.NewCreateWhiteLabelTemplateLogic(ctx, s.svcCtx)
	return l.CreateWhiteLabelTemplate(in)
}

// 更新尚未发布的V3白标模板。
func (s *CoreServer) UpdateWhiteLabelTemplate(ctx context.Context, in *core.UpdateWhiteLabelTemplateReq) (*core.WhiteLabelTemplateResp, error) {
	l := logic.NewUpdateWhiteLabelTemplateLogic(ctx, s.svcCtx)
	return l.UpdateWhiteLabelTemplate(in)
}

// 复制V3白标模板及其修订为新草稿。
func (s *CoreServer) CopyWhiteLabelTemplate(ctx context.Context, in *core.CopyWhiteLabelTemplateReq) (*core.WhiteLabelTemplateResp, error) {
	l := logic.NewCopyWhiteLabelTemplateLogic(ctx, s.svcCtx)
	return l.CopyWhiteLabelTemplate(in)
}

// 删除从未发布且未被产品引用的V3白标模板。
func (s *CoreServer) DeleteWhiteLabelTemplate(ctx context.Context, in *core.WhiteLabelTemplateIdReq) (*core.RespBase, error) {
	l := logic.NewDeleteWhiteLabelTemplateLogic(ctx, s.svcCtx)
	return l.DeleteWhiteLabelTemplate(in)
}

// 查询V3白标模板。
func (s *CoreServer) GetWhiteLabelTemplate(ctx context.Context, in *core.WhiteLabelTemplateIdReq) (*core.WhiteLabelTemplateResp, error) {
	l := logic.NewGetWhiteLabelTemplateLogic(ctx, s.svcCtx)
	return l.GetWhiteLabelTemplate(in)
}

// 分页查询V3白标模板。
func (s *CoreServer) ListWhiteLabelTemplates(ctx context.Context, in *core.WhiteLabelTemplateListReq) (*core.WhiteLabelTemplateListResp, error) {
	l := logic.NewListWhiteLabelTemplatesLogic(ctx, s.svcCtx)
	return l.ListWhiteLabelTemplates(in)
}

// 创建不可变模板修订。
func (s *CoreServer) CreateWhiteLabelTemplateRevision(ctx context.Context, in *core.CreateWhiteLabelTemplateRevisionReq) (*core.WhiteLabelTemplateRevisionResp, error) {
	l := logic.NewCreateWhiteLabelTemplateRevisionLogic(ctx, s.svcCtx)
	return l.CreateWhiteLabelTemplateRevision(in)
}

// 查询单个模板修订。
func (s *CoreServer) GetWhiteLabelTemplateRevision(ctx context.Context, in *core.WhiteLabelTemplateRevisionIdReq) (*core.WhiteLabelTemplateRevisionResp, error) {
	l := logic.NewGetWhiteLabelTemplateRevisionLogic(ctx, s.svcCtx)
	return l.GetWhiteLabelTemplateRevision(in)
}

// 更新尚未发布的模板草稿修订。
func (s *CoreServer) UpdateWhiteLabelTemplateRevision(ctx context.Context, in *core.UpdateWhiteLabelTemplateRevisionReq) (*core.WhiteLabelTemplateRevisionResp, error) {
	l := logic.NewUpdateWhiteLabelTemplateRevisionLogic(ctx, s.svcCtx)
	return l.UpdateWhiteLabelTemplateRevision(in)
}

// 删除尚未发布的模板草稿修订。
func (s *CoreServer) DeleteWhiteLabelTemplateRevision(ctx context.Context, in *core.WhiteLabelTemplateRevisionIdReq) (*core.RespBase, error) {
	l := logic.NewDeleteWhiteLabelTemplateRevisionLogic(ctx, s.svcCtx)
	return l.DeleteWhiteLabelTemplateRevision(in)
}

// 查询模板修订。
func (s *CoreServer) ListWhiteLabelTemplateRevisions(ctx context.Context, in *core.WhiteLabelTemplateRevisionListReq) (*core.WhiteLabelTemplateRevisionListResp, error) {
	l := logic.NewListWhiteLabelTemplateRevisionsLogic(ctx, s.svcCtx)
	return l.ListWhiteLabelTemplateRevisions(in)
}

// 发布模板修订。
func (s *CoreServer) PublishWhiteLabelTemplate(ctx context.Context, in *core.PublishWhiteLabelTemplateReq) (*core.WhiteLabelTemplateResp, error) {
	l := logic.NewPublishWhiteLabelTemplateLogic(ctx, s.svcCtx)
	return l.PublishWhiteLabelTemplate(in)
}

// 修改V3白标模板状态。
func (s *CoreServer) ChangeWhiteLabelTemplateStatus(ctx context.Context, in *core.ChangeWhiteLabelTemplateStatusReq) (*core.WhiteLabelTemplateResp, error) {
	l := logic.NewChangeWhiteLabelTemplateStatusLogic(ctx, s.svcCtx)
	return l.ChangeWhiteLabelTemplateStatus(in)
}

// 创建V3白标产品。
func (s *CoreServer) CreateWhiteLabelProduct(ctx context.Context, in *core.CreateWhiteLabelProductReq) (*core.WhiteLabelProductResp, error) {
	l := logic.NewCreateWhiteLabelProductLogic(ctx, s.svcCtx)
	return l.CreateWhiteLabelProduct(in)
}

// 更新V3白标产品。
func (s *CoreServer) UpdateWhiteLabelProduct(ctx context.Context, in *core.UpdateWhiteLabelProductReq) (*core.WhiteLabelProductResp, error) {
	l := logic.NewUpdateWhiteLabelProductLogic(ctx, s.svcCtx)
	return l.UpdateWhiteLabelProduct(in)
}

// 删除未启用且没有历史构建的V3白标产品。
func (s *CoreServer) DeleteWhiteLabelProduct(ctx context.Context, in *core.WhiteLabelProductIdReq) (*core.RespBase, error) {
	l := logic.NewDeleteWhiteLabelProductLogic(ctx, s.svcCtx)
	return l.DeleteWhiteLabelProduct(in)
}

// 查询V3白标产品。
func (s *CoreServer) GetWhiteLabelProduct(ctx context.Context, in *core.WhiteLabelProductIdReq) (*core.WhiteLabelProductResp, error) {
	l := logic.NewGetWhiteLabelProductLogic(ctx, s.svcCtx)
	return l.GetWhiteLabelProduct(in)
}

// 分页查询V3白标产品。
func (s *CoreServer) ListWhiteLabelProducts(ctx context.Context, in *core.WhiteLabelProductListReq) (*core.WhiteLabelProductListResp, error) {
	l := logic.NewListWhiteLabelProductsLogic(ctx, s.svcCtx)
	return l.ListWhiteLabelProducts(in)
}

// 修改V3白标产品状态。
func (s *CoreServer) ChangeWhiteLabelProductStatus(ctx context.Context, in *core.ChangeWhiteLabelProductStatusReq) (*core.WhiteLabelProductResp, error) {
	l := logic.NewChangeWhiteLabelProductStatusLogic(ctx, s.svcCtx)
	return l.ChangeWhiteLabelProductStatus(in)
}

// 同步预检V3白标产品契约和依赖。
func (s *CoreServer) PreflightWhiteLabelProduct(ctx context.Context, in *core.WhiteLabelProductIdReq) (*core.WhiteLabelProductPreflightResp, error) {
	l := logic.NewPreflightWhiteLabelProductLogic(ctx, s.svcCtx)
	return l.PreflightWhiteLabelProduct(in)
}

func (s *CoreServer) CreateBuildTask(ctx context.Context, in *core.CreateBuildTaskReq) (*core.BuildTaskResp, error) {
	l := logic.NewCreateBuildTaskLogic(ctx, s.svcCtx)
	return l.CreateBuildTask(in)
}

func (s *CoreServer) GetBuildTask(ctx context.Context, in *core.BuildTaskIdReq) (*core.BuildTaskResp, error) {
	l := logic.NewGetBuildTaskLogic(ctx, s.svcCtx)
	return l.GetBuildTask(in)
}

func (s *CoreServer) ListBuildTasks(ctx context.Context, in *core.BuildTaskListReq) (*core.BuildTaskListResp, error) {
	l := logic.NewListBuildTasksLogic(ctx, s.svcCtx)
	return l.ListBuildTasks(in)
}

func (s *CoreServer) ReportInstall(ctx context.Context, in *core.InstallReportReq) (*core.RespBase, error) {
	l := logic.NewReportInstallLogic(ctx, s.svcCtx)
	return l.ReportInstall(in)
}

func (s *CoreServer) ReportChannelEvent(ctx context.Context, in *core.ReportChannelEventReq) (*core.RespBase, error) {
	l := logic.NewReportChannelEventLogic(ctx, s.svcCtx)
	return l.ReportChannelEvent(in)
}

func (s *CoreServer) GetChannelStats(ctx context.Context, in *core.ChannelStatsReq) (*core.ChannelStatsResp, error) {
	l := logic.NewGetChannelStatsLogic(ctx, s.svcCtx)
	return l.GetChannelStats(in)
}

// 解析渠道最新成功产物并幂等记录点击、下载事件。
func (s *CoreServer) ResolveChannelDownload(ctx context.Context, in *core.ResolveChannelDownloadReq) (*core.ChannelDownloadArtifactResp, error) {
	l := logic.NewResolveChannelDownloadLogic(ctx, s.svcCtx)
	return l.ResolveChannelDownload(in)
}

func (s *CoreServer) ClaimBuildTask(ctx context.Context, in *core.ClaimBuildTaskReq) (*core.BuildTaskResp, error) {
	l := logic.NewClaimBuildTaskLogic(ctx, s.svcCtx)
	return l.ClaimBuildTask(in)
}

// 读取当前Builder已领取任务的内部执行上下文。
func (s *CoreServer) GetBuildExecutionContext(ctx context.Context, in *core.GetBuildExecutionContextReq) (*core.BuildExecutionContextResp, error) {
	l := logic.NewGetBuildExecutionContextLogic(ctx, s.svcCtx)
	return l.GetBuildExecutionContext(in)
}

func (s *CoreServer) HeartbeatBuildTask(ctx context.Context, in *core.HeartbeatBuildTaskReq) (*core.RespBase, error) {
	l := logic.NewHeartbeatBuildTaskLogic(ctx, s.svcCtx)
	return l.HeartbeatBuildTask(in)
}

func (s *CoreServer) ReportBuildProgress(ctx context.Context, in *core.ReportBuildProgressReq) (*core.RespBase, error) {
	l := logic.NewReportBuildProgressLogic(ctx, s.svcCtx)
	return l.ReportBuildProgress(in)
}

func (s *CoreServer) CompleteBuildTask(ctx context.Context, in *core.CompleteBuildTaskReq) (*core.RespBase, error) {
	l := logic.NewCompleteBuildTaskLogic(ctx, s.svcCtx)
	return l.CompleteBuildTask(in)
}

func (s *CoreServer) FailBuildTask(ctx context.Context, in *core.FailBuildTaskReq) (*core.RespBase, error) {
	l := logic.NewFailBuildTaskLogic(ctx, s.svcCtx)
	return l.FailBuildTask(in)
}
