// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysTenantFieldNames          = builder.RawFieldNames(&SysTenant{})
	sysTenantRows                = strings.Join(sysTenantFieldNames, ",")
	sysTenantRowsExpectAutoSet   = strings.Join(stringx.Remove(sysTenantFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysTenantRowsWithPlaceHolder = strings.Join(stringx.Remove(sysTenantFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysTenantIdPrefix         = "cache:sysTenant:id:"
	cacheSysTenantTenantCodePrefix = "cache:sysTenant:tenantCode:"
)

type (
	sysTenantModel interface {
		Insert(ctx context.Context, data *SysTenant) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysTenant, error)
		FindOneByTenantCode(ctx context.Context, tenantCode string) (*SysTenant, error)
		Update(ctx context.Context, data *SysTenant) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysTenantModel struct {
		sqlc.CachedConn
		table string
	}

	SysTenant struct {
		Id           int64          `db:"id"`            // 租户ID
		TenantCode   string         `db:"tenant_code"`   // 租户编码
		TenantName   string         `db:"tenant_name"`   // 租户名称
		Enabled      int64          `db:"enabled"`       // 启用开关：1启用 2禁用
		ExpireTime   int64          `db:"expire_time"`   // 到期时间
		ContactName  sql.NullString `db:"contact_name"`  // 联系人
		ContactPhone sql.NullString `db:"contact_phone"` // 联系电话
		LoginIp      sql.NullString `db:"login_ip"`      // 最后登录IP
		LoginTime    int64          `db:"login_time"`    // 最后登录时间
		LoginCount   int64          `db:"login_count"`   // 登录次数
		Remark       sql.NullString `db:"remark"`        // 备注
		CreateBy     sql.NullString `db:"create_by"`     // 创建人
		CreateTimes  int64          `db:"create_times"`  // 创建时间
		UpdateBy     sql.NullString `db:"update_by"`     // 更新人
		UpdateTimes  int64          `db:"update_times"`  // 更新时间
	}
)

func newSysTenantModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysTenantModel {
	return &defaultSysTenantModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_tenant`",
	}
}

func (m *defaultSysTenantModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysTenantIdKey := fmt.Sprintf("%s%v", cacheSysTenantIdPrefix, id)
	sysTenantTenantCodeKey := fmt.Sprintf("%s%v", cacheSysTenantTenantCodePrefix, data.TenantCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysTenantIdKey, sysTenantTenantCodeKey)
	return err
}

func (m *defaultSysTenantModel) FindOne(ctx context.Context, id int64) (*SysTenant, error) {
	sysTenantIdKey := fmt.Sprintf("%s%v", cacheSysTenantIdPrefix, id)
	var resp SysTenant
	err := m.QueryRowCtx(ctx, &resp, sysTenantIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysTenantRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysTenantModel) FindOneByTenantCode(ctx context.Context, tenantCode string) (*SysTenant, error) {
	sysTenantTenantCodeKey := fmt.Sprintf("%s%v", cacheSysTenantTenantCodePrefix, tenantCode)
	var resp SysTenant
	err := m.QueryRowIndexCtx(ctx, &resp, sysTenantTenantCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_code` = ? limit 1", sysTenantRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysTenantModel) Insert(ctx context.Context, data *SysTenant) (sql.Result, error) {
	sysTenantIdKey := fmt.Sprintf("%s%v", cacheSysTenantIdPrefix, data.Id)
	sysTenantTenantCodeKey := fmt.Sprintf("%s%v", cacheSysTenantTenantCodePrefix, data.TenantCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysTenantRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantCode, data.TenantName, data.Enabled, data.ExpireTime, data.ContactName, data.ContactPhone, data.LoginIp, data.LoginTime, data.LoginCount, data.Remark, data.CreateBy, data.CreateTimes, data.UpdateBy, data.UpdateTimes)
	}, sysTenantIdKey, sysTenantTenantCodeKey)
	return ret, err
}

func (m *defaultSysTenantModel) Update(ctx context.Context, newData *SysTenant) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysTenantIdKey := fmt.Sprintf("%s%v", cacheSysTenantIdPrefix, data.Id)
	sysTenantTenantCodeKey := fmt.Sprintf("%s%v", cacheSysTenantTenantCodePrefix, data.TenantCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysTenantRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantCode, newData.TenantName, newData.Enabled, newData.ExpireTime, newData.ContactName, newData.ContactPhone, newData.LoginIp, newData.LoginTime, newData.LoginCount, newData.Remark, newData.CreateBy, newData.CreateTimes, newData.UpdateBy, newData.UpdateTimes, newData.Id)
	}, sysTenantIdKey, sysTenantTenantCodeKey)
	return err
}

func (m *defaultSysTenantModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysTenantIdPrefix, primary)
}

func (m *defaultSysTenantModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysTenantRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysTenantModel) tableName() string {
	return m.table
}
