// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysTenantDomainFieldNames          = builder.RawFieldNames(&SysTenantDomain{})
	sysTenantDomainRows                = strings.Join(sysTenantDomainFieldNames, ",")
	sysTenantDomainRowsExpectAutoSet   = strings.Join(stringx.Remove(sysTenantDomainFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysTenantDomainRowsWithPlaceHolder = strings.Join(stringx.Remove(sysTenantDomainFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysTenantDomainIdPrefix             = "cache:sysTenantDomain:id:"
	cacheSysTenantDomainTenantIdOriginPrefix = "cache:sysTenantDomain:tenantId:origin:"
)

type (
	sysTenantDomainModel interface {
		Insert(ctx context.Context, data *SysTenantDomain) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysTenantDomain, error)
		FindOneByTenantIdOrigin(ctx context.Context, tenantId int64, origin string) (*SysTenantDomain, error)
		Update(ctx context.Context, data *SysTenantDomain) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysTenantDomainModel struct {
		sqlc.CachedConn
		table string
	}

	SysTenantDomain struct {
		Id          int64  `db:"id"`           // 主键ID
		TenantId    int64  `db:"tenant_id"`    // 租户ID
		Origin      string `db:"origin"`       // 规范化域名Origin
		Status      int64  `db:"status"`       // 1使用中 2已退役 3已禁用
		Priority    int64  `db:"priority"`     // 使用中域名跳转优先级
		CreateTimes int64  `db:"create_times"` // 创建时间（Unix毫秒）
		UpdateTimes int64  `db:"update_times"` // 更新时间（Unix毫秒）
	}
)

func newSysTenantDomainModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysTenantDomainModel {
	return &defaultSysTenantDomainModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_tenant_domain`",
	}
}

func (m *defaultSysTenantDomainModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysTenantDomainIdKey := fmt.Sprintf("%s%v", cacheSysTenantDomainIdPrefix, id)
	sysTenantDomainTenantIdOriginKey := fmt.Sprintf("%s%v:%v", cacheSysTenantDomainTenantIdOriginPrefix, data.TenantId, data.Origin)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysTenantDomainIdKey, sysTenantDomainTenantIdOriginKey)
	return err
}

func (m *defaultSysTenantDomainModel) FindOne(ctx context.Context, id int64) (*SysTenantDomain, error) {
	sysTenantDomainIdKey := fmt.Sprintf("%s%v", cacheSysTenantDomainIdPrefix, id)
	var resp SysTenantDomain
	err := m.QueryRowCtx(ctx, &resp, sysTenantDomainIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysTenantDomainRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysTenantDomainModel) FindOneByTenantIdOrigin(ctx context.Context, tenantId int64, origin string) (*SysTenantDomain, error) {
	sysTenantDomainTenantIdOriginKey := fmt.Sprintf("%s%v:%v", cacheSysTenantDomainTenantIdOriginPrefix, tenantId, origin)
	var resp SysTenantDomain
	err := m.QueryRowIndexCtx(ctx, &resp, sysTenantDomainTenantIdOriginKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `origin` = ? limit 1", sysTenantDomainRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, origin); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysTenantDomainModel) Insert(ctx context.Context, data *SysTenantDomain) (sql.Result, error) {
	sysTenantDomainIdKey := fmt.Sprintf("%s%v", cacheSysTenantDomainIdPrefix, data.Id)
	sysTenantDomainTenantIdOriginKey := fmt.Sprintf("%s%v:%v", cacheSysTenantDomainTenantIdOriginPrefix, data.TenantId, data.Origin)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, sysTenantDomainRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.Origin, data.Status, data.Priority, data.CreateTimes, data.UpdateTimes)
	}, sysTenantDomainIdKey, sysTenantDomainTenantIdOriginKey)
	return ret, err
}

func (m *defaultSysTenantDomainModel) Update(ctx context.Context, newData *SysTenantDomain) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysTenantDomainIdKey := fmt.Sprintf("%s%v", cacheSysTenantDomainIdPrefix, data.Id)
	sysTenantDomainTenantIdOriginKey := fmt.Sprintf("%s%v:%v", cacheSysTenantDomainTenantIdOriginPrefix, data.TenantId, data.Origin)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysTenantDomainRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.Origin, newData.Status, newData.Priority, newData.CreateTimes, newData.UpdateTimes, newData.Id)
	}, sysTenantDomainIdKey, sysTenantDomainTenantIdOriginKey)
	return err
}

func (m *defaultSysTenantDomainModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysTenantDomainIdPrefix, primary)
}

func (m *defaultSysTenantDomainModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysTenantDomainRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysTenantDomainModel) tableName() string {
	return m.table
}
