// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/builder/builder.proto

package builder

import (
	common "appforge/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APK 构建任务状态。
type BuildTaskStatus int32

const (
	BuildTaskStatus_BUILD_TASK_STATUS_UNKNOWN   BuildTaskStatus = 0 // 未知
	BuildTaskStatus_BUILD_TASK_STATUS_PENDING   BuildTaskStatus = 1 // 待处理
	BuildTaskStatus_BUILD_TASK_STATUS_BUILDING  BuildTaskStatus = 2 // 构建中
	BuildTaskStatus_BUILD_TASK_STATUS_SIGNING   BuildTaskStatus = 3 // 签名中
	BuildTaskStatus_BUILD_TASK_STATUS_UPLOADING BuildTaskStatus = 4 // 上传中
	BuildTaskStatus_BUILD_TASK_STATUS_SUCCESS   BuildTaskStatus = 5 // 成功
	BuildTaskStatus_BUILD_TASK_STATUS_FAILED    BuildTaskStatus = 6 // 失败
)

// Enum value maps for BuildTaskStatus.
var (
	BuildTaskStatus_name = map[int32]string{
		0: "BUILD_TASK_STATUS_UNKNOWN",
		1: "BUILD_TASK_STATUS_PENDING",
		2: "BUILD_TASK_STATUS_BUILDING",
		3: "BUILD_TASK_STATUS_SIGNING",
		4: "BUILD_TASK_STATUS_UPLOADING",
		5: "BUILD_TASK_STATUS_SUCCESS",
		6: "BUILD_TASK_STATUS_FAILED",
	}
	BuildTaskStatus_value = map[string]int32{
		"BUILD_TASK_STATUS_UNKNOWN":   0,
		"BUILD_TASK_STATUS_PENDING":   1,
		"BUILD_TASK_STATUS_BUILDING":  2,
		"BUILD_TASK_STATUS_SIGNING":   3,
		"BUILD_TASK_STATUS_UPLOADING": 4,
		"BUILD_TASK_STATUS_SUCCESS":   5,
		"BUILD_TASK_STATUS_FAILED":    6,
	}
)

func (x BuildTaskStatus) Enum() *BuildTaskStatus {
	p := new(BuildTaskStatus)
	*p = x
	return p
}

func (x BuildTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_builder_builder_proto_enumTypes[0].Descriptor()
}

func (BuildTaskStatus) Type() protoreflect.EnumType {
	return &file_proto_builder_builder_proto_enumTypes[0]
}

func (x BuildTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildTaskStatus.Descriptor instead.
func (BuildTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{0}
}

type RespBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.RespBase       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespBase) Reset() {
	*x = RespBase{}
	mi := &file_proto_builder_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBase) ProtoMessage() {}

func (x *RespBase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespBase.ProtoReflect.Descriptor instead.
func (*RespBase) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{0}
}

func (x *RespBase) GetBase() *common.RespBase {
	if x != nil {
		return x.Base
	}
	return nil
}

type BuildTask struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId          int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AppId             int64                  `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionId         int64                  `protobuf:"varint,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ChannelId         int64                  `protobuf:"varint,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SigningConfigId   int64                  `protobuf:"varint,6,opt,name=signing_config_id,json=signingConfigId,proto3" json:"signing_config_id,omitempty"`
	ChannelCode       string                 `protobuf:"bytes,7,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	VersionCode       int64                  `protobuf:"varint,8,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	VersionName       string                 `protobuf:"bytes,9,opt,name=version_name,json=versionName,proto3" json:"version_name,omitempty"`
	Status            BuildTaskStatus        `protobuf:"varint,10,opt,name=status,proto3,enum=builder.BuildTaskStatus" json:"status,omitempty"` // 构建任务状态
	BuilderAttempt    int32                  `protobuf:"varint,11,opt,name=builder_attempt,json=builderAttempt,proto3" json:"builder_attempt,omitempty"`
	Priority          int32                  `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty"`
	SourceApkUrl      string                 `protobuf:"bytes,13,opt,name=source_apk_url,json=sourceApkUrl,proto3" json:"source_apk_url,omitempty"`
	BuildConfigJson   string                 `protobuf:"bytes,14,opt,name=build_config_json,json=buildConfigJson,proto3" json:"build_config_json,omitempty"`
	SourceApkObjectId int64                  `protobuf:"varint,15,opt,name=source_apk_object_id,json=sourceApkObjectId,proto3" json:"source_apk_object_id,omitempty"` // 原始APK私有对象ID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BuildTask) Reset() {
	*x = BuildTask{}
	mi := &file_proto_builder_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTask) ProtoMessage() {}

func (x *BuildTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTask.ProtoReflect.Descriptor instead.
func (*BuildTask) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{1}
}

func (x *BuildTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildTask) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BuildTask) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *BuildTask) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *BuildTask) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *BuildTask) GetSigningConfigId() int64 {
	if x != nil {
		return x.SigningConfigId
	}
	return 0
}

func (x *BuildTask) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *BuildTask) GetVersionCode() int64 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *BuildTask) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *BuildTask) GetStatus() BuildTaskStatus {
	if x != nil {
		return x.Status
	}
	return BuildTaskStatus_BUILD_TASK_STATUS_UNKNOWN
}

func (x *BuildTask) GetBuilderAttempt() int32 {
	if x != nil {
		return x.BuilderAttempt
	}
	return 0
}

func (x *BuildTask) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *BuildTask) GetSourceApkUrl() string {
	if x != nil {
		return x.SourceApkUrl
	}
	return ""
}

func (x *BuildTask) GetBuildConfigJson() string {
	if x != nil {
		return x.BuildConfigJson
	}
	return ""
}

func (x *BuildTask) GetSourceApkObjectId() int64 {
	if x != nil {
		return x.SourceApkObjectId
	}
	return 0
}

type ClaimBuildTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuilderId     string                 `protobuf:"bytes,1,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	LeaseSeconds  int32                  `protobuf:"varint,2,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimBuildTaskReq) Reset() {
	*x = ClaimBuildTaskReq{}
	mi := &file_proto_builder_builder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimBuildTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimBuildTaskReq) ProtoMessage() {}

func (x *ClaimBuildTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimBuildTaskReq.ProtoReflect.Descriptor instead.
func (*ClaimBuildTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimBuildTaskReq) GetBuilderId() string {
	if x != nil {
		return x.BuilderId
	}
	return ""
}

func (x *ClaimBuildTaskReq) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

type BuildTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.RespBase       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *BuildTask             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTaskResp) Reset() {
	*x = BuildTaskResp{}
	mi := &file_proto_builder_builder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTaskResp) ProtoMessage() {}

func (x *BuildTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTaskResp.ProtoReflect.Descriptor instead.
func (*BuildTaskResp) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{3}
}

func (x *BuildTaskResp) GetBase() *common.RespBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *BuildTaskResp) GetData() *BuildTask {
	if x != nil {
		return x.Data
	}
	return nil
}

type HeartbeatBuildTaskReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BuilderId      string                 `protobuf:"bytes,2,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	LeaseSeconds   int32                  `protobuf:"varint,3,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	BuilderAttempt int32                  `protobuf:"varint,4,opt,name=builder_attempt,json=builderAttempt,proto3" json:"builder_attempt,omitempty"` // 本次领取代次，用于阻止过期Worker回写
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatBuildTaskReq) Reset() {
	*x = HeartbeatBuildTaskReq{}
	mi := &file_proto_builder_builder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatBuildTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatBuildTaskReq) ProtoMessage() {}

func (x *HeartbeatBuildTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatBuildTaskReq.ProtoReflect.Descriptor instead.
func (*HeartbeatBuildTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatBuildTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *HeartbeatBuildTaskReq) GetBuilderId() string {
	if x != nil {
		return x.BuilderId
	}
	return ""
}

func (x *HeartbeatBuildTaskReq) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

func (x *HeartbeatBuildTaskReq) GetBuilderAttempt() int32 {
	if x != nil {
		return x.BuilderAttempt
	}
	return 0
}

type ReportBuildProgressReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BuilderId      string                 `protobuf:"bytes,2,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	Status         BuildTaskStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=builder.BuildTaskStatus" json:"status,omitempty"` // 当前构建任务状态
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Progress       int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	BuilderAttempt int32                  `protobuf:"varint,6,opt,name=builder_attempt,json=builderAttempt,proto3" json:"builder_attempt,omitempty"` // 本次领取代次，用于阻止过期Worker回写
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportBuildProgressReq) Reset() {
	*x = ReportBuildProgressReq{}
	mi := &file_proto_builder_builder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportBuildProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBuildProgressReq) ProtoMessage() {}

func (x *ReportBuildProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBuildProgressReq.ProtoReflect.Descriptor instead.
func (*ReportBuildProgressReq) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{5}
}

func (x *ReportBuildProgressReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportBuildProgressReq) GetBuilderId() string {
	if x != nil {
		return x.BuilderId
	}
	return ""
}

func (x *ReportBuildProgressReq) GetStatus() BuildTaskStatus {
	if x != nil {
		return x.Status
	}
	return BuildTaskStatus_BUILD_TASK_STATUS_UNKNOWN
}

func (x *ReportBuildProgressReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportBuildProgressReq) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ReportBuildProgressReq) GetBuilderAttempt() int32 {
	if x != nil {
		return x.BuilderAttempt
	}
	return 0
}

type CompleteBuildTaskReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BuilderId      string                 `protobuf:"bytes,2,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	ApkUrl         string                 `protobuf:"bytes,3,opt,name=apk_url,json=apkUrl,proto3" json:"apk_url,omitempty"`
	ApkSha256      string                 `protobuf:"bytes,4,opt,name=apk_sha256,json=apkSha256,proto3" json:"apk_sha256,omitempty"`
	ApkSize        int64                  `protobuf:"varint,5,opt,name=apk_size,json=apkSize,proto3" json:"apk_size,omitempty"`
	LogUrl         string                 `protobuf:"bytes,6,opt,name=log_url,json=logUrl,proto3" json:"log_url,omitempty"`
	ApkObjectKey   string                 `protobuf:"bytes,7,opt,name=apk_object_key,json=apkObjectKey,proto3" json:"apk_object_key,omitempty"`       // 构建产物私有对象Key
	LogObjectKey   string                 `protobuf:"bytes,8,opt,name=log_object_key,json=logObjectKey,proto3" json:"log_object_key,omitempty"`       // 构建日志私有对象Key
	LogSha256      string                 `protobuf:"bytes,9,opt,name=log_sha256,json=logSha256,proto3" json:"log_sha256,omitempty"`                  // 构建日志SHA-256
	LogSize        int64                  `protobuf:"varint,10,opt,name=log_size,json=logSize,proto3" json:"log_size,omitempty"`                      // 构建日志大小，单位字节
	BuilderAttempt int32                  `protobuf:"varint,11,opt,name=builder_attempt,json=builderAttempt,proto3" json:"builder_attempt,omitempty"` // 本次领取代次，用于阻止过期Worker回写
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteBuildTaskReq) Reset() {
	*x = CompleteBuildTaskReq{}
	mi := &file_proto_builder_builder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBuildTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBuildTaskReq) ProtoMessage() {}

func (x *CompleteBuildTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBuildTaskReq.ProtoReflect.Descriptor instead.
func (*CompleteBuildTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteBuildTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CompleteBuildTaskReq) GetBuilderId() string {
	if x != nil {
		return x.BuilderId
	}
	return ""
}

func (x *CompleteBuildTaskReq) GetApkUrl() string {
	if x != nil {
		return x.ApkUrl
	}
	return ""
}

func (x *CompleteBuildTaskReq) GetApkSha256() string {
	if x != nil {
		return x.ApkSha256
	}
	return ""
}

func (x *CompleteBuildTaskReq) GetApkSize() int64 {
	if x != nil {
		return x.ApkSize
	}
	return 0
}

func (x *CompleteBuildTaskReq) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *CompleteBuildTaskReq) GetApkObjectKey() string {
	if x != nil {
		return x.ApkObjectKey
	}
	return ""
}

func (x *CompleteBuildTaskReq) GetLogObjectKey() string {
	if x != nil {
		return x.LogObjectKey
	}
	return ""
}

func (x *CompleteBuildTaskReq) GetLogSha256() string {
	if x != nil {
		return x.LogSha256
	}
	return ""
}

func (x *CompleteBuildTaskReq) GetLogSize() int64 {
	if x != nil {
		return x.LogSize
	}
	return 0
}

func (x *CompleteBuildTaskReq) GetBuilderAttempt() int32 {
	if x != nil {
		return x.BuilderAttempt
	}
	return 0
}

type FailBuildTaskReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BuilderId      string                 `protobuf:"bytes,2,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LogUrl         string                 `protobuf:"bytes,4,opt,name=log_url,json=logUrl,proto3" json:"log_url,omitempty"`
	LogObjectKey   string                 `protobuf:"bytes,5,opt,name=log_object_key,json=logObjectKey,proto3" json:"log_object_key,omitempty"`      // 构建日志私有对象Key
	LogSha256      string                 `protobuf:"bytes,6,opt,name=log_sha256,json=logSha256,proto3" json:"log_sha256,omitempty"`                 // 构建日志SHA-256
	LogSize        int64                  `protobuf:"varint,7,opt,name=log_size,json=logSize,proto3" json:"log_size,omitempty"`                      // 构建日志大小，单位字节
	BuilderAttempt int32                  `protobuf:"varint,8,opt,name=builder_attempt,json=builderAttempt,proto3" json:"builder_attempt,omitempty"` // 本次领取代次，用于阻止过期Worker回写
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FailBuildTaskReq) Reset() {
	*x = FailBuildTaskReq{}
	mi := &file_proto_builder_builder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailBuildTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailBuildTaskReq) ProtoMessage() {}

func (x *FailBuildTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailBuildTaskReq.ProtoReflect.Descriptor instead.
func (*FailBuildTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{7}
}

func (x *FailBuildTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *FailBuildTaskReq) GetBuilderId() string {
	if x != nil {
		return x.BuilderId
	}
	return ""
}

func (x *FailBuildTaskReq) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FailBuildTaskReq) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *FailBuildTaskReq) GetLogObjectKey() string {
	if x != nil {
		return x.LogObjectKey
	}
	return ""
}

func (x *FailBuildTaskReq) GetLogSha256() string {
	if x != nil {
		return x.LogSha256
	}
	return ""
}

func (x *FailBuildTaskReq) GetLogSize() int64 {
	if x != nil {
		return x.LogSize
	}
	return 0
}

func (x *FailBuildTaskReq) GetBuilderAttempt() int32 {
	if x != nil {
		return x.BuilderAttempt
	}
	return 0
}

// 校验签名文件、别名和密码请求，仅允许内部API调用。
type ValidateSigningMaterialReq struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	KeystoreObjectKey          string                 `protobuf:"bytes,1,opt,name=keystore_object_key,json=keystoreObjectKey,proto3" json:"keystore_object_key,omitempty"`                            // 签名文件私有对象Key
	KeyAlias                   string                 `protobuf:"bytes,2,opt,name=key_alias,json=keyAlias,proto3" json:"key_alias,omitempty"`                                                         // 待校验的签名别名
	KeystorePasswordCiphertext string                 `protobuf:"bytes,3,opt,name=keystore_password_ciphertext,json=keystorePasswordCiphertext,proto3" json:"keystore_password_ciphertext,omitempty"` // Keystore密码密文
	KeyPasswordCiphertext      string                 `protobuf:"bytes,4,opt,name=key_password_ciphertext,json=keyPasswordCiphertext,proto3" json:"key_password_ciphertext,omitempty"`                // Key密码密文
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ValidateSigningMaterialReq) Reset() {
	*x = ValidateSigningMaterialReq{}
	mi := &file_proto_builder_builder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSigningMaterialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSigningMaterialReq) ProtoMessage() {}

func (x *ValidateSigningMaterialReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_builder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSigningMaterialReq.ProtoReflect.Descriptor instead.
func (*ValidateSigningMaterialReq) Descriptor() ([]byte, []int) {
	return file_proto_builder_builder_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateSigningMaterialReq) GetKeystoreObjectKey() string {
	if x != nil {
		return x.KeystoreObjectKey
	}
	return ""
}

func (x *ValidateSigningMaterialReq) GetKeyAlias() string {
	if x != nil {
		return x.KeyAlias
	}
	return ""
}

func (x *ValidateSigningMaterialReq) GetKeystorePasswordCiphertext() string {
	if x != nil {
		return x.KeystorePasswordCiphertext
	}
	return ""
}

func (x *ValidateSigningMaterialReq) GetKeyPasswordCiphertext() string {
	if x != nil {
		return x.KeyPasswordCiphertext
	}
	return ""
}

var File_proto_builder_builder_proto protoreflect.FileDescriptor

const file_proto_builder_builder_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/builder/builder.proto\x12\abuilder\x1a\x19proto/common/common.proto\"0\n" +
	"\bRespBase\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.common.RespBaseR\x04base\"\x9c\x04\n" +
	"\tBuildTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\x03R\x05appId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\x03R\tversionId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\x03R\tchannelId\x12*\n" +
	"\x11signing_config_id\x18\x06 \x01(\x03R\x0fsigningConfigId\x12!\n" +
	"\fchannel_code\x18\a \x01(\tR\vchannelCode\x12!\n" +
	"\fversion_code\x18\b \x01(\x03R\vversionCode\x12!\n" +
	"\fversion_name\x18\t \x01(\tR\vversionName\x120\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x18.builder.BuildTaskStatusR\x06status\x12'\n" +
	"\x0fbuilder_attempt\x18\v \x01(\x05R\x0ebuilderAttempt\x12\x1a\n" +
	"\bpriority\x18\f \x01(\x05R\bpriority\x12$\n" +
	"\x0esource_apk_url\x18\r \x01(\tR\fsourceApkUrl\x12*\n" +
	"\x11build_config_json\x18\x0e \x01(\tR\x0fbuildConfigJson\x12/\n" +
	"\x14source_apk_object_id\x18\x0f \x01(\x03R\x11sourceApkObjectId\"W\n" +
	"\x11ClaimBuildTaskReq\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x01 \x01(\tR\tbuilderId\x12#\n" +
	"\rlease_seconds\x18\x02 \x01(\x05R\fleaseSeconds\"]\n" +
	"\rBuildTaskResp\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.common.RespBaseR\x04base\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.builder.BuildTaskR\x04data\"\x9d\x01\n" +
	"\x15HeartbeatBuildTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x02 \x01(\tR\tbuilderId\x12#\n" +
	"\rlease_seconds\x18\x03 \x01(\x05R\fleaseSeconds\x12'\n" +
	"\x0fbuilder_attempt\x18\x04 \x01(\x05R\x0ebuilderAttempt\"\xe1\x01\n" +
	"\x16ReportBuildProgressReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x02 \x01(\tR\tbuilderId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.builder.BuildTaskStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\x12'\n" +
	"\x0fbuilder_attempt\x18\x06 \x01(\x05R\x0ebuilderAttempt\"\xe9\x02\n" +
	"\x14CompleteBuildTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x02 \x01(\tR\tbuilderId\x12\x17\n" +
	"\aapk_url\x18\x03 \x01(\tR\x06apkUrl\x12\x1d\n" +
	"\n" +
	"apk_sha256\x18\x04 \x01(\tR\tapkSha256\x12\x19\n" +
	"\bapk_size\x18\x05 \x01(\x03R\aapkSize\x12\x17\n" +
	"\alog_url\x18\x06 \x01(\tR\x06logUrl\x12$\n" +
	"\x0eapk_object_key\x18\a \x01(\tR\fapkObjectKey\x12$\n" +
	"\x0elog_object_key\x18\b \x01(\tR\flogObjectKey\x12\x1d\n" +
	"\n" +
	"log_sha256\x18\t \x01(\tR\tlogSha256\x12\x19\n" +
	"\blog_size\x18\n" +
	" \x01(\x03R\alogSize\x12'\n" +
	"\x0fbuilder_attempt\x18\v \x01(\x05R\x0ebuilderAttempt\"\x91\x02\n" +
	"\x10FailBuildTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x02 \x01(\tR\tbuilderId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\alog_url\x18\x04 \x01(\tR\x06logUrl\x12$\n" +
	"\x0elog_object_key\x18\x05 \x01(\tR\flogObjectKey\x12\x1d\n" +
	"\n" +
	"log_sha256\x18\x06 \x01(\tR\tlogSha256\x12\x19\n" +
	"\blog_size\x18\a \x01(\x03R\alogSize\x12'\n" +
	"\x0fbuilder_attempt\x18\b \x01(\x05R\x0ebuilderAttempt\"\xe3\x01\n" +
	"\x1aValidateSigningMaterialReq\x12.\n" +
	"\x13keystore_object_key\x18\x01 \x01(\tR\x11keystoreObjectKey\x12\x1b\n" +
	"\tkey_alias\x18\x02 \x01(\tR\bkeyAlias\x12@\n" +
	"\x1ckeystore_password_ciphertext\x18\x03 \x01(\tR\x1akeystorePasswordCiphertext\x126\n" +
	"\x17key_password_ciphertext\x18\x04 \x01(\tR\x15keyPasswordCiphertext*\xec\x01\n" +
	"\x0fBuildTaskStatus\x12\x1d\n" +
	"\x19BUILD_TASK_STATUS_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19BUILD_TASK_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aBUILD_TASK_STATUS_BUILDING\x10\x02\x12\x1d\n" +
	"\x19BUILD_TASK_STATUS_SIGNING\x10\x03\x12\x1f\n" +
	"\x1bBUILD_TASK_STATUS_UPLOADING\x10\x04\x12\x1d\n" +
	"\x19BUILD_TASK_STATUS_SUCCESS\x10\x05\x12\x1c\n" +
	"\x18BUILD_TASK_STATUS_FAILED\x10\x062\xbc\x03\n" +
	"\aBuilder\x12Q\n" +
	"\x17ValidateSigningMaterial\x12#.builder.ValidateSigningMaterialReq\x1a\x11.builder.RespBase\x12D\n" +
	"\x0eClaimBuildTask\x12\x1a.builder.ClaimBuildTaskReq\x1a\x16.builder.BuildTaskResp\x12G\n" +
	"\x12HeartbeatBuildTask\x12\x1e.builder.HeartbeatBuildTaskReq\x1a\x11.builder.RespBase\x12I\n" +
	"\x13ReportBuildProgress\x12\x1f.builder.ReportBuildProgressReq\x1a\x11.builder.RespBase\x12E\n" +
	"\x11CompleteBuildTask\x12\x1d.builder.CompleteBuildTaskReq\x1a\x11.builder.RespBase\x12=\n" +
	"\rFailBuildTask\x12\x19.builder.FailBuildTaskReq\x1a\x11.builder.RespBaseB Z\x1eappforge/proto/builder;builderb\x06proto3"

var (
	file_proto_builder_builder_proto_rawDescOnce sync.Once
	file_proto_builder_builder_proto_rawDescData []byte
)

func file_proto_builder_builder_proto_rawDescGZIP() []byte {
	file_proto_builder_builder_proto_rawDescOnce.Do(func() {
		file_proto_builder_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_builder_builder_proto_rawDesc), len(file_proto_builder_builder_proto_rawDesc)))
	})
	return file_proto_builder_builder_proto_rawDescData
}

var file_proto_builder_builder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_builder_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_builder_builder_proto_goTypes = []any{
	(BuildTaskStatus)(0),               // 0: builder.BuildTaskStatus
	(*RespBase)(nil),                   // 1: builder.RespBase
	(*BuildTask)(nil),                  // 2: builder.BuildTask
	(*ClaimBuildTaskReq)(nil),          // 3: builder.ClaimBuildTaskReq
	(*BuildTaskResp)(nil),              // 4: builder.BuildTaskResp
	(*HeartbeatBuildTaskReq)(nil),      // 5: builder.HeartbeatBuildTaskReq
	(*ReportBuildProgressReq)(nil),     // 6: builder.ReportBuildProgressReq
	(*CompleteBuildTaskReq)(nil),       // 7: builder.CompleteBuildTaskReq
	(*FailBuildTaskReq)(nil),           // 8: builder.FailBuildTaskReq
	(*ValidateSigningMaterialReq)(nil), // 9: builder.ValidateSigningMaterialReq
	(*common.RespBase)(nil),            // 10: common.RespBase
}
var file_proto_builder_builder_proto_depIdxs = []int32{
	10, // 0: builder.RespBase.base:type_name -> common.RespBase
	0,  // 1: builder.BuildTask.status:type_name -> builder.BuildTaskStatus
	10, // 2: builder.BuildTaskResp.base:type_name -> common.RespBase
	2,  // 3: builder.BuildTaskResp.data:type_name -> builder.BuildTask
	0,  // 4: builder.ReportBuildProgressReq.status:type_name -> builder.BuildTaskStatus
	9,  // 5: builder.Builder.ValidateSigningMaterial:input_type -> builder.ValidateSigningMaterialReq
	3,  // 6: builder.Builder.ClaimBuildTask:input_type -> builder.ClaimBuildTaskReq
	5,  // 7: builder.Builder.HeartbeatBuildTask:input_type -> builder.HeartbeatBuildTaskReq
	6,  // 8: builder.Builder.ReportBuildProgress:input_type -> builder.ReportBuildProgressReq
	7,  // 9: builder.Builder.CompleteBuildTask:input_type -> builder.CompleteBuildTaskReq
	8,  // 10: builder.Builder.FailBuildTask:input_type -> builder.FailBuildTaskReq
	1,  // 11: builder.Builder.ValidateSigningMaterial:output_type -> builder.RespBase
	4,  // 12: builder.Builder.ClaimBuildTask:output_type -> builder.BuildTaskResp
	1,  // 13: builder.Builder.HeartbeatBuildTask:output_type -> builder.RespBase
	1,  // 14: builder.Builder.ReportBuildProgress:output_type -> builder.RespBase
	1,  // 15: builder.Builder.CompleteBuildTask:output_type -> builder.RespBase
	1,  // 16: builder.Builder.FailBuildTask:output_type -> builder.RespBase
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_builder_builder_proto_init() }
func file_proto_builder_builder_proto_init() {
	if File_proto_builder_builder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_builder_builder_proto_rawDesc), len(file_proto_builder_builder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_builder_builder_proto_goTypes,
		DependencyIndexes: file_proto_builder_builder_proto_depIdxs,
		EnumInfos:         file_proto_builder_builder_proto_enumTypes,
		MessageInfos:      file_proto_builder_builder_proto_msgTypes,
	}.Build()
	File_proto_builder_builder_proto = out.File
	file_proto_builder_builder_proto_goTypes = nil
	file_proto_builder_builder_proto_depIdxs = nil
}
