// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/builder/builder.proto

package builder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Builder_ClaimBuildTask_FullMethodName      = "/builder.Builder/ClaimBuildTask"
	Builder_HeartbeatBuildTask_FullMethodName  = "/builder.Builder/HeartbeatBuildTask"
	Builder_ReportBuildProgress_FullMethodName = "/builder.Builder/ReportBuildProgress"
	Builder_CompleteBuildTask_FullMethodName   = "/builder.Builder/CompleteBuildTask"
	Builder_FailBuildTask_FullMethodName       = "/builder.Builder/FailBuildTask"
)

// BuilderClient is the client API for Builder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuilderClient interface {
	ClaimBuildTask(ctx context.Context, in *ClaimBuildTaskReq, opts ...grpc.CallOption) (*BuildTaskResp, error)
	HeartbeatBuildTask(ctx context.Context, in *HeartbeatBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error)
	ReportBuildProgress(ctx context.Context, in *ReportBuildProgressReq, opts ...grpc.CallOption) (*RespBase, error)
	CompleteBuildTask(ctx context.Context, in *CompleteBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error)
	FailBuildTask(ctx context.Context, in *FailBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error)
}

type builderClient struct {
	cc grpc.ClientConnInterface
}

func NewBuilderClient(cc grpc.ClientConnInterface) BuilderClient {
	return &builderClient{cc}
}

func (c *builderClient) ClaimBuildTask(ctx context.Context, in *ClaimBuildTaskReq, opts ...grpc.CallOption) (*BuildTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildTaskResp)
	err := c.cc.Invoke(ctx, Builder_ClaimBuildTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderClient) HeartbeatBuildTask(ctx context.Context, in *HeartbeatBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespBase)
	err := c.cc.Invoke(ctx, Builder_HeartbeatBuildTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderClient) ReportBuildProgress(ctx context.Context, in *ReportBuildProgressReq, opts ...grpc.CallOption) (*RespBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespBase)
	err := c.cc.Invoke(ctx, Builder_ReportBuildProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderClient) CompleteBuildTask(ctx context.Context, in *CompleteBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespBase)
	err := c.cc.Invoke(ctx, Builder_CompleteBuildTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderClient) FailBuildTask(ctx context.Context, in *FailBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespBase)
	err := c.cc.Invoke(ctx, Builder_FailBuildTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuilderServer is the server API for Builder service.
// All implementations must embed UnimplementedBuilderServer
// for forward compatibility.
type BuilderServer interface {
	ClaimBuildTask(context.Context, *ClaimBuildTaskReq) (*BuildTaskResp, error)
	HeartbeatBuildTask(context.Context, *HeartbeatBuildTaskReq) (*RespBase, error)
	ReportBuildProgress(context.Context, *ReportBuildProgressReq) (*RespBase, error)
	CompleteBuildTask(context.Context, *CompleteBuildTaskReq) (*RespBase, error)
	FailBuildTask(context.Context, *FailBuildTaskReq) (*RespBase, error)
	mustEmbedUnimplementedBuilderServer()
}

// UnimplementedBuilderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuilderServer struct{}

func (UnimplementedBuilderServer) ClaimBuildTask(context.Context, *ClaimBuildTaskReq) (*BuildTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimBuildTask not implemented")
}
func (UnimplementedBuilderServer) HeartbeatBuildTask(context.Context, *HeartbeatBuildTaskReq) (*RespBase, error) {
	return nil, status.Error(codes.Unimplemented, "method HeartbeatBuildTask not implemented")
}
func (UnimplementedBuilderServer) ReportBuildProgress(context.Context, *ReportBuildProgressReq) (*RespBase, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportBuildProgress not implemented")
}
func (UnimplementedBuilderServer) CompleteBuildTask(context.Context, *CompleteBuildTaskReq) (*RespBase, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteBuildTask not implemented")
}
func (UnimplementedBuilderServer) FailBuildTask(context.Context, *FailBuildTaskReq) (*RespBase, error) {
	return nil, status.Error(codes.Unimplemented, "method FailBuildTask not implemented")
}
func (UnimplementedBuilderServer) mustEmbedUnimplementedBuilderServer() {}
func (UnimplementedBuilderServer) testEmbeddedByValue()                 {}

// UnsafeBuilderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuilderServer will
// result in compilation errors.
type UnsafeBuilderServer interface {
	mustEmbedUnimplementedBuilderServer()
}

func RegisterBuilderServer(s grpc.ServiceRegistrar, srv BuilderServer) {
	// If the following call panics, it indicates UnimplementedBuilderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Builder_ServiceDesc, srv)
}

func _Builder_ClaimBuildTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimBuildTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServer).ClaimBuildTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Builder_ClaimBuildTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServer).ClaimBuildTask(ctx, req.(*ClaimBuildTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builder_HeartbeatBuildTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatBuildTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServer).HeartbeatBuildTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Builder_HeartbeatBuildTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServer).HeartbeatBuildTask(ctx, req.(*HeartbeatBuildTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builder_ReportBuildProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportBuildProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServer).ReportBuildProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Builder_ReportBuildProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServer).ReportBuildProgress(ctx, req.(*ReportBuildProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builder_CompleteBuildTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBuildTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServer).CompleteBuildTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Builder_CompleteBuildTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServer).CompleteBuildTask(ctx, req.(*CompleteBuildTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builder_FailBuildTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailBuildTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServer).FailBuildTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Builder_FailBuildTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServer).FailBuildTask(ctx, req.(*FailBuildTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Builder_ServiceDesc is the grpc.ServiceDesc for Builder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Builder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "builder.Builder",
	HandlerType: (*BuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimBuildTask",
			Handler:    _Builder_ClaimBuildTask_Handler,
		},
		{
			MethodName: "HeartbeatBuildTask",
			Handler:    _Builder_HeartbeatBuildTask_Handler,
		},
		{
			MethodName: "ReportBuildProgress",
			Handler:    _Builder_ReportBuildProgress_Handler,
		},
		{
			MethodName: "CompleteBuildTask",
			Handler:    _Builder_CompleteBuildTask_Handler,
		},
		{
			MethodName: "FailBuildTask",
			Handler:    _Builder_FailBuildTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/builder/builder.proto",
}
