// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package app

import (
	"context"

	"appforge/proto/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignUserRolesReq       = system.AssignUserRolesReq
	ChangeUserStatusReq      = system.ChangeUserStatusReq
	CreateOpLogReq           = system.CreateOpLogReq
	Empty                    = system.Empty
	Google2FABindReq         = system.Google2FABindReq
	Google2FADisableReq      = system.Google2FADisableReq
	Google2FAEnableReq       = system.Google2FAEnableReq
	Google2FAInitData        = system.Google2FAInitData
	Google2FAInitReq         = system.Google2FAInitReq
	Google2FAInitResp        = system.Google2FAInitResp
	Google2FAResetReq        = system.Google2FAResetReq
	LoginData                = system.LoginData
	LoginLogItem             = system.LoginLogItem
	LoginLogListReq          = system.LoginLogListReq
	LoginLogListResp         = system.LoginLogListResp
	LoginReq                 = system.LoginReq
	LoginResp                = system.LoginResp
	LoginUserPermsReq        = system.LoginUserPermsReq
	LoginUserPermsResp       = system.LoginUserPermsResp
	OpLogItem                = system.OpLogItem
	OpLogListReq             = system.OpLogListReq
	OpLogListResp            = system.OpLogListResp
	ProfileData              = system.ProfileData
	ProfileResp              = system.ProfileResp
	ProfileUser              = system.ProfileUser
	ResetUserPwdReq          = system.ResetUserPwdReq
	ResolveTenantDomainReq   = system.ResolveTenantDomainReq
	ResolveTenantDomainResp  = system.ResolveTenantDomainResp
	RespBase                 = system.RespBase
	SysConfigByKeysReq       = system.SysConfigByKeysReq
	SysConfigByKeysResp      = system.SysConfigByKeysResp
	SysConfigCreateReq       = system.SysConfigCreateReq
	SysConfigDeleteReq       = system.SysConfigDeleteReq
	SysConfigDetailReq       = system.SysConfigDetailReq
	SysConfigDetailResp      = system.SysConfigDetailResp
	SysConfigItem            = system.SysConfigItem
	SysConfigListReq         = system.SysConfigListReq
	SysConfigListResp        = system.SysConfigListResp
	SysConfigUpdateReq       = system.SysConfigUpdateReq
	SysMenuCreateReq         = system.SysMenuCreateReq
	SysMenuDeleteReq         = system.SysMenuDeleteReq
	SysMenuItem              = system.SysMenuItem
	SysMenuListReq           = system.SysMenuListReq
	SysMenuListResp          = system.SysMenuListResp
	SysMenuNode              = system.SysMenuNode
	SysMenuTreeReq           = system.SysMenuTreeReq
	SysMenuTreeResp          = system.SysMenuTreeResp
	SysMenuUpdateReq         = system.SysMenuUpdateReq
	SysPermItem              = system.SysPermItem
	SysPermListResp          = system.SysPermListResp
	SysRoleCreateReq         = system.SysRoleCreateReq
	SysRoleDeleteReq         = system.SysRoleDeleteReq
	SysRoleGrantDetailData   = system.SysRoleGrantDetailData
	SysRoleGrantDetailReq    = system.SysRoleGrantDetailReq
	SysRoleGrantDetailResp   = system.SysRoleGrantDetailResp
	SysRoleGrantReq          = system.SysRoleGrantReq
	SysRoleItem              = system.SysRoleItem
	SysRoleListReq           = system.SysRoleListReq
	SysRoleListResp          = system.SysRoleListResp
	SysRoleUpdateReq         = system.SysRoleUpdateReq
	SysTenantCreateReq       = system.SysTenantCreateReq
	SysTenantDeleteReq       = system.SysTenantDeleteReq
	SysTenantDetailReq       = system.SysTenantDetailReq
	SysTenantDetailResp      = system.SysTenantDetailResp
	SysTenantDomainCreateReq = system.SysTenantDomainCreateReq
	SysTenantDomainDeleteReq = system.SysTenantDomainDeleteReq
	SysTenantDomainItem      = system.SysTenantDomainItem
	SysTenantDomainListReq   = system.SysTenantDomainListReq
	SysTenantDomainListResp  = system.SysTenantDomainListResp
	SysTenantDomainUpdateReq = system.SysTenantDomainUpdateReq
	SysTenantItem            = system.SysTenantItem
	SysTenantListReq         = system.SysTenantListReq
	SysTenantListResp        = system.SysTenantListResp
	SysTenantUpdateReq       = system.SysTenantUpdateReq
	SysUserCreateReq         = system.SysUserCreateReq
	SysUserDeleteReq         = system.SysUserDeleteReq
	SysUserDetailReq         = system.SysUserDetailReq
	SysUserDetailResp        = system.SysUserDetailResp
	SysUserItem              = system.SysUserItem
	SysUserListReq           = system.SysUserListReq
	SysUserListResp          = system.SysUserListResp
	SysUserUpdateReq         = system.SysUserUpdateReq
	UpdateProfileReq         = system.UpdateProfileReq

	App interface {
		SysConfigDetail(ctx context.Context, in *SysConfigDetailReq, opts ...grpc.CallOption) (*SysConfigDetailResp, error)
		SysTenantDetail(ctx context.Context, in *SysTenantDetailReq, opts ...grpc.CallOption) (*SysTenantDetailResp, error)
	}

	defaultApp struct {
		cli zrpc.Client
	}
)

func NewApp(cli zrpc.Client) App {
	return &defaultApp{
		cli: cli,
	}
}

func (m *defaultApp) SysConfigDetail(ctx context.Context, in *SysConfigDetailReq, opts ...grpc.CallOption) (*SysConfigDetailResp, error) {
	client := system.NewAppClient(m.cli.Conn())
	return client.SysConfigDetail(ctx, in, opts...)
}

func (m *defaultApp) SysTenantDetail(ctx context.Context, in *SysTenantDetailReq, opts ...grpc.CallOption) (*SysTenantDetailResp, error) {
	client := system.NewAppClient(m.cli.Conn())
	return client.SysTenantDetail(ctx, in, opts...)
}
