// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AssignUserRolesReq struct {
	UserId  int64   `json:"userId"`
	RoleIds []int64 `json:"roleIds"`
}

type AuthorizePlatformSourceRepositoryReq struct {
	Id           int64  `path:"id"`
	RepositoryId string `path:"repositoryId"`
}

type CancelPlatformBuildTaskReq struct {
	Id     int64  `path:"id"`
	Reason string `json:"reason,optional"`
}

type CancelPlatformSubscriptionReq struct {
	TenantId    int64 `json:"tenantId,optional"`
	Immediately bool  `json:"immediately"`
}

type ChangePlatformBrandingProfileStatusReq struct {
	Id     int64 `path:"id"`
	Status int32 `json:"status"`
}

type ChangePlatformSubscriptionReq struct {
	TenantId int64 `json:"tenantId,optional"`
	PlanId   int64 `json:"planId"`
	Mode     int32 `json:"mode"`
}

type ChangePlatformWhiteLabelProductStatusReq struct {
	Id     int64 `path:"id"`
	Status int32 `json:"status"`
}

type ChangePlatformWhiteLabelTemplateStatusReq struct {
	Id     int64 `path:"id"`
	Status int32 `json:"status"`
}

type ChangeUserStatusReq struct {
	Id      int64 `json:"id"`
	Enabled int64 `json:"enabled"` // 0未知 1启用 2禁用
}

type CleanupPlatformBuildCacheReq struct {
	Limit           int32 `json:"limit,optional"`
	TargetFreeBytes int64 `json:"targetFreeBytes,optional"`
}

type CompletePlatformUploadReq struct {
	Id int64 `path:"id"`
}

type CompletePlatformUploadResp struct {
	RespBase
	Data PlatformStorageObject `json:"data"`
}

type CopyPlatformWhiteLabelTemplateReq struct {
	Id              int64  `path:"id"`
	TemplateCode    string `json:"templateCode"`
	TemplateName    string `json:"templateName"`
	SourceVersionId int64  `json:"sourceVersionId,optional"`
}

type CreatePlatformApplicationReq struct {
	AppCode     string `json:"appCode"`
	AppName     string `json:"appName"`
	PackageName string `json:"packageName"`
	Description string `json:"description,optional"`
	IconUrl     string `json:"iconUrl,optional"`
	ApiHost     string `json:"apiHost,optional"`
}

type CreatePlatformBillingCheckoutReq struct {
	PlanId int64 `json:"planId"`
}

type CreatePlatformBillingPlanReq struct {
	PlanCode            string `json:"planCode"`
	PlanName            string `json:"planName"`
	BillingCycle        int32  `json:"billingCycle"`
	PriceAmount         int64  `json:"priceAmount"`
	Currency            string `json:"currency"`
	FeatureJson         string `json:"featureJson"`
	BuildsPerCycle      int64  `json:"buildsPerCycle"`
	MaxBuildConcurrency int32  `json:"maxBuildConcurrency"`
	StorageBytes        int64  `json:"storageBytes"`
	MaxUploadBytes      int64  `json:"maxUploadBytes"`
	TeamSeats           int32  `json:"teamSeats"`
	ApiRateLimit        int32  `json:"apiRateLimit"`
	ChargeFailedBuild   bool   `json:"chargeFailedBuild"`
	ChargeCacheHit      bool   `json:"chargeCacheHit"`
	ChargeRetryBuild    bool   `json:"chargeRetryBuild"`
}

type CreatePlatformBrandingPreflightReq struct {
	Id        int64 `path:"id"`
	VersionId int64 `json:"versionId"`
}

type CreatePlatformBrandingProfileReq struct {
	AppId                int64  `json:"appId"`
	ProfileName          string `json:"profileName"`
	AppName              string `json:"appName"`
	LogoObjectId         int64  `json:"logoObjectId"`
	SplashObjectId       int64  `json:"splashObjectId"`
	ApiHost              string `json:"apiHost"`
	RewriteMode          int32  `json:"rewriteMode"`
	LauncherIconTarget   string `json:"launcherIconTarget,optional"`
	SplashResourceTarget string `json:"splashResourceTarget,optional"`
	RuntimeConfigJson    string `json:"runtimeConfigJson,optional"`
}

type CreatePlatformBuildTaskReq struct {
	AppId               int64  `json:"appId"`
	VersionId           int64  `json:"versionId"`
	ChannelId           int64  `json:"channelId"`
	SigningConfigId     int64  `json:"signingConfigId,optional"`
	Priority            int32  `json:"priority,optional"`
	BrandingProfileId   int64  `json:"brandingProfileId,optional"`
	WhiteLabelProductId int64  `json:"whiteLabelProductId,optional"`
	PoolCode            string `json:"poolCode,optional"`
}

type CreatePlatformChannelReq struct {
	AppId       int64  `json:"appId"`
	ChannelCode string `json:"channelCode,optional"`
	ChannelName string `json:"channelName"`
	LandingUrl  string `json:"landingUrl,optional"`
	DownloadUrl string `json:"downloadUrl,optional"`
}

type CreatePlatformLocalAgentRegistrationReq struct {
	TenantId           int64                          `json:"tenantId,optional"`
	AgentCode          string                         `json:"agentCode"`
	AgentName          string                         `json:"agentName"`
	PoolCode           string                         `json:"poolCode"`
	ArtifactMode       int32                          `json:"artifactMode"`
	CustomerStorageRef string                         `json:"customerStorageRef,optional"`
	AllowedAppIds      []int64                        `json:"allowedAppIds"`
	Capabilities       []PlatformLocalAgentCapability `json:"capabilities"`
	ExpiresSeconds     int64                          `json:"expiresSeconds,optional"`
}

type CreatePlatformOpenApiCredentialReq struct {
	CredentialName     string   `json:"credentialName"`
	Scopes             []int32  `json:"scopes"`
	AppIds             []int64  `json:"appIds,optional"`
	IpAllowlist        []string `json:"ipAllowlist,optional"`
	RateLimitPerMinute int32    `json:"rateLimitPerMinute"`
	ExpiresAt          int64    `json:"expiresAt,optional"`
}

type CreatePlatformSigningConfigReq struct {
	AppId            int64  `json:"appId"`
	Name             string `json:"name"`
	KeyAlias         string `json:"keyAlias"`
	KeystorePassword string `json:"keystorePassword,optional"`
	KeyPassword      string `json:"keyPassword,optional"`
	SecretRef        string `json:"secretRef,optional"`
	KeystoreObjectId int64  `json:"keystoreObjectId"`
	SigningMode      int32  `json:"signingMode,optional"`
}

type CreatePlatformSourceBuildTriggerReq struct {
	RepositoryId        int64   `json:"repositoryId"`
	AppId               int64   `json:"appId"`
	TriggerName         string  `json:"triggerName"`
	EventType           int32   `json:"eventType"`
	RefPattern          string  `json:"refPattern,optional"`
	ArtifactSelector    string  `json:"artifactSelector"`
	ChannelIds          []int64 `json:"channelIds"`
	SigningConfigId     int64   `json:"signingConfigId,optional"`
	BrandingProfileId   int64   `json:"brandingProfileId,optional"`
	WhiteLabelProductId int64   `json:"whiteLabelProductId,optional"`
	Priority            int32   `json:"priority,optional"`
	PoolCode            string  `json:"poolCode,optional"`
	VersionNamePrefix   string  `json:"versionNamePrefix,optional"`
}

type CreatePlatformSourceOAuthAuthorizationReq struct {
	Platform int32 `path:"platform"`
}

type CreatePlatformVersionReq struct {
	AppId             int64  `json:"appId"`
	VersionCode       int64  `json:"versionCode"`
	VersionName       string `json:"versionName"`
	SourceApkUrl      string `json:"sourceApkUrl,optional"`
	SourceApkSha256   string `json:"sourceApkSha256,optional"`
	ReleaseNotes      string `json:"releaseNotes,optional"`
	BuildConfigJson   string `json:"buildConfigJson,optional"`
	SourceApkObjectId int64  `json:"sourceApkObjectId"`
}

type CreatePlatformWebhookEndpointReq struct {
	EndpointName string   `json:"endpointName"`
	EndpointUrl  string   `json:"endpointUrl"`
	EventTypes   []string `json:"eventTypes"`
	MaxAttempts  int32    `json:"maxAttempts,optional"`
}

type CreatePlatformWhiteLabelProductReq struct {
	AppId               int64  `json:"appId"`
	ProductCode         string `json:"productCode"`
	ProductName         string `json:"productName"`
	TemplateId          int64  `json:"templateId"`
	TemplateRevision    int32  `json:"templateRevision"`
	BrandingProfileId   int64  `json:"brandingProfileId"`
	PackageName         string `json:"packageName"`
	SigningConfigId     int64  `json:"signingConfigId"`
	ParameterValuesJson string `json:"parameterValuesJson,optional"`
}

type CreatePlatformWhiteLabelTemplateReq struct {
	AppId                  int64  `json:"appId"`
	TemplateCode           string `json:"templateCode"`
	TemplateName           string `json:"templateName"`
	SourceVersionId        int64  `json:"sourceVersionId"`
	ParameterSchemaJson    string `json:"parameterSchemaJson,optional"`
	CompatibilityRulesJson string `json:"compatibilityRulesJson,optional"`
}

type CreatePlatformWhiteLabelTemplateRevisionReq struct {
	Id                    int64  `path:"id"`
	PackageNameRuleJson   string `json:"packageNameRuleJson"`
	ManifestPatchJson     string `json:"manifestPatchJson,optional"`
	ResourcePatchJson     string `json:"resourcePatchJson,optional"`
	ExtensionFilesJson    string `json:"extensionFilesJson,optional"`
	ExpectedArtifactsJson string `json:"expectedArtifactsJson,optional"`
}

type DrainPlatformBuilderNodeReq struct {
	Id          int64 `path:"id"`
	DrainStatus int32 `json:"drainStatus"`
}

type DrainPlatformLocalAgentReq struct {
	Id          int64 `path:"id"`
	TenantId    int64 `json:"tenantId,optional"`
	DrainStatus int32 `json:"drainStatus"`
}

type GetPlatformBuildClusterMetricsReq struct {
	PoolCode      string `form:"poolCode,optional"`
	PeriodMinutes int32  `form:"periodMinutes,optional"`
}

type GetPlatformChannelStatsReq struct {
	AppId     int64 `form:"appId"`
	ChannelId int64 `form:"channelId"`
	StartTime int64 `form:"startTime,optional"`
	EndTime   int64 `form:"endTime,optional"`
}

type GetSystemCore struct {
	SiteName      string         `json:"siteName"`
	SiteLogo      string         `json:"siteLogo"`
	AssetUrl      string         `json:"assetUrl"`
	MustGoogleF2a int64          `json:"mustGoogleF2a"`
	Options       []OptionsGroup `json:"options"`
}

type GetSystemCoreResp struct {
	RespBase
	Data GetSystemCore `json:"data"`
}

type Google2FABindReq struct {
	UserId int64  `json:"userId"`
	Secret string `json:"secret"`
	Code   string `json:"code"`
}

type Google2FADisableReq struct {
	UserId int64  `json:"userId"`
	Code   string `json:"code,optional"`
}

type Google2FAEnableReq struct {
	UserId int64  `json:"userId"`
	Code   string `json:"code"`
}

type Google2FAInit struct {
	Secret     string `json:"secret"`
	OtpauthUrl string `json:"otpauthUrl"`
	QrCode     string `json:"qrCode,optional"`
}

type Google2FAInitReq struct {
	UserId int64 `json:"userId"`
}

type Google2FAInitResp struct {
	RespBase
	Data Google2FAInit `json:"data"`
}

type Google2FAResetReq struct {
	UserId int64 `json:"userId"`
}

type ImportPlatformAirGappedResultReq struct {
	PackageCode    string `json:"packageCode"`
	ResultObjectId int64  `json:"resultObjectId"`
}

type ImportPlatformSourceArtifactReq struct {
	AppId              int64  `json:"appId"`
	RepositoryId       int64  `json:"repositoryId"`
	ArtifactSource     int32  `json:"artifactSource"`
	ExternalArtifactId string `json:"externalArtifactId"`
	ReleaseRef         string `json:"releaseRef,optional"`
	VersionCode        int64  `json:"versionCode"`
	VersionName        string `json:"versionName"`
	ReleaseNotes       string `json:"releaseNotes,optional"`
}

type InitiatePlatformUploadReq struct {
	AppId       int64  `json:"appId,optional"`
	ObjectType  int32  `json:"objectType"`
	FileName    string `json:"fileName"`
	SizeBytes   int64  `json:"sizeBytes"`
	ContentType string `json:"contentType,optional"`
}

type InitiatePlatformUploadResp struct {
	RespBase
	Data PlatformUploadTicket `json:"data"`
}

type InvalidatePlatformBuildCacheReq struct {
	Id     int64  `path:"id"`
	Reason string `json:"reason,optional"`
}

type ListPlatformApplicationsReq struct {
	PageReq
	Keyword string `form:"keyword,optional"`
	Status  int32  `form:"status,optional"`
}

type ListPlatformBillingPlansReq struct {
	Page     int32 `form:"page,optional"`
	PageSize int32 `form:"pageSize,optional"`
	Status   int32 `form:"status,optional"`
}

type ListPlatformBrandingPreflightsReq struct {
	PageReq
	AppId             int64 `form:"appId,optional"`
	BrandingProfileId int64 `form:"brandingProfileId,optional"`
	VersionId         int64 `form:"versionId,optional"`
	Status            int32 `form:"status,optional"`
}

type ListPlatformBrandingProfilesReq struct {
	PageReq
	AppId   int64  `form:"appId,optional"`
	Keyword string `form:"keyword,optional"`
	Status  int32  `form:"status,optional"`
}

type ListPlatformBuildCacheEntriesReq struct {
	PageReq
	CacheScope int32  `form:"cacheScope,optional"`
	Status     int32  `form:"status,optional"`
	Keyword    string `form:"keyword,optional"`
}

type ListPlatformBuildConcurrencyPoliciesReq struct {
	PageReq
	AppId    int64  `form:"appId,optional"`
	PoolCode string `form:"poolCode,optional"`
	Status   int32  `form:"status,optional"`
}

type ListPlatformBuildSchedulerEventsReq struct {
	PageReq
	AppId     int64  `form:"appId,optional"`
	TaskId    int64  `form:"taskId,optional"`
	NodeCode  string `form:"nodeCode,optional"`
	PoolCode  string `form:"poolCode,optional"`
	EventType int32  `form:"eventType,optional"`
}

type ListPlatformBuildTasksReq struct {
	PageReq
	AppId     int64 `form:"appId,optional"`
	ChannelId int64 `form:"channelId,optional"`
	Status    int32 `form:"status,optional"`
}

type ListPlatformBuilderNodesReq struct {
	PageReq
	PoolCode    string `form:"poolCode,optional"`
	Status      int32  `form:"status,optional"`
	DrainStatus int32  `form:"drainStatus,optional"`
	Keyword     string `form:"keyword,optional"`
}

type ListPlatformChannelsReq struct {
	PageReq
	AppId   int64  `form:"appId,optional"`
	Keyword string `form:"keyword,optional"`
	Status  int32  `form:"status,optional"`
}

type ListPlatformInvoicesReq struct {
	TenantId int64 `form:"tenantId,optional"`
	Status   int32 `form:"status,optional"`
	Page     int32 `form:"page,optional"`
	PageSize int32 `form:"pageSize,optional"`
}

type ListPlatformLocalAgentsReq struct {
	PageReq
	TenantId int64 `form:"tenantId,optional"`
	Status   int32 `form:"status,optional"`
}

type ListPlatformOpenApiCredentialsReq struct {
	PageReq
	Status  int32  `form:"status,optional"`
	Keyword string `form:"keyword,optional"`
}

type ListPlatformSigningConfigsReq struct {
	PageReq
	AppId  int64 `form:"appId,optional"`
	Status int64 `form:"status,optional"`
}

type ListPlatformSourceAvailableRepositoriesReq struct {
	Id int64 `path:"id"`
}

type ListPlatformSourceBuildTriggersReq struct {
	PageReq
	RepositoryId int64  `form:"repositoryId,optional"`
	AppId        int64  `form:"appId,optional"`
	Status       int32  `form:"status,optional"`
	Keyword      string `form:"keyword,optional"`
}

type ListPlatformSourceIntegrationsReq struct {
	PageReq
	Platform int32  `form:"platform,optional"`
	Status   int32  `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
}

type ListPlatformSourceRepositoriesReq struct {
	PageReq
	IntegrationId int64  `form:"integrationId,optional"`
	Status        int32  `form:"status,optional"`
	Keyword       string `form:"keyword,optional"`
}

type ListPlatformSourceWebhookEventsReq struct {
	PageReq
	TriggerId int64 `form:"triggerId,optional"`
	Status    int32 `form:"status,optional"`
}

type ListPlatformVersionsReq struct {
	PageReq
	AppId  int64 `form:"appId,optional"`
	Status int32 `form:"status,optional"`
}

type ListPlatformWebhookDeliveriesReq struct {
	PageReq
	EndpointId int64  `form:"endpointId,optional"`
	Status     int32  `form:"status,optional"`
	EventType  string `form:"eventType,optional"`
}

type ListPlatformWebhookEndpointsReq struct {
	PageReq
	Status  int32  `form:"status,optional"`
	Keyword string `form:"keyword,optional"`
}

type ListPlatformWhiteLabelProductsReq struct {
	PageReq
	AppId   int64  `form:"appId,optional"`
	Keyword string `form:"keyword,optional"`
	Status  int32  `form:"status,optional"`
}

type ListPlatformWhiteLabelTemplateRevisionsReq struct {
	PageReq
	Id     int64 `path:"id"`
	Status int32 `form:"status,optional"`
}

type ListPlatformWhiteLabelTemplatesReq struct {
	PageReq
	AppId   int64  `form:"appId,optional"`
	Keyword string `form:"keyword,optional"`
	Status  int32  `form:"status,optional"`
}

type LoginData struct {
	Token string `json:"token"`
	Exp   int64  `json:"exp"`
}

type LoginLogItem struct {
	Id       int64  `json:"id"`
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Ip       string `json:"ip"`
	Ua       string `json:"ua"`
	Success  int64  `json:"success"`
	Msg      string `json:"msg,optional"`
	LoginAt  int64  `json:"loginAt"`
}

type LoginLogListReq struct {
	PageReq
	Username string `form:"username,optional"`
	Success  int64  `form:"success,optional"`
}

type LoginLogListResp struct {
	RespBase
	Data []LoginLogItem `json:"data"`
}

type LoginReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	GoogleCode string `json:"googleCode,optional"`
}

type LoginResp struct {
	RespBase
	Data LoginData `json:"data"`
}

type MenuNode struct {
	Id        int64      `json:"id"`
	ParentId  int64      `json:"parentId"`
	Name      string     `json:"name"`
	MenuType  int64      `json:"menuType"` // 1目录 2菜单 3按钮
	Path      string     `json:"path,optional"`
	Component string     `json:"component,optional"`
	Icon      string     `json:"icon,optional"`
	Sort      int64      `json:"sort"`
	Visible   int64      `json:"visible"`
	Enabled   int64      `json:"enabled"`
	Perms     string     `json:"perms,optional"`
	Children  []MenuNode `json:"children,optional"`
}

type OpLogItem struct {
	Id          int64  `json:"id"`
	TenantId    int64  `json:"tenantId"`
	UserId      int64  `json:"userId"`
	Username    string `json:"username"`
	Module      string `json:"module"`
	Action      string `json:"action"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	Req         string `json:"req,optional"`
	Resp        string `json:"resp,optional"`
	Ip          string `json:"ip"`
	CostMs      int64  `json:"costMs"`
	CreateTimes int64  `json:"createTimes"`
	UpdateTimes int64  `json:"updateTimes"`
}

type OpLogListReq struct {
	PageReq
	Username string `form:"username,optional"`
	Method   string `form:"method,optional"`
	Path     string `form:"path,optional"`
}

type OpLogListResp struct {
	RespBase
	Data []OpLogItem `json:"data"`
}

type OpenListApplicationsReq struct {
	PageReq
	Keyword string `form:"keyword,optional"`
	Status  int32  `form:"status,optional"`
}

type OptionsGroup struct {
	Key     string        `json:"key"`
	Label   string        `json:"label"`
	Options []OptionsItem `json:"options"`
}

type OptionsItem struct {
	Value int32  `json:"value"`
	Code  string `json:"code"`
}

type PageReq struct {
	Cursor int64 `form:"cursor,optional"`
	Limit  int64 `form:"limit,optional"`
	Count  int64 `form:"count,optional"` // 已知总数；<=0 时服务端按需重新统计
}

type PlatformAirGappedExport struct {
	PackageData PlatformAirGappedPackage `json:"package"`
	DownloadUrl string                   `json:"downloadUrl"`
	ExpiresAt   int64                    `json:"expiresAt"`
}

type PlatformAirGappedExportResp struct {
	RespBase
	Data PlatformAirGappedExport `json:"data"`
}

type PlatformAirGappedPackage struct {
	Id                     int64  `json:"id"`
	TenantId               int64  `json:"tenantId"`
	AppId                  int64  `json:"appId"`
	PackageCode            string `json:"packageCode"`
	AgentId                int64  `json:"agentId"`
	TaskId                 int64  `json:"taskId"`
	BuilderAttempt         int32  `json:"builderAttempt"`
	AgentCertificateSerial string `json:"agentCertificateSerial"`
	Status                 int32  `json:"status"`
	ExportObjectId         int64  `json:"exportObjectId,optional"`
	ExportSha256           string `json:"exportSha256,optional"`
	ExportSizeBytes        int64  `json:"exportSizeBytes,optional"`
	ResultObjectId         int64  `json:"resultObjectId,optional"`
	ResultSha256           string `json:"resultSha256,optional"`
	ResultSizeBytes        int64  `json:"resultSizeBytes,optional"`
	IssuedAt               int64  `json:"issuedAt"`
	ExpiresAt              int64  `json:"expiresAt"`
	ImportedAt             int64  `json:"importedAt,optional"`
	CreateTime             int64  `json:"createTime"`
	UpdateTime             int64  `json:"updateTime"`
}

type PlatformAirGappedPackageReq struct {
	PackageCode string `path:"packageCode"`
}

type PlatformAirGappedPackageResp struct {
	RespBase
	Data PlatformAirGappedPackage `json:"data"`
}

type PlatformApplication struct {
	Id          int64  `json:"id"`
	TenantId    int64  `json:"tenantId"`
	AppCode     string `json:"appCode"`
	AppName     string `json:"appName"`
	PackageName string `json:"packageName"`
	Description string `json:"description,optional"`
	IconUrl     string `json:"iconUrl,optional"`
	ApiHost     string `json:"apiHost,optional"`
	Status      int32  `json:"status"`
	CreateBy    int64  `json:"createBy"`
	CreateTime  int64  `json:"createTime"`
	UpdateTime  int64  `json:"updateTime"`
}

type PlatformApplicationListResp struct {
	RespBase
	Data []PlatformApplication `json:"data"`
}

type PlatformApplicationResp struct {
	RespBase
	Data PlatformApplication `json:"data"`
}

type PlatformBillingCheckoutResp struct {
	RespBase
	CheckoutUrl string `json:"checkoutUrl"`
	SessionId   string `json:"sessionId"`
}

type PlatformBillingPlan struct {
	Id                  int64  `json:"id"`
	PlanCode            string `json:"planCode"`
	PlanName            string `json:"planName"`
	BillingCycle        int32  `json:"billingCycle"`
	PriceAmount         int64  `json:"priceAmount"`
	Currency            string `json:"currency"`
	FeatureJson         string `json:"featureJson"`
	BuildsPerCycle      int64  `json:"buildsPerCycle"`
	MaxBuildConcurrency int32  `json:"maxBuildConcurrency"`
	StorageBytes        int64  `json:"storageBytes"`
	MaxUploadBytes      int64  `json:"maxUploadBytes"`
	TeamSeats           int32  `json:"teamSeats"`
	ApiRateLimit        int32  `json:"apiRateLimit"`
	ChargeFailedBuild   bool   `json:"chargeFailedBuild"`
	ChargeCacheHit      bool   `json:"chargeCacheHit"`
	ChargeRetryBuild    bool   `json:"chargeRetryBuild"`
	Status              int32  `json:"status"`
	Version             int32  `json:"version"`
	CreateTime          int64  `json:"createTime"`
	UpdateTime          int64  `json:"updateTime"`
}

type PlatformBillingPlanIdReq struct {
	Id int64 `path:"id"`
}

type PlatformBillingPlanListResp struct {
	RespBase
	Data  []PlatformBillingPlan `json:"data"`
	Total int64                 `json:"total"`
}

type PlatformBillingPlanResp struct {
	RespBase
	Data PlatformBillingPlan `json:"data"`
}

type PlatformBillingUsageReq struct {
	TenantId  int64  `form:"tenantId,optional"`
	PeriodKey string `form:"periodKey,optional"`
}

type PlatformBillingUsageResp struct {
	RespBase
	PeriodKey string                       `json:"periodKey"`
	Data      []PlatformUsageMetricSummary `json:"data"`
}

type PlatformBrandingPreflight struct {
	Id                int64  `json:"id"`
	TenantId          int64  `json:"tenantId"`
	AppId             int64  `json:"appId"`
	BrandingProfileId int64  `json:"brandingProfileId"`
	BrandingRevision  int32  `json:"brandingRevision"`
	VersionId         int64  `json:"versionId"`
	Status            int32  `json:"status"`
	ReportJson        string `json:"reportJson,optional"`
	SourceApkSha256   string `json:"sourceApkSha256,optional"`
	ToolchainVersion  string `json:"toolchainVersion,optional"`
	StartTime         int64  `json:"startTime,optional"`
	FinishTime        int64  `json:"finishTime,optional"`
	CreateBy          int64  `json:"createBy"`
	CreateTime        int64  `json:"createTime"`
	UpdateTime        int64  `json:"updateTime"`
}

type PlatformBrandingPreflightListResp struct {
	RespBase
	Data []PlatformBrandingPreflight `json:"data"`
}

type PlatformBrandingPreflightResp struct {
	RespBase
	Data PlatformBrandingPreflight `json:"data"`
}

type PlatformBrandingProfile struct {
	Id                   int64  `json:"id"`
	TenantId             int64  `json:"tenantId"`
	AppId                int64  `json:"appId"`
	ProfileName          string `json:"profileName"`
	AppName              string `json:"appName"`
	LogoObjectId         int64  `json:"logoObjectId"`
	SplashObjectId       int64  `json:"splashObjectId"`
	ApiHost              string `json:"apiHost"`
	RewriteMode          int32  `json:"rewriteMode"`
	LauncherIconTarget   string `json:"launcherIconTarget,optional"`
	SplashResourceTarget string `json:"splashResourceTarget,optional"`
	RuntimeConfigJson    string `json:"runtimeConfigJson,optional"`
	Status               int32  `json:"status"`
	Revision             int32  `json:"revision"`
	CreateBy             int64  `json:"createBy"`
	CreateTime           int64  `json:"createTime"`
	UpdateTime           int64  `json:"updateTime"`
}

type PlatformBrandingProfileListResp struct {
	RespBase
	Data []PlatformBrandingProfile `json:"data"`
}

type PlatformBrandingProfileResp struct {
	RespBase
	Data PlatformBrandingProfile `json:"data"`
}

type PlatformBuildCacheCleanupResp struct {
	RespBase
	Data PlatformBuildCacheCleanupResult `json:"data"`
}

type PlatformBuildCacheCleanupResult struct {
	InvalidatedCount int64   `json:"invalidatedCount"`
	ReclaimableBytes int64   `json:"reclaimableBytes"`
	ObjectIds        []int64 `json:"objectIds"`
}

type PlatformBuildCacheEntry struct {
	Id                   int64  `json:"id"`
	TenantId             int64  `json:"tenantId"`
	CacheScope           int32  `json:"cacheScope"`
	CacheKey             string `json:"cacheKey"`
	ToolchainVersion     string `json:"toolchainVersion"`
	BuildProtocolVersion int32  `json:"buildProtocolVersion"`
	InputDigest          string `json:"inputDigest"`
	ArtifactObjectId     int64  `json:"artifactObjectId"`
	ArtifactSha256       string `json:"artifactSha256"`
	SizeBytes            int64  `json:"sizeBytes"`
	HitCount             int64  `json:"hitCount"`
	Status               int32  `json:"status"`
	ExpiresAt            int64  `json:"expiresAt"`
	LastHitAt            int64  `json:"lastHitAt,optional"`
	CreateTime           int64  `json:"createTime"`
	UpdateTime           int64  `json:"updateTime"`
}

type PlatformBuildCacheEntryListResp struct {
	RespBase
	Data []PlatformBuildCacheEntry `json:"data"`
}

type PlatformBuildCacheEntryResp struct {
	RespBase
	Data PlatformBuildCacheEntry `json:"data"`
}

type PlatformBuildClusterMetrics struct {
	PoolCode                    string   `json:"poolCode"`
	PeriodMinutes               int32    `json:"periodMinutes"`
	OnlineNodes                 int64    `json:"onlineNodes"`
	OfflineNodes                int64    `json:"offlineNodes"`
	DrainingNodes               int64    `json:"drainingNodes"`
	TotalSlots                  int64    `json:"totalSlots"`
	RunningSlots                int64    `json:"runningSlots"`
	DiskCapacity                int64    `json:"diskCapacity"`
	DiskFree                    int64    `json:"diskFree"`
	QueuedTasks                 int64    `json:"queuedTasks"`
	RunningTasks                int64    `json:"runningTasks"`
	CompletedTasks              int64    `json:"completedTasks"`
	SuccessTasks                int64    `json:"successTasks"`
	FailedTasks                 int64    `json:"failedTasks"`
	CancelledTasks              int64    `json:"cancelledTasks"`
	AverageQueueMs              int64    `json:"averageQueueMs"`
	AverageBuildMs              int64    `json:"averageBuildMs"`
	SuccessRate                 float64  `json:"successRate"`
	CacheHitTasks               int64    `json:"cacheHitTasks"`
	CacheHitRate                float64  `json:"cacheHitRate"`
	ActiveCacheEntries          int64    `json:"activeCacheEntries"`
	ActiveCacheBytes            int64    `json:"activeCacheBytes"`
	LeaseRecoveryCount          int64    `json:"leaseRecoveryCount"`
	CacheValidationFailureCount int64    `json:"cacheValidationFailureCount"`
	OldestQueuedMs              int64    `json:"oldestQueuedMs"`
	Alerts                      []string `json:"alerts"`
}

type PlatformBuildClusterMetricsResp struct {
	RespBase
	Data PlatformBuildClusterMetrics `json:"data"`
}

type PlatformBuildConcurrencyPolicy struct {
	Id             int64  `json:"id"`
	TenantId       int64  `json:"tenantId"`
	AppId          int64  `json:"appId"`
	PoolCode       string `json:"poolCode"`
	MaxConcurrency int32  `json:"maxConcurrency"`
	FairWeight     int32  `json:"fairWeight"`
	MaxPriority    int32  `json:"maxPriority"`
	Status         int32  `json:"status"`
	CreateBy       int64  `json:"createBy"`
	CreateTime     int64  `json:"createTime"`
	UpdateTime     int64  `json:"updateTime"`
}

type PlatformBuildConcurrencyPolicyListResp struct {
	RespBase
	Data []PlatformBuildConcurrencyPolicy `json:"data"`
}

type PlatformBuildConcurrencyPolicyResp struct {
	RespBase
	Data PlatformBuildConcurrencyPolicy `json:"data"`
}

type PlatformBuildSchedulerEvent struct {
	Id           int64  `json:"id"`
	TenantId     int64  `json:"tenantId"`
	AppId        int64  `json:"appId"`
	TaskId       int64  `json:"taskId"`
	NodeCode     string `json:"nodeCode,optional"`
	PoolCode     string `json:"poolCode"`
	EventType    int32  `json:"eventType"`
	ReasonCode   string `json:"reasonCode,optional"`
	DecisionJson string `json:"decisionJson,optional"`
	CreateTime   int64  `json:"createTime"`
}

type PlatformBuildSchedulerEventListResp struct {
	RespBase
	Data []PlatformBuildSchedulerEvent `json:"data"`
}

type PlatformBuildTask struct {
	Id                   int64  `json:"id"`
	TenantId             int64  `json:"tenantId"`
	AppId                int64  `json:"appId"`
	VersionId            int64  `json:"versionId"`
	ChannelId            int64  `json:"channelId"`
	SigningConfigId      int64  `json:"signingConfigId"`
	ChannelCode          string `json:"channelCode"`
	VersionCode          int64  `json:"versionCode"`
	VersionName          string `json:"versionName"`
	Status               int32  `json:"status"`
	BuilderId            string `json:"builderId,optional"`
	BuilderAttempt       int32  `json:"builderAttempt"`
	Priority             int32  `json:"priority"`
	ApkUrl               string `json:"apkUrl,optional"`
	ApkSha256            string `json:"apkSha256,optional"`
	ApkSize              int64  `json:"apkSize"`
	LogUrl               string `json:"logUrl,optional"`
	SourceApkObjectId    int64  `json:"sourceApkObjectId"`
	ApkObjectId          int64  `json:"apkObjectId"`
	LogObjectId          int64  `json:"logObjectId"`
	ErrorMessage         string `json:"errorMessage,optional"`
	QueuedAt             int64  `json:"queuedAt"`
	StartTime            int64  `json:"startTime,optional"`
	FinishTime           int64  `json:"finishTime,optional"`
	CreateBy             int64  `json:"createBy"`
	CreateTime           int64  `json:"createTime"`
	UpdateTime           int64  `json:"updateTime"`
	BrandingProfileId    int64  `json:"brandingProfileId"`
	BrandingRevision     int32  `json:"brandingRevision"`
	BrandingSnapshotJson string `json:"brandingSnapshotJson,optional"`
	WhiteLabelProductId  int64  `json:"whiteLabelProductId"`
	TemplateRevision     int32  `json:"templateRevision"`
	TemplateSnapshotJson string `json:"templateSnapshotJson,optional"`
	PoolCode             string `json:"poolCode"`
	CacheKey             string `json:"cacheKey,optional"`
	CacheEntryId         int64  `json:"cacheEntryId"`
	CacheHit             bool   `json:"cacheHit"`
	CancelRequestedAt    int64  `json:"cancelRequestedAt,optional"`
	CancelledAt          int64  `json:"cancelledAt,optional"`
	CancelReason         string `json:"cancelReason,optional"`
	RetryOfTaskId        int64  `json:"retryOfTaskId"`
}

type PlatformBuildTaskListResp struct {
	RespBase
	Data []PlatformBuildTask `json:"data"`
}

type PlatformBuildTaskResp struct {
	RespBase
	Data PlatformBuildTask `json:"data"`
}

type PlatformBuilderNode struct {
	Id                   int64  `json:"id"`
	NodeCode             string `json:"nodeCode"`
	PoolCode             string `json:"poolCode"`
	Endpoint             string `json:"endpoint,optional"`
	Status               int32  `json:"status"`
	DrainStatus          int32  `json:"drainStatus"`
	MaxConcurrency       int32  `json:"maxConcurrency"`
	RunningCount         int32  `json:"runningCount"`
	CpuCapacity          int32  `json:"cpuCapacity"`
	MemoryCapacity       int64  `json:"memoryCapacity"`
	DiskCapacity         int64  `json:"diskCapacity"`
	DiskFree             int64  `json:"diskFree"`
	ToolchainVersion     string `json:"toolchainVersion"`
	BuildProtocolVersion int32  `json:"buildProtocolVersion"`
	CapabilityJson       string `json:"capabilityJson"`
	LastErrorMessage     string `json:"lastErrorMessage,optional"`
	LastHeartbeatAt      int64  `json:"lastHeartbeatAt"`
	CreateTime           int64  `json:"createTime"`
	UpdateTime           int64  `json:"updateTime"`
}

type PlatformBuilderNodeListResp struct {
	RespBase
	Data []PlatformBuilderNode `json:"data"`
}

type PlatformBuilderNodeResp struct {
	RespBase
	Data PlatformBuilderNode `json:"data"`
}

type PlatformChannel struct {
	Id          int64  `json:"id"`
	TenantId    int64  `json:"tenantId"`
	AppId       int64  `json:"appId"`
	ChannelCode string `json:"channelCode"`
	ChannelName string `json:"channelName"`
	LandingUrl  string `json:"landingUrl,optional"`
	DownloadUrl string `json:"downloadUrl,optional"`
	Status      int32  `json:"status"`
	CreateBy    int64  `json:"createBy"`
	CreateTime  int64  `json:"createTime"`
	UpdateTime  int64  `json:"updateTime"`
}

type PlatformChannelDownloadReq struct {
	ChannelCode string `path:"channelCode"`
}

type PlatformChannelEventReq struct {
	AppId       int64  `json:"appId"`
	ChannelCode string `json:"channelCode"`
	EventType   int32  `json:"eventType"`
	EventKey    string `json:"eventKey"`
	InstallId   string `json:"installId,optional"`
	UserId      int64  `json:"userId,optional"`
	AppVersion  string `json:"appVersion,optional"`
	Ip          string `json:"ip,optional"`
	DeviceModel string `json:"deviceModel,optional"`
	EventTime   int64  `json:"eventTime,optional"`
	Metadata    string `json:"metadata,optional"`
}

type PlatformChannelListResp struct {
	RespBase
	Data []PlatformChannel `json:"data"`
}

type PlatformChannelResp struct {
	RespBase
	Data PlatformChannel `json:"data"`
}

type PlatformChannelStats struct {
	ChannelId     int64  `json:"channelId"`
	ChannelCode   string `json:"channelCode"`
	Clicks        int64  `json:"clicks"`
	Downloads     int64  `json:"downloads"`
	Installs      int64  `json:"installs"`
	Registrations int64  `json:"registrations"`
	FirstPays     int64  `json:"firstPays"`
	Pays          int64  `json:"pays"`
}

type PlatformChannelStatsResp struct {
	RespBase
	Data PlatformChannelStats `json:"data"`
}

type PlatformDeploymentComponent struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	Message   string `json:"message,optional"`
	CheckedAt int64  `json:"checkedAt"`
}

type PlatformDeploymentLicense struct {
	Enabled         bool     `json:"enabled"`
	Status          string   `json:"status"`
	LicenseId       string   `json:"licenseId,optional"`
	Customer        string   `json:"customer,optional"`
	DeploymentId    string   `json:"deploymentId,optional"`
	DeploymentModes []string `json:"deploymentModes,optional"`
	Features        []string `json:"features,optional"`
	NotBefore       int64    `json:"notBefore,optional"`
	NotAfter        int64    `json:"notAfter,optional"`
	Sequence        uint64   `json:"sequence,optional"`
	MaxTenants      int64    `json:"maxTenants,optional"`
	MaxBuilders     int64    `json:"maxBuilders,optional"`
	Fingerprint     string   `json:"fingerprint,optional"`
}

type PlatformDeploymentMigration struct {
	Version     string `json:"version"`
	Description string `json:"description"`
}

type PlatformDeploymentStatus struct {
	DeploymentId         string                        `json:"deploymentId"`
	DeploymentMode       string                        `json:"deploymentMode"`
	ProductVersion       string                        `json:"productVersion"`
	TargetSchemaVersion  string                        `json:"targetSchemaVersion"`
	ActualSchemaVersion  string                        `json:"actualSchemaVersion"`
	SchemaCompatible     bool                          `json:"schemaCompatible"`
	MaxVersionSkew       int32                         `json:"maxVersionSkew"`
	AgentProtocolCurrent int32                         `json:"agentProtocolCurrent"`
	AgentProtocolMinimum int32                         `json:"agentProtocolMinimum"`
	UpgradeReady         bool                          `json:"upgradeReady"`
	DiagnosticsCommand   string                        `json:"diagnosticsCommand"`
	MigrationCount       int64                         `json:"migrationCount"`
	RecentMigrations     []PlatformDeploymentMigration `json:"recentMigrations"`
	Components           []PlatformDeploymentComponent `json:"components"`
	License              PlatformDeploymentLicense     `json:"license"`
	CheckedAt            int64                         `json:"checkedAt"`
}

type PlatformDeploymentStatusResp struct {
	RespBase
	Data PlatformDeploymentStatus `json:"data"`
}

type PlatformIdReq struct {
	Id int64 `path:"id"`
}

type PlatformInstallReportReq struct {
	AppId         int64  `json:"appId"`
	ChannelCode   string `json:"channelCode"`
	InstallId     string `json:"installId"`
	AppVersion    string `json:"appVersion,optional"`
	DeviceModel   string `json:"deviceModel,optional"`
	Ip            string `json:"ip,optional"`
	FirstOpenTime int64  `json:"firstOpenTime,optional"`
}

type PlatformInvoice struct {
	Id                int64                 `json:"id"`
	TenantId          int64                 `json:"tenantId"`
	InvoiceNo         string                `json:"invoiceNo"`
	ExternalInvoiceId string                `json:"externalInvoiceId,optional"`
	Status            int32                 `json:"status"`
	Currency          string                `json:"currency"`
	SubtotalAmount    int64                 `json:"subtotalAmount"`
	DiscountAmount    int64                 `json:"discountAmount"`
	TaxAmount         int64                 `json:"taxAmount"`
	TotalAmount       int64                 `json:"totalAmount"`
	PaidAmount        int64                 `json:"paidAmount"`
	RefundedAmount    int64                 `json:"refundedAmount"`
	PeriodStart       int64                 `json:"periodStart"`
	PeriodEnd         int64                 `json:"periodEnd"`
	DueAt             int64                 `json:"dueAt,optional"`
	PaidAt            int64                 `json:"paidAt,optional"`
	Items             []PlatformInvoiceItem `json:"items"`
	CreateTime        int64                 `json:"createTime"`
}

type PlatformInvoiceItem struct {
	Id          int64  `json:"id"`
	InvoiceId   int64  `json:"invoiceId"`
	LineKey     string `json:"lineKey"`
	ItemType    int32  `json:"itemType"`
	Description string `json:"description"`
	Metric      int32  `json:"metric"`
	Quantity    int64  `json:"quantity"`
	UnitAmount  int64  `json:"unitAmount"`
	Amount      int64  `json:"amount"`
}

type PlatformInvoiceListResp struct {
	RespBase
	Data  []PlatformInvoice `json:"data"`
	Total int64             `json:"total"`
}

type PlatformLocalAgent struct {
	Id                  int64                          `json:"id"`
	TenantId            int64                          `json:"tenantId"`
	AgentCode           string                         `json:"agentCode"`
	AgentName           string                         `json:"agentName"`
	PoolCode            string                         `json:"poolCode"`
	Status              int32                          `json:"status"`
	DrainStatus         int32                          `json:"drainStatus"`
	ProtocolVersion     int32                          `json:"protocolVersion"`
	AgentVersion        string                         `json:"agentVersion"`
	ArtifactMode        int32                          `json:"artifactMode"`
	CustomerStorageRef  string                         `json:"customerStorageRef,optional"`
	AllowedAppIds       []int64                        `json:"allowedAppIds"`
	Capabilities        []PlatformLocalAgentCapability `json:"capabilities"`
	CertificateSerial   string                         `json:"certificateSerial,optional"`
	CertificateNotAfter int64                          `json:"certificateNotAfter,optional"`
	LastHeartbeatAt     int64                          `json:"lastHeartbeatAt,optional"`
	CreateTime          int64                          `json:"createTime"`
	UpdateTime          int64                          `json:"updateTime"`
}

type PlatformLocalAgentCapability struct {
	CapabilityKey   string `json:"capabilityKey"`
	CapabilityValue string `json:"capabilityValue"`
}

type PlatformLocalAgentIdReq struct {
	Id       int64 `path:"id"`
	TenantId int64 `json:"tenantId,optional" form:"tenantId,optional"`
}

type PlatformLocalAgentListResp struct {
	RespBase
	Data  []PlatformLocalAgent `json:"data"`
	Total int64                `json:"total"`
}

type PlatformLocalAgentRegistrationResp struct {
	RespBase
	Data              PlatformLocalAgent `json:"data"`
	RegistrationToken string             `json:"registrationToken"`
	ExpiresAt         int64              `json:"expiresAt"`
}

type PlatformLocalAgentResp struct {
	RespBase
	Data PlatformLocalAgent `json:"data"`
}

type PlatformOpenApiCredential struct {
	Id                 int64    `json:"id"`
	TenantId           int64    `json:"tenantId"`
	CredentialName     string   `json:"credentialName"`
	KeyId              string   `json:"keyId"`
	Scopes             []int32  `json:"scopes"`
	AppIds             []int64  `json:"appIds"`
	IpAllowlist        []string `json:"ipAllowlist"`
	RateLimitPerMinute int32    `json:"rateLimitPerMinute"`
	Status             int32    `json:"status"`
	ExpiresAt          int64    `json:"expiresAt,optional"`
	GraceExpiresAt     int64    `json:"graceExpiresAt,optional"`
	RotatedFromId      int64    `json:"rotatedFromId"`
	LastUsedAt         int64    `json:"lastUsedAt,optional"`
	CreateBy           int64    `json:"createBy"`
	CreateTime         int64    `json:"createTime"`
	UpdateTime         int64    `json:"updateTime"`
}

type PlatformOpenApiCredentialListResp struct {
	RespBase
	Data []PlatformOpenApiCredential `json:"data"`
}

type PlatformOpenApiCredentialResp struct {
	RespBase
	Data PlatformOpenApiCredential `json:"data"`
}

type PlatformOpenApiCredentialSecret struct {
	Credential PlatformOpenApiCredential `json:"credential"`
	ApiKey     string                    `json:"apiKey"`
}

type PlatformOpenApiCredentialSecretResp struct {
	RespBase
	Data PlatformOpenApiCredentialSecret `json:"data"`
}

type PlatformSigningConfig struct {
	Id                int64  `json:"id"`
	TenantId          int64  `json:"tenantId"`
	AppId             int64  `json:"appId"`
	Name              string `json:"name"`
	KeystoreObjectKey string `json:"keystoreObjectKey,optional"`
	KeystoreObjectId  int64  `json:"keystoreObjectId"`
	KeyAlias          string `json:"keyAlias"`
	SecretRef         string `json:"secretRef,optional"`
	Status            int64  `json:"status"`
	LastVerifiedAt    int64  `json:"lastVerifiedAt,optional"`
	CreateBy          int64  `json:"createBy"`
	CreateTime        int64  `json:"createTime"`
	UpdateTime        int64  `json:"updateTime"`
	CertificateSha256 string `json:"certificateSha256,optional"`
	SigningMode       int32  `json:"signingMode"`
}

type PlatformSigningConfigListResp struct {
	RespBase
	Data []PlatformSigningConfig `json:"data"`
}

type PlatformSigningConfigResp struct {
	RespBase
	Data PlatformSigningConfig `json:"data"`
}

type PlatformSourceArtifact struct {
	Id                 int64  `json:"id"`
	AppId              int64  `json:"appId"`
	VersionId          int64  `json:"versionId"`
	IntegrationId      int64  `json:"integrationId"`
	RepositoryId       int64  `json:"repositoryId"`
	ArtifactSource     int32  `json:"artifactSource"`
	ExternalArtifactId string `json:"externalArtifactId"`
	CommitSha          string `json:"commitSha"`
	PipelineRef        string `json:"pipelineRef,optional"`
	JobRef             string `json:"jobRef,optional"`
	ArtifactSha256     string `json:"artifactSha256"`
	StorageObjectId    int64  `json:"storageObjectId"`
	CreateTime         int64  `json:"createTime"`
}

type PlatformSourceArtifactImportResp struct {
	RespBase
	Data PlatformSourceArtifactImportResult `json:"data"`
}

type PlatformSourceArtifactImportResult struct {
	Version  PlatformVersion        `json:"version"`
	Artifact PlatformSourceArtifact `json:"artifact"`
}

type PlatformSourceAvailableRepository struct {
	ExternalRepositoryId string `json:"externalRepositoryId"`
	RepositoryFullName   string `json:"repositoryFullName"`
	DefaultBranch        string `json:"defaultBranch,optional"`
}

type PlatformSourceAvailableRepositoryListResp struct {
	RespBase
	Data []PlatformSourceAvailableRepository `json:"data"`
}

type PlatformSourceBuildTrigger struct {
	Id                  int64   `json:"id"`
	TenantId            int64   `json:"tenantId"`
	RepositoryId        int64   `json:"repositoryId"`
	AppId               int64   `json:"appId"`
	TriggerName         string  `json:"triggerName"`
	EventType           int32   `json:"eventType"`
	RefPattern          string  `json:"refPattern"`
	ArtifactSelector    string  `json:"artifactSelector"`
	ChannelIds          []int64 `json:"channelIds"`
	SigningConfigId     int64   `json:"signingConfigId"`
	BrandingProfileId   int64   `json:"brandingProfileId,optional"`
	WhiteLabelProductId int64   `json:"whiteLabelProductId,optional"`
	Priority            int32   `json:"priority"`
	PoolCode            string  `json:"poolCode"`
	VersionNamePrefix   string  `json:"versionNamePrefix,optional"`
	Status              int32   `json:"status"`
	Platform            int32   `json:"platform"`
	RepositoryFullName  string  `json:"repositoryFullName"`
	CreateTime          int64   `json:"createTime"`
	UpdateTime          int64   `json:"updateTime"`
}

type PlatformSourceBuildTriggerListResp struct {
	RespBase
	Data []PlatformSourceBuildTrigger `json:"data"`
}

type PlatformSourceBuildTriggerResp struct {
	RespBase
	Data PlatformSourceBuildTrigger `json:"data"`
}

type PlatformSourceBuildTriggerSecret struct {
	Trigger       PlatformSourceBuildTrigger `json:"trigger"`
	WebhookUrl    string                     `json:"webhookUrl"`
	SigningSecret string                     `json:"signingSecret"`
}

type PlatformSourceBuildTriggerSecretResp struct {
	RespBase
	Data PlatformSourceBuildTriggerSecret `json:"data"`
}

type PlatformSourceIntegration struct {
	Id              int64  `json:"id"`
	TenantId        int64  `json:"tenantId"`
	Platform        int32  `json:"platform"`
	IntegrationName string `json:"integrationName"`
	InstallationRef string `json:"installationRef"`
	TokenExpiresAt  int64  `json:"tokenExpiresAt,optional"`
	Status          int32  `json:"status"`
	LastSyncAt      int64  `json:"lastSyncAt,optional"`
	CreateBy        int64  `json:"createBy"`
	CreateTime      int64  `json:"createTime"`
	UpdateTime      int64  `json:"updateTime"`
}

type PlatformSourceIntegrationListResp struct {
	RespBase
	Data []PlatformSourceIntegration `json:"data"`
}

type PlatformSourceIntegrationResp struct {
	RespBase
	Data PlatformSourceIntegration `json:"data"`
}

type PlatformSourceOAuthAuthorization struct {
	AuthorizationUrl string `json:"authorizationUrl"`
}

type PlatformSourceOAuthAuthorizationResp struct {
	RespBase
	Data PlatformSourceOAuthAuthorization `json:"data"`
}

type PlatformSourceRepository struct {
	Id                   int64  `json:"id"`
	TenantId             int64  `json:"tenantId"`
	IntegrationId        int64  `json:"integrationId"`
	ExternalRepositoryId string `json:"externalRepositoryId"`
	RepositoryFullName   string `json:"repositoryFullName"`
	DefaultBranch        string `json:"defaultBranch,optional"`
	PermissionLevel      string `json:"permissionLevel"`
	Status               int32  `json:"status"`
	CreateTime           int64  `json:"createTime"`
	UpdateTime           int64  `json:"updateTime"`
}

type PlatformSourceRepositoryListResp struct {
	RespBase
	Data []PlatformSourceRepository `json:"data"`
}

type PlatformSourceRepositoryResp struct {
	RespBase
	Data PlatformSourceRepository `json:"data"`
}

type PlatformSourceWebhookEvent struct {
	Id                 int64   `json:"id"`
	TriggerId          int64   `json:"triggerId"`
	ProviderEventId    string  `json:"providerEventId"`
	ProviderEventType  string  `json:"providerEventType"`
	SourceRef          string  `json:"sourceRef"`
	CommitSha          string  `json:"commitSha"`
	ArtifactSource     int32   `json:"artifactSource"`
	ExternalArtifactId string  `json:"externalArtifactId"`
	ReleaseRef         string  `json:"releaseRef,optional"`
	PipelineRef        string  `json:"pipelineRef,optional"`
	JobRef             string  `json:"jobRef,optional"`
	PayloadSha256      string  `json:"payloadSha256"`
	VersionCode        int64   `json:"versionCode"`
	VersionName        string  `json:"versionName"`
	Status             int32   `json:"status"`
	Attempt            int32   `json:"attempt"`
	VersionId          int64   `json:"versionId,optional"`
	BuildTaskIds       []int64 `json:"buildTaskIds,optional"`
	ErrorMessage       string  `json:"errorMessage,optional"`
	CreateTime         int64   `json:"createTime"`
	UpdateTime         int64   `json:"updateTime"`
}

type PlatformSourceWebhookEventListResp struct {
	RespBase
	Data []PlatformSourceWebhookEvent `json:"data"`
}

type PlatformStorageDownload struct {
	DownloadUrl string `json:"downloadUrl"`
	ExpiresAt   int64  `json:"expiresAt"`
}

type PlatformStorageDownloadResp struct {
	RespBase
	Data PlatformStorageDownload `json:"data"`
}

type PlatformStorageObject struct {
	ObjectId     int64  `json:"objectId"`
	AppId        int64  `json:"appId"`
	ObjectType   int32  `json:"objectType"`
	OriginalName string `json:"originalName"`
	SizeBytes    int64  `json:"sizeBytes"`
	Sha256       string `json:"sha256"`
	Status       int32  `json:"status"`
	StorageMode  int32  `json:"storageMode"`
	OwnerAgentId int64  `json:"ownerAgentId"`
}

type PlatformStorageObjectIdReq struct {
	Id int64 `path:"id"`
}

type PlatformTenantBillingReq struct {
	TenantId int64 `form:"tenantId,optional"`
}

type PlatformTenantBillingResp struct {
	RespBase
	Subscription PlatformTenantSubscription `json:"subscription"`
	Entitlement  PlatformTenantEntitlement  `json:"entitlement"`
	Plan         PlatformBillingPlan        `json:"plan"`
}

type PlatformTenantEntitlement struct {
	Id                  int64  `json:"id"`
	TenantId            int64  `json:"tenantId"`
	PlanId              int64  `json:"planId"`
	PlanVersion         int32  `json:"planVersion"`
	BuildsPerCycle      int64  `json:"buildsPerCycle"`
	MaxBuildConcurrency int32  `json:"maxBuildConcurrency"`
	StorageBytes        int64  `json:"storageBytes"`
	MaxUploadBytes      int64  `json:"maxUploadBytes"`
	TeamSeats           int32  `json:"teamSeats"`
	ApiRateLimit        int32  `json:"apiRateLimit"`
	ChargeFailedBuild   bool   `json:"chargeFailedBuild"`
	ChargeCacheHit      bool   `json:"chargeCacheHit"`
	ChargeRetryBuild    bool   `json:"chargeRetryBuild"`
	OverrideJson        string `json:"overrideJson,optional"`
	ValidFrom           int64  `json:"validFrom"`
	ValidUntil          int64  `json:"validUntil"`
	Status              int32  `json:"status"`
	Revision            int64  `json:"revision"`
}

type PlatformTenantSubscription struct {
	Id                     int64  `json:"id"`
	TenantId               int64  `json:"tenantId"`
	PlanId                 int64  `json:"planId"`
	PlanVersion            int32  `json:"planVersion"`
	Status                 int32  `json:"status"`
	Source                 int32  `json:"source"`
	ExternalCustomerId     string `json:"externalCustomerId,optional"`
	ExternalSubscriptionId string `json:"externalSubscriptionId,optional"`
	CurrentPeriodStart     int64  `json:"currentPeriodStart"`
	CurrentPeriodEnd       int64  `json:"currentPeriodEnd"`
	CancelAtPeriodEnd      bool   `json:"cancelAtPeriodEnd"`
	GraceUntil             int64  `json:"graceUntil,optional"`
	PendingPlanId          int64  `json:"pendingPlanId"`
	PendingPlanVersion     int32  `json:"pendingPlanVersion"`
	CreateTime             int64  `json:"createTime"`
	UpdateTime             int64  `json:"updateTime"`
}

type PlatformUploadTicket struct {
	ObjectId  int64  `json:"objectId"`
	UploadUrl string `json:"uploadUrl"`
	ExpiresAt int64  `json:"expiresAt"`
}

type PlatformUsageMetricSummary struct {
	Metric           int32 `json:"metric"`
	UsedQuantity     int64 `json:"usedQuantity"`
	ReservedQuantity int64 `json:"reservedQuantity"`
	LimitQuantity    int64 `json:"limitQuantity"`
	UsagePercent     int32 `json:"usagePercent"`
}

type PlatformVersion struct {
	Id                int64  `json:"id"`
	TenantId          int64  `json:"tenantId"`
	AppId             int64  `json:"appId"`
	VersionCode       int64  `json:"versionCode"`
	VersionName       string `json:"versionName"`
	SourceApkUrl      string `json:"sourceApkUrl,optional"`
	SourceApkSha256   string `json:"sourceApkSha256,optional"`
	SourceApkObjectId int64  `json:"sourceApkObjectId"`
	ReleaseNotes      string `json:"releaseNotes,optional"`
	BuildConfigJson   string `json:"buildConfigJson,optional"`
	Status            int32  `json:"status"`
	PublishedAt       int64  `json:"publishedAt,optional"`
	CreateBy          int64  `json:"createBy"`
	CreateTime        int64  `json:"createTime"`
	UpdateTime        int64  `json:"updateTime"`
}

type PlatformVersionListResp struct {
	RespBase
	Data []PlatformVersion `json:"data"`
}

type PlatformVersionResp struct {
	RespBase
	Data PlatformVersion `json:"data"`
}

type PlatformWebhookDelivery struct {
	Id                  int64  `json:"id"`
	TenantId            int64  `json:"tenantId"`
	EndpointId          int64  `json:"endpointId"`
	EventId             string `json:"eventId"`
	EventType           string `json:"eventType"`
	Attempt             int32  `json:"attempt"`
	Status              int32  `json:"status"`
	ResponseStatus      int32  `json:"responseStatus"`
	ResponseBodyExcerpt string `json:"responseBodyExcerpt,optional"`
	ErrorMessage        string `json:"errorMessage,optional"`
	NextRetryAt         int64  `json:"nextRetryAt"`
	DeliveredAt         int64  `json:"deliveredAt,optional"`
	CreateTime          int64  `json:"createTime"`
	UpdateTime          int64  `json:"updateTime"`
}

type PlatformWebhookDeliveryListResp struct {
	RespBase
	Data []PlatformWebhookDelivery `json:"data"`
}

type PlatformWebhookDeliveryResp struct {
	RespBase
	Data PlatformWebhookDelivery `json:"data"`
}

type PlatformWebhookEndpoint struct {
	Id            int64    `json:"id"`
	TenantId      int64    `json:"tenantId"`
	EndpointName  string   `json:"endpointName"`
	EndpointUrl   string   `json:"endpointUrl"`
	EventTypes    []string `json:"eventTypes"`
	SecretHint    string   `json:"secretHint"`
	MaxAttempts   int32    `json:"maxAttempts"`
	Status        int32    `json:"status"`
	LastSuccessAt int64    `json:"lastSuccessAt,optional"`
	LastFailureAt int64    `json:"lastFailureAt,optional"`
	CreateBy      int64    `json:"createBy"`
	CreateTime    int64    `json:"createTime"`
	UpdateTime    int64    `json:"updateTime"`
}

type PlatformWebhookEndpointListResp struct {
	RespBase
	Data []PlatformWebhookEndpoint `json:"data"`
}

type PlatformWebhookEndpointResp struct {
	RespBase
	Data PlatformWebhookEndpoint `json:"data"`
}

type PlatformWebhookEndpointSecret struct {
	Endpoint      PlatformWebhookEndpoint `json:"endpoint"`
	SigningSecret string                  `json:"signingSecret"`
}

type PlatformWebhookEndpointSecretResp struct {
	RespBase
	Data PlatformWebhookEndpointSecret `json:"data"`
}

type PlatformWhiteLabelProduct struct {
	Id                  int64  `json:"id"`
	TenantId            int64  `json:"tenantId"`
	AppId               int64  `json:"appId"`
	ProductCode         string `json:"productCode"`
	ProductName         string `json:"productName"`
	TemplateId          int64  `json:"templateId"`
	TemplateRevision    int32  `json:"templateRevision"`
	BrandingProfileId   int64  `json:"brandingProfileId"`
	PackageName         string `json:"packageName"`
	SigningConfigId     int64  `json:"signingConfigId"`
	ParameterValuesJson string `json:"parameterValuesJson,optional"`
	Status              int32  `json:"status"`
	CreateTime          int64  `json:"createTime"`
	UpdateTime          int64  `json:"updateTime"`
}

type PlatformWhiteLabelProductListResp struct {
	RespBase
	Data []PlatformWhiteLabelProduct `json:"data"`
}

type PlatformWhiteLabelProductPreflightResp struct {
	RespBase
	Compatible bool   `json:"compatible"`
	ReportJson string `json:"reportJson"`
}

type PlatformWhiteLabelProductResp struct {
	RespBase
	Data PlatformWhiteLabelProduct `json:"data"`
}

type PlatformWhiteLabelTemplate struct {
	Id                     int64  `json:"id"`
	TenantId               int64  `json:"tenantId"`
	AppId                  int64  `json:"appId"`
	TemplateCode           string `json:"templateCode"`
	TemplateName           string `json:"templateName"`
	SourceVersionId        int64  `json:"sourceVersionId"`
	ParameterSchemaJson    string `json:"parameterSchemaJson,optional"`
	CompatibilityRulesJson string `json:"compatibilityRulesJson,optional"`
	Status                 int32  `json:"status"`
	PublishedRevision      int32  `json:"publishedRevision"`
	CreateTime             int64  `json:"createTime"`
	UpdateTime             int64  `json:"updateTime"`
}

type PlatformWhiteLabelTemplateListResp struct {
	RespBase
	Data []PlatformWhiteLabelTemplate `json:"data"`
}

type PlatformWhiteLabelTemplateResp struct {
	RespBase
	Data PlatformWhiteLabelTemplate `json:"data"`
}

type PlatformWhiteLabelTemplateRevision struct {
	Id                    int64  `json:"id"`
	TenantId              int64  `json:"tenantId"`
	TemplateId            int64  `json:"templateId"`
	Revision              int32  `json:"revision"`
	PackageNameRuleJson   string `json:"packageNameRuleJson"`
	ManifestPatchJson     string `json:"manifestPatchJson,optional"`
	ResourcePatchJson     string `json:"resourcePatchJson,optional"`
	ExtensionFilesJson    string `json:"extensionFilesJson,optional"`
	ExpectedArtifactsJson string `json:"expectedArtifactsJson,optional"`
	Checksum              string `json:"checksum"`
	Status                int32  `json:"status"`
	CreateTime            int64  `json:"createTime"`
}

type PlatformWhiteLabelTemplateRevisionIdReq struct {
	Id       int64 `path:"id"`
	Revision int32 `path:"revision"`
}

type PlatformWhiteLabelTemplateRevisionListResp struct {
	RespBase
	Data []PlatformWhiteLabelTemplateRevision `json:"data"`
}

type PlatformWhiteLabelTemplateRevisionResp struct {
	RespBase
	Data PlatformWhiteLabelTemplateRevision `json:"data"`
}

type PreparePlatformAirGappedExportReq struct {
	AgentId        int64 `json:"agentId"`
	TaskId         int64 `json:"taskId"`
	ExpiresSeconds int64 `json:"expiresSeconds,optional"`
}

type ProfileData struct {
	User  ProfileUser `json:"user"`
	Menus []MenuNode  `json:"menus"`
	Perms []string    `json:"perms"`
}

type ProfileResp struct {
	RespBase
	Data ProfileData `json:"data"`
}

type ProfileUser struct {
	Id               int64  `json:"id"`
	Username         string `json:"username"`
	Nickname         string `json:"nickname,optional"`
	Avatar           string `json:"avatar,optional"`
	TenantId         int64  `json:"tenantId"` // 所属租户ID：0=系统侧，>0=租户ID
	UserType         int64  `json:"userType"` // 用户类型：1系统管理员 2租户主账号 3租户管理员
	IsOwner          int64  `json:"isOwner"`  // 是否租户主账号：1是 2否
	Google2FaEnabled int64  `json:"google2FaEnabled"`
}

type PublishPlatformWhiteLabelTemplateReq struct {
	Id       int64 `path:"id"`
	Revision int32 `json:"revision"`
}

type RecoverPlatformBuilderNodeReq struct {
	Id     int64  `path:"id"`
	Reason string `json:"reason"`
}

type ResetUserPwdReq struct {
	Id       int64  `json:"id"`
	Password string `json:"password"`
}

type RespBase struct {
	Code       int32  `json:"code"`
	Msg        string `json:"msg"`
	Total      int64  `json:"total,optional"`
	HasNext    bool   `json:"hasNext,optional"`
	HasPrev    bool   `json:"hasPrev,optional"`
	NextCursor int64  `json:"nextCursor,optional"`
	PrevCursor int64  `json:"prevCursor,optional"`
}

type RetryPlatformBuildTaskReq struct {
	Id       int64 `path:"id"`
	Priority int32 `json:"priority,optional"`
}

type RevokePlatformLocalAgentReq struct {
	Id       int64  `path:"id"`
	TenantId int64  `json:"tenantId,optional"`
	Reason   string `json:"reason"`
}

type RevokePlatformOpenApiCredentialReq struct {
	Id int64 `path:"id"`
}

type RotatePlatformOpenApiCredentialReq struct {
	Id           int64 `path:"id"`
	GraceSeconds int64 `json:"graceSeconds,optional"`
}

type SysConfigCreateReq struct {
	TenantId    int64  `json:"tenantId,optional"`
	ConfigKey   string `json:"configKey" validate:"required"`
	ConfigValue string `json:"configValue"`
	Remark      string `json:"remark,optional"`
}

type SysConfigDeleteReq struct {
	Id int64 `path:"id" validate:"required"`
}

type SysConfigItem struct {
	Id          int64  `json:"id"`
	TenantId    int64  `json:"tenantId"`
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
	Remark      string `json:"remark,optional"`
	CreateTimes int64  `json:"createTimes"`
	UpdateTimes int64  `json:"updateTimes"`
}

type SysConfigListReq struct {
	PageReq
	Keyword  string `form:"keyword,optional"`
	TenantId int64  `form:"tenantId,optional"`
}

type SysConfigListResp struct {
	RespBase
	Data []SysConfigItem `json:"data"`
}

type SysConfigUpdateReq struct {
	Id          int64  `json:"id" validate:"required"`
	ConfigKey   string `json:"configKey,optional"`
	ConfigValue string `json:"configValue,optional"`
	Remark      string `json:"remark,optional"`
}

type SysMenuCreateReq struct {
	ParentId  int64  `json:"parentId,optional"`
	Name      string `json:"name"`
	MenuType  int64  `json:"menuType"`
	Method    string `json:"method,optional"` // GET POST PUT DELETE
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Sort      int64  `json:"sort,optional"`
	Visible   int64  `json:"visible,optional"`
	Enabled   int64  `json:"enabled,optional"`
	Perms     string `json:"perms,optional"`
	AppScope  int64  `json:"appScope"`
}

type SysMenuDeleteReq struct {
	Id int64 `path:"id"`
}

type SysMenuItem struct {
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parentId"`
	Name      string `json:"name"`
	MenuType  int64  `json:"menuType"`        // 1目录 2菜单 3按钮
	Method    string `json:"method,optional"` // GET POST PUT DELETE
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Sort      int64  `json:"sort"`
	Visible   int64  `json:"visible"`
	Enabled   int64  `json:"enabled"`
	Perms     string `json:"perms,optional"`
	AppScope  int64  `json:"appScope"`
}

type SysMenuListReq struct {
	PageReq
	Keyword  string `form:"keyword,optional"`  // 按 name/perms 模糊
	Enabled  int64  `form:"enabled,optional"`  // 0未知 1启用 2禁用
	Visible  int64  `form:"visible,optional"`  // 0/1
	MenuType int64  `form:"menuType,optional"` // 1/2/3
	AppScope int64  `form:"appScope,optional"`
}

type SysMenuListResp struct {
	RespBase
	Data []SysMenuItem `json:"data"`
}

type SysMenuTreeReq struct {
	RoleId int64 `path:"roleId"`
}

type SysMenuTreeResp struct {
	RespBase
	Data []SysMenuItem `json:"data"`
}

type SysMenuUpdateReq struct {
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parentId,optional"`
	Name      string `json:"name,optional"`
	MenuType  int64  `json:"menuType,optional"`
	Method    string `json:"method,optional"` // GET POST PUT DELETE
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Sort      int64  `json:"sort,optional"`
	Visible   int64  `json:"visible,optional"`
	Enabled   int64  `json:"enabled,optional"`
	Perms     string `json:"perms,optional"`
	AppScope  int64  `json:"appScope,optional"`
}

type SysPermItem struct {
	PermKey  string `json:"key"`  // 唯一权限标识（如 sys:role:add）
	Name     string `json:"name"` // 展示名称（如 新增角色）
	AppScope int64  `json:"appScope"`
}

type SysPermListResp struct {
	RespBase
	Data []SysPermItem `json:"data"`
}

type SysRoleCreateReq struct {
	TenantId int64  `json:"tenantId"`
	Name     string `json:"name"`
	Code     string `json:"code"`
	Enabled  int64  `json:"enabled,optional"`
	Remark   string `json:"remark,optional"`
	AppScope int64  `json:"appScope"`
}

type SysRoleDeleteReq struct {
	Id int64 `path:"id"`
}

type SysRoleGrantDetail struct {
	RoleId   int64    `json:"roleId"`
	MenuIds  []int64  `json:"menuIds"`
	PermKeys []string `json:"permKeys"`
}

type SysRoleGrantDetailReq struct {
	Id int64 `path:"id"`
}

type SysRoleGrantDetailResp struct {
	RespBase
	Data SysRoleGrantDetail `json:"data"`
}

type SysRoleGrantReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type SysRoleItem struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Enabled     int64  `json:"enabled"`
	Remark      string `json:"remark,optional"`
	TenantId    int64  `json:"tenantId"`
	CreateTimes int64  `json:"createTimes"`
	AppScope    int64  `json:"appScope"`
}

type SysRoleListReq struct {
	PageReq
	Keyword  string `form:"keyword,optional"`
	Enabled  int64  `form:"enabled,optional"`
	AppScope int64  `form:"appScope,optional"`
}

type SysRoleListResp struct {
	RespBase
	Data []SysRoleItem `json:"data"`
}

type SysRoleUpdateReq struct {
	Id       int64  `json:"id"`
	TenantId int64  `json:"tenantId,optional"`
	Name     string `json:"name,optional"`
	Enabled  int64  `json:"enabled,optional"`
	Remark   string `json:"remark,optional"`
	AppScope int64  `json:"appScope,optional"`
}

type SysTenantCreateReq struct {
	Username       string `json:"username"`
	TenantName     string `json:"tenantName"`
	TenantPassword string `json:"tenantPassword"`
	Enabled        int64  `json:"enabled"`
	ExpireTime     int64  `json:"expireTime"`
	ContactName    string `json:"contactName,optional"`
	ContactPhone   string `json:"contactPhone,optional"`
	Remark         string `json:"remark,optional"`
}

type SysTenantDeleteReq struct {
	Id int64 `path:"id"`
}

type SysTenantDetailReq struct {
	TenantId   *int64  `form:"tenantId,optional"`
	TenantCode *string `form:"tenantCode,optional"`
}

type SysTenantDetailResp struct {
	RespBase
	Data SysTenantItem `json:"data"`
}

type SysTenantDomainCreateReq struct {
	TenantId int64  `json:"tenantId"`
	Origin   string `json:"origin"`
	Status   int64  `json:"status"`
	Priority int64  `json:"priority"`
}

type SysTenantDomainDeleteReq struct {
	Id int64 `path:"id"`
}

type SysTenantDomainItem struct {
	Id          int64  `json:"id"`
	TenantId    int64  `json:"tenantId"`
	Origin      string `json:"origin"`
	Status      int64  `json:"status"`
	Priority    int64  `json:"priority"`
	CreateTimes int64  `json:"createTimes"`
	UpdateTimes int64  `json:"updateTimes"`
}

type SysTenantDomainListReq struct {
	TenantId int64 `form:"tenantId"`
}

type SysTenantDomainListResp struct {
	RespBase
	Data []SysTenantDomainItem `json:"data"`
}

type SysTenantDomainUpdateReq struct {
	Id       int64  `json:"id"`
	Origin   string `json:"origin"`
	Status   int64  `json:"status"`
	Priority int64  `json:"priority"`
}

type SysTenantItem struct {
	Id           int64  `json:"id"`
	TenantCode   string `json:"tenantCode"`
	TenantName   string `json:"tenantName"`
	Enabled      int64  `json:"enabled"`
	ExpireTime   int64  `json:"expireTime"`
	ContactName  string `json:"contactName,optional"`
	ContactPhone string `json:"contactPhone,optional"`
	Remark       string `json:"remark,optional"`
	CreateTimes  int64  `json:"createTimes"`
	UpdateTimes  int64  `json:"updateTimes"`
}

type SysTenantListReq struct {
	PageReq
	Keyword      string `form:"keyword,optional"` // 按 tenant_code/tenant_name/contact_name/contact_phone 模糊
	Enabled      int64  `form:"enabled,optional"` // 0全部 1启用 2禁用
	TenantCode   string `form:"tenantCode,optional"`
	TenantName   string `form:"tenantName,optional"`
	ContactName  string `form:"contactName,optional"`
	ContactPhone string `form:"contactPhone,optional"`
}

type SysTenantListResp struct {
	RespBase
	Data []SysTenantItem `json:"data"`
}

type SysTenantUpdateReq struct {
	Id             int64  `json:"id"`
	TenantName     string `json:"tenantName,optional"`
	TenantPassword string `json:"tenantPassword,optional"`
	Enabled        int64  `json:"enabled,optional"`
	ExpireTime     int64  `json:"expireTime,optional"`
	ContactName    string `json:"contactName,optional"`
	ContactPhone   string `json:"contactPhone,optional"`
	Remark         string `json:"remark,optional"`
}

type SysUserCreateReq struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Nickname string  `json:"nickname,optional"`
	Enabled  int64   `json:"enabled,optional"` // 0未知 1启用 2禁用
	RoleIds  []int64 `json:"roleIds,optional"`
	AppScope int64   `json:"appScope"`
}

type SysUserDeleteReq struct {
	Id int64 `path:"id"`
}

type SysUserDetailReq struct {
	Id int64 `form:"id"`
}

type SysUserDetailResp struct {
	RespBase
	Data SysUserItem `json:"data"`
}

type SysUserItem struct {
	Id               int64   `json:"id"`
	Username         string  `json:"username"`
	Nickname         string  `json:"nickname"`
	Enabled          int64   `json:"enabled"`
	RoleIds          []int64 `json:"roleIds"`
	CreateTimes      int64   `json:"createTimes"`
	Google2FaEnabled int64   `json:"google2FaEnabled"`
	TenantId         int64   `json:"tenantId"`
	UserType         int64   `json:"userType"`
	IsOwner          int64   `json:"isOwner"`
	Avatar           string  `json:"avatar"`
	PermsVer         int64   `json:"permsVer"`
	LastLoginIp      string  `json:"lastLoginIp"`
	LastLoginAt      int64   `json:"lastLoginAt"`
	CreateBy         int64   `json:"createBy"`
	UpdateTimes      int64   `json:"updateTimes"`
	AppScope         int64   `json:"appScope"`
}

type SysUserListReq struct {
	PageReq
	Keyword  string `form:"keyword,optional"`
	Enabled  int64  `form:"enabled,optional"`
	AppScope int64  `form:"appScope,optional"`
}

type SysUserListResp struct {
	RespBase
	Data []SysUserItem `json:"data"`
}

type SysUserUpdateReq struct {
	Id       int64   `json:"id"`
	Nickname string  `json:"nickname,optional"`
	Enabled  int64   `json:"enabled,optional"`
	RoleIds  []int64 `json:"roleIds,optional"`
	AppScope int64   `json:"appScope,optional"`
}

type TimeRange struct {
	StartTime int64 `form:"startTime,optional"`
	EndTime   int64 `form:"endTime,optional"`
}

type UpdatePlatformBrandingProfileReq struct {
	Id                   int64  `path:"id"`
	ProfileName          string `json:"profileName"`
	AppName              string `json:"appName"`
	LogoObjectId         int64  `json:"logoObjectId"`
	SplashObjectId       int64  `json:"splashObjectId"`
	ApiHost              string `json:"apiHost"`
	RewriteMode          int32  `json:"rewriteMode"`
	LauncherIconTarget   string `json:"launcherIconTarget,optional"`
	SplashResourceTarget string `json:"splashResourceTarget,optional"`
	RuntimeConfigJson    string `json:"runtimeConfigJson,optional"`
}

type UpdatePlatformSourceBuildTriggerReq struct {
	Id                  int64   `path:"id"`
	TriggerName         string  `json:"triggerName"`
	EventType           int32   `json:"eventType"`
	RefPattern          string  `json:"refPattern,optional"`
	ArtifactSelector    string  `json:"artifactSelector"`
	ChannelIds          []int64 `json:"channelIds"`
	SigningConfigId     int64   `json:"signingConfigId,optional"`
	BrandingProfileId   int64   `json:"brandingProfileId,optional"`
	WhiteLabelProductId int64   `json:"whiteLabelProductId,optional"`
	Priority            int32   `json:"priority,optional"`
	PoolCode            string  `json:"poolCode,optional"`
	VersionNamePrefix   string  `json:"versionNamePrefix,optional"`
	Status              int32   `json:"status"`
}

type UpdatePlatformWebhookEndpointReq struct {
	Id           int64    `path:"id"`
	EndpointName string   `json:"endpointName"`
	EndpointUrl  string   `json:"endpointUrl"`
	EventTypes   []string `json:"eventTypes"`
	MaxAttempts  int32    `json:"maxAttempts"`
	Status       int32    `json:"status"`
}

type UpdatePlatformWhiteLabelProductReq struct {
	Id                  int64  `path:"id"`
	ProductName         string `json:"productName"`
	BrandingProfileId   int64  `json:"brandingProfileId"`
	PackageName         string `json:"packageName"`
	SigningConfigId     int64  `json:"signingConfigId"`
	ParameterValuesJson string `json:"parameterValuesJson,optional"`
	TemplateId          int64  `json:"templateId"`
	TemplateRevision    int32  `json:"templateRevision"`
}

type UpdatePlatformWhiteLabelTemplateReq struct {
	Id                     int64  `path:"id"`
	TemplateName           string `json:"templateName"`
	SourceVersionId        int64  `json:"sourceVersionId"`
	ParameterSchemaJson    string `json:"parameterSchemaJson,optional"`
	CompatibilityRulesJson string `json:"compatibilityRulesJson,optional"`
}

type UpdatePlatformWhiteLabelTemplateRevisionReq struct {
	Id                    int64  `path:"id"`
	Revision              int32  `path:"revision"`
	PackageNameRuleJson   string `json:"packageNameRuleJson"`
	ManifestPatchJson     string `json:"manifestPatchJson,optional"`
	ResourcePatchJson     string `json:"resourcePatchJson,optional"`
	ExtensionFilesJson    string `json:"extensionFilesJson,optional"`
	ExpectedArtifactsJson string `json:"expectedArtifactsJson,optional"`
}

type UpdateProfileReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Password string `json:"password,optional"`
}

type UpsertPlatformBuildConcurrencyPolicyReq struct {
	Id             int64  `json:"id,optional"`
	AppId          int64  `json:"appId,optional"`
	PoolCode       string `json:"poolCode,optional"`
	MaxConcurrency int32  `json:"maxConcurrency"`
	FairWeight     int32  `json:"fairWeight"`
	MaxPriority    int32  `json:"maxPriority"`
	Status         int32  `json:"status"`
}

type UpsertPlatformManualSubscriptionReq struct {
	TenantId          int64  `json:"tenantId"`
	PlanId            int64  `json:"planId"`
	PeriodStart       int64  `json:"periodStart"`
	PeriodEnd         int64  `json:"periodEnd"`
	GraceUntil        int64  `json:"graceUntil,optional"`
	OverrideJson      string `json:"overrideJson,optional"`
	ContractReference string `json:"contractReference"`
}
