// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package server

import (
	"context"

	"appforge/proto/system"
	"appforge/services/system/internal/logic/app"
	"appforge/services/system/internal/svc"
)

type AppServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedAppServer
}

func NewAppServer(svcCtx *svc.ServiceContext) *AppServer {
	return &AppServer{
		svcCtx: svcCtx,
	}
}

func (s *AppServer) SysConfigDetail(ctx context.Context, in *system.SysConfigDetailReq) (*system.SysConfigDetailResp, error) {
	l := applogic.NewSysConfigDetailLogic(ctx, s.svcCtx)
	return l.SysConfigDetail(in)
}

func (s *AppServer) SysTenantDetail(ctx context.Context, in *system.SysTenantDetailReq) (*system.SysTenantDetailResp, error) {
	l := applogic.NewSysTenantDetailLogic(ctx, s.svcCtx)
	return l.SysTenantDetail(in)
}
