// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: builder.proto

package builder

import (
	"context"

	"appforge/proto/builder"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BuildTask                   = builder.BuildTask
	BuildTaskResp               = builder.BuildTaskResp
	ClaimBuildTaskReq           = builder.ClaimBuildTaskReq
	CompleteBuildTaskReq        = builder.CompleteBuildTaskReq
	FailBuildTaskReq            = builder.FailBuildTaskReq
	HeartbeatBuildTaskReq       = builder.HeartbeatBuildTaskReq
	ReportBuildProgressReq      = builder.ReportBuildProgressReq
	RespBase                    = builder.RespBase
	SigningMaterialValidation   = builder.SigningMaterialValidation
	ValidateSigningMaterialReq  = builder.ValidateSigningMaterialReq
	ValidateSigningMaterialResp = builder.ValidateSigningMaterialResp

	Builder interface {
		// 使用实际签名工具校验签名材料，成功后方可创建可用签名配置。
		ValidateSigningMaterial(ctx context.Context, in *ValidateSigningMaterialReq, opts ...grpc.CallOption) (*ValidateSigningMaterialResp, error)
		ClaimBuildTask(ctx context.Context, in *ClaimBuildTaskReq, opts ...grpc.CallOption) (*BuildTaskResp, error)
		HeartbeatBuildTask(ctx context.Context, in *HeartbeatBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error)
		ReportBuildProgress(ctx context.Context, in *ReportBuildProgressReq, opts ...grpc.CallOption) (*RespBase, error)
		CompleteBuildTask(ctx context.Context, in *CompleteBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error)
		FailBuildTask(ctx context.Context, in *FailBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error)
	}

	defaultBuilder struct {
		cli zrpc.Client
	}
)

func NewBuilder(cli zrpc.Client) Builder {
	return &defaultBuilder{
		cli: cli,
	}
}

// 使用实际签名工具校验签名材料，成功后方可创建可用签名配置。
func (m *defaultBuilder) ValidateSigningMaterial(ctx context.Context, in *ValidateSigningMaterialReq, opts ...grpc.CallOption) (*ValidateSigningMaterialResp, error) {
	client := builder.NewBuilderClient(m.cli.Conn())
	return client.ValidateSigningMaterial(ctx, in, opts...)
}

func (m *defaultBuilder) ClaimBuildTask(ctx context.Context, in *ClaimBuildTaskReq, opts ...grpc.CallOption) (*BuildTaskResp, error) {
	client := builder.NewBuilderClient(m.cli.Conn())
	return client.ClaimBuildTask(ctx, in, opts...)
}

func (m *defaultBuilder) HeartbeatBuildTask(ctx context.Context, in *HeartbeatBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := builder.NewBuilderClient(m.cli.Conn())
	return client.HeartbeatBuildTask(ctx, in, opts...)
}

func (m *defaultBuilder) ReportBuildProgress(ctx context.Context, in *ReportBuildProgressReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := builder.NewBuilderClient(m.cli.Conn())
	return client.ReportBuildProgress(ctx, in, opts...)
}

func (m *defaultBuilder) CompleteBuildTask(ctx context.Context, in *CompleteBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := builder.NewBuilderClient(m.cli.Conn())
	return client.CompleteBuildTask(ctx, in, opts...)
}

func (m *defaultBuilder) FailBuildTask(ctx context.Context, in *FailBuildTaskReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := builder.NewBuilderClient(m.cli.Conn())
	return client.FailBuildTask(ctx, in, opts...)
}
